### ISSUE TITLE
Divisionalisation

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#101]

**Comment by prabhupdesh** [comment]
1. Purchase Invoice - division in header and lines should be same
2. if lines having multiple division, then division in header should be support

**Comment by prabhupdesh** [comment]
Conveyance ledger - 217500 - Employee code is dimension mandatory. Once employee code is populated auto populate employee's division as well

**Comment by prabhupdesh** [comment]
is this done?

**Comment by prabhupdesh** [comment]
#105

**Comment by prabhupdesh** [comment]
#105

**Comment by YashwanthGowdaJ** [comment]
Working on some other tasks. After completing those, will take up this.

**Comment by YashwanthGowdaJ** [comment]
Today I will take up this task.

WIP

**Comment by YashwanthGowdaJ** [comment]
As discussed with @prabhupdesh, no need to take care of header division. Anyhow lines division is flowing from GRN. 

Aged accounts payable report is based on VLE(dimensions from purchase invoice header). And @surajsrivastava1991 is working on line wise purchase invoice aged accounts payable (From VLE).

Need to make below change in Purchase Invoice.
Users need to select lines in purchase invoice after selecting all the dimensions in header. (To avoid dimension changes in lines)
If Entity, CS and division is blank, we should not allow them to select lines.

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan I am making Entity, CS and Division to be mandatory before selecting get receipt lines. 

Please check this to move to live.

**Comment by IT-Saravanan** [comment]
Purchase invoice test Case 
Purchase invoice No: 105U06210013 
after populating receipt lines in purchase invoice. user cannot edit the division in Purchase header

**Comment by YashwanthGowdaJ** [comment]
Moved to live. Close the task

**Comment by prabhupdesh** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/prabh/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/prabh/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



View By | Entity |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
  | Customer Group |   | Period type | Present Month | Last Month | Present Quarter | YTD
  | Customer Season |   | Period Filter | 010422..300422 |   |   |  
  | Division |   |   |   |   |   |  
  | Department |   |   |   |   |   |  
  | MIS Location |   |   |   |   |   |  
  |   |   |   |   |   |   |  
View By Filter | TRITAN |   |   |   |   |   |  
  |   |   |   |   |   |   |  
  |   |   | Bag | Wallet | Belt | Total |  
  |   | Sales | -26,15,71,300.67 | -68,31,36,275.81 | -21,24,58,526.24 | -1,15,71,66,102.73 |  
  |   | Incentives | -1,85,94,443.21 | -1,51,33,815.74 | -66,19,013.75 | -4,03,47,272.71 |  
  |   | Total Revenue | -28,01,65,743.88 | -69,82,70,091.56 | -21,90,77,540.00 | -1,19,75,13,375.44 |  
  |   | Cost of Goods Sold |   |   |   |   |  
  |   | Opening Stock | 20,30,25,010.80 | 17,66,58,033.17 | 7,81,95,028.12 | 45,78,78,072.10 |  
  |   | Purchases | 8,77,45,212.04 | 36,38,08,776.81 | 17,48,17,207.68 | 62,63,71,196.54 |  
  |   | Closing Stock | 5,18,54,717.39 | 15,77,23,316.82 | 13,50,91,322.66 | 34,46,69,356.87 |  
  |   | Cost of Goods Sold | 23,89,15,505.45 | 38,27,43,493.16 | 11,79,20,913.14 | 73,95,79,911.76 |  
  |   | Gross Profit | -4,12,50,238.43 | -31,55,26,598.39 | -10,11,56,626.86 | -45,79,33,463.68 |  
  |   | Factory Costs |   |   |   |   |  
  |   | Salaries | 92,23,589.07 | 1,65,65,831.00 | 19,93,912.07 | 2,77,83,332.14 |  
  |   | Wages | 8,46,82,171.80 | 10,84,65,509.34 | 2,60,31,728.55 | 21,91,79,409.69 |  
  |   | Non People Costs | 3,20,65,990.33 | 9,04,40,856.85 | 4,53,35,589.63 | 16,78,42,436.82 |  
  |   | Factory Cost Total | 12,59,71,751.20 | 21,54,72,197.20 | 7,33,61,230.25 | 41,48,05,178.65 |  
  |   | Factory Contribution | 8,47,21,512.77 | -10,00,54,401.20 | -2,77,95,396.60 | -4,31,28,285.03 |  
  |   | Accounting | 1,33,77,627.90 | 2,48,41,701.45 | 1,59,61,904.66 | 5,41,81,234.02 |  
  |   | Documentation | 17,14,965.46 | 51,08,262.14 | 22,52,513.24 | 90,75,740.84 |  
  |   | IT | 3,11,169.42 | 13,77,500.01 | 5,06,168.99 | 21,94,838.42 |  
  |   | Sourcing | 11,18,925.58 | 15,31,161.32 | 4,12,235.74 | 30,62,322.63 |  
  |   | Merchandising | 8,88,086.21 | 20,99,716.65 | 21,81,314.32 | 51,69,117.18 |  
  |   | HRD | 5,09,904.23 | 12,63,798.40 | 3,97,026.33 | 21,70,728.96 |  
  |   | Corporate | 15,52,511.78 | 27,61,927.03 | 7,66,248.91 | 50,80,687.72 |  
  |   | PD | 53,46,989.27 | 55,09,019.25 | 53,46,989.27 | 1,62,02,997.80 |  
  |   |   | 19,35,075.94 | 51,90,316.65 | 40,99,407.87 | 1,12,24,800.46 |  
  |   | Net Profit (Loss) | 9,80,99,140.67 | -7,52,12,699.75 | -1,18,33,491.94 | 1,10,52,948.98 |  



</body>

</html>

**Comment by prabhupdesh** [comment]
[Populating MIS GL Detailed Entry.docx](https://github.com/BPS-Industries/Navision/files/8332992/Populating.MIS.GL.Detailed.Entry.docx)
