### ISSUE TITLE
Job Work

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#102]

**Comment by prabhupdesh** [comment]
1. Create a batch job if quantity and remaining quantity are matching in a job work order, because only the price for output qty. get updated
2. Suraj to work on above
3. Meanwhile, ram to finish job work orders manually for month of march
4. Once batch job is ready, run the batch job month wise.
5. There may be cases when qty & remaining qty is not equal for which this data to be sent to veera and take confirmation for closure

**Comment by prabhupdesh** [comment]
is this done? status please!

**Comment by ramapandian14** [comment]
Till March 2021 We have closed the Job Work Order Manually.
After April 2021 need to create a batch job to close the Job Work.
