### ISSUE TITLE
Aged Account Payable by Division

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#105]
Aged Account Payable by Division

**Comment by prabhupdesh** [comment]
Suraj, Please show division column also in the report

**Comment by surajsrivastava1991** [comment]
Hi @prabhupdesh ,

Sure I will let you know, thanks

**Comment by prabhupdesh** [comment]
Report id 50037

**Comment by prabhupdesh** [comment]
The layout of this report needs some working.
Most of the cells are merged due to which I cannot place any filter. @surajsrivastava1991 please check

**Comment by prabhupdesh** [comment]
![image](https://user-images.githubusercontent.com/61455315/122527186-bb0efe00-d038-11eb-82f4-bf3f45583b04.png)

**Comment by prabhupdesh** [comment]
@surajsrivastava1991 please check this report urgently

**Comment by surajsrivastava1991** [comment]
Okay sir ,I will check and let you know,


Thanks
Suraj

**Comment by surajsrivastava1991** [comment]
[image: image.png]
Hi Team,
Please check the Report now.

Thanks
Suraj S

**Comment by surajsrivastava1991** [comment]
<img width="960" alt="Aging Report" src="https://user-images.githubusercontent.com/55792214/122536694-6ec8bb80-d042-11eb-9196-a0bc5ec7fb57.png">
@prabhupdesh 
Please check the report once and I have uploaded the screenshot, FYR

Thanks 
Suraj S.

**Comment by prabhupdesh** [comment]
Division still not coming. Pick it from dimension set entry

**Comment by prabhupdesh** [comment]
Division is showing now.
Need to differentiate which row is from vendor ledger entry and which row from lines. Please show a column called "Entry Source" and mention "VLE" or "Lines" respectively.
For type = item charge, data should be shown from respective GRN to which cost is applied. this data can come from value entry table by filtering on document no. Division should accordingly flow from value entry

**Comment by prabhupdesh** [comment]
If vendor is a foreign vendor, then line amount should be calculated from field "Line Amount".
If vendor is domestic vendor then line amount should be calculated from "Amount to vendor". Already working in this manner.

**Comment by surajsrivastava1991** [comment]
> If vendor is a foreign vendor, then line amount should be calculated from field "Line Amount".
> If vendor is domestic vendor then line amount should be calculated from "Amount to vendor". Already working in this manner.

This is done, now working on Value entry split whenever Charge Item comes

**Comment by prabhupdesh** [comment]
![image](https://user-images.githubusercontent.com/61455315/122736077-438dd880-d29d-11eb-8d29-b925624119ec.png)
@surajsrivastava1991

**Comment by surajsrivastava1991** [comment]
@prabhupdesh 

Please check the report once ,I have added the Line wise aging amount as well in the report.
FYR,
![image](https://user-images.githubusercontent.com/55792214/123062428-22a6be00-d42a-11eb-866f-c39d22b73cf1.png)

Thanks 
Suraj S.

**Comment by prabhupdesh** [comment]
Invoice no. to check for totals split case: 10511200291

**Comment by surajsrivastava1991** [comment]
@prabhupdesh 
FYR

![image](https://user-images.githubusercontent.com/55792214/123513554-7411b000-d6ab-11eb-918e-52818b3f583d.png)

**Comment by surajsrivastava1991** [comment]
@prabhupdesh 

Please find the attachment, I have done the local to foreign Currency conversion for VE (Actual Cost (LCY)) and remaining calculation as well.

For your reference ,I have attached the report Excel, Please check and confirm.

Thanks 
Suraj S.
[Report50037.xlsx](https://github.com/BPS-Industries/Navision/files/6735694/Report50037.xlsx)
