### ISSUE TITLE
Item aging report

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#107]

**Comment by prabhupdesh** [comment]
Item aging report is by posting date. Need a option to show item aging by GRN date

**Comment by ramapandian14** [comment]
Item Age -Composition by Value
--------------------------------------
I have run the report and i have found a mismatch  for value

These report is run based on cost amount actual/qty =Unit Cost
After Finding Unit Cost it will be multiplied by Rem.Qty.

**Comment by ramapandian14** [comment]
Today i will run the report and compare the values for Stock Register vs Item age compoistion-Value

**Comment by ramapandian14** [comment]
I have generated a report for both entity and started to check the values in report..

**Comment by ramapandian14** [comment]
I am working on Item age composition value- GRN Date via application entry table.
I will update on today asap..
