### ISSUE TITLE
Employee loan status report

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#108]

**Comment by prabhupdesh** [comment]
Done

**Comment by prabhupdesh** [comment]
@nitesh, as discussed need to take care if loan is completed. There may be a possibility when remaining amount <> 0 but completed is true, in such case, remaining amount should be treated as 0

**Comment by prabhupdesh** [comment]
Scenario tested with emp id: 40001
![image](https://user-images.githubusercontent.com/61455315/122642338-a198af80-d127-11eb-8c39-80328ba1cb91.png)





<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:///C:/Users/prabh/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel="File-List" href="file:///C:/Users/prabh/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>





40001
--












<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:///C:/Users/prabh/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel="File-List" href="file:///C:/Users/prabh/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>





40001
--

**Comment by prabhupdesh** [comment]
@NiteshTLW working on this

**Comment by NiteshTLW** [comment]
Sir, will update the same.

**Comment by NiteshTLW** [comment]
Completed.
