### ISSUE TITLE
TL-027/19-20 mismatch

### ISSUE THREAD

**Issue by dhivyabarathi** [BPS-Industries/Navision#109]

**Comment by dhivyabarathi** [comment]
#110

**Comment by prabhupdesh** [comment]
Dhivya, please mention the mismatched points here

**Comment by NiteshTLW** [comment]
The following things are not matching:
1. Value of price for Style No. N72317
2. LC Details missing 
4. Notify II address missing and when to display
5. DBK code values and when to display
6. Consignee address data missing

Dear, @IT-Saravanan Please advise for points 2 to 5

**Comment by NiteshTLW** [comment]
This is matching the original Invoice and packing list.
