### ISSUE TITLE
TL-008/21-22 PACKING LIST AND INVOICE MISMATCH

### ISSUE THREAD

**Issue by dhivyabarathi** [BPS-Industries/Navision#110]

**Comment by dhivyabarathi** [comment]
In this po no both the invoice and packing list address , layout is mismatching

**Comment by NiteshTLW** [comment]
Issues:
1. Sales lines combined by FG no.
2. RoDTEP scheme declaration letter, when to dislpay
3. Custom Reference Field what data and when should be shown
4. Agent Commission information, when to display
5. Subheader, "Ladies", how to identify
6. Item is belts but size not displayed, what is the condition for it.

Dear @IT-Saravanan please advise in all these points

**Comment by NiteshTLW** [comment]
> In this po no both the invoice and packing list address , layout is mismatching

Adderss is mismatching because, document no. is not correct as per the link. Maybe wrong report is being verified. It can be No. TL-029/19-20 or TL-040/19-20 or any other. Please confirm

**Comment by NiteshTLW** [comment]
Points 2 & 5 resolved with Export Document Parameter(Ref. #106)
