### ISSUE TITLE
Fixed asset GRN/Invoicing (Cutting Dies)

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#111]
Cutting dies are being created as Fixed asset, then created as item to facilitate job work order creation and further grn of job work order items.
At the time of invoicing the job work invoice, "get receipt lines" will be used.
The requirement is to populate related fixed asset for invoicing purpose.
Also populate relevant division from fixed asset card

**Comment by prabhupdesh** [comment]
Division is mandatory for all fixed asset creation
Support division selection is not allowed while creating fixed asset
"Set of" is available to be selected for all fixed asset creation

**Comment by ramapandian14** [comment]
I have created a Purchase invoice for fixed asset
I have checked preview posting G/L entries are posting properly..

**Comment by YashwanthGowdaJ** [comment]
Ram, I have made division as mandatory while taking Label printout.

Watever the situation, division should be selected mandatorily.

So, division will get updated as below,
1. If user selects style number by lookup, then division will flow accordingly based on FG of selected style No. and also BUCL dimension will get updated.
2. If user has manually entered style no. then they have manually select division also. When they select division, then dimension will get updated.
3. Support selection in division is not allowed.

@ramapandian14  and @IT-Saravanan  I have taken all the cases and I am controlling in the system that division should be mandatory. So please check from your end and confirm. 

Development done in test server.

**Comment by YashwanthGowdaJ** [comment]
While selecting Fixed Asset(As Item) in job work order, default dimensions are not flowing properly.

This is because, in job work order, if we select Item, then dimensions will flow from default dimensions(From Item card).
But while creating FA as Item, we are not storing default dimensions. 

Need to work on this.

**Comment by YashwanthGowdaJ** [comment]
@ramapandian14  or @IT-Saravanan  please include this FA(Already created as Item) CD-MD-MD-21-16-2 to create job work order and please check whether division dimension is flowing till purchase invoice.

**Comment by ramapandian14** [comment]
Noted Yashwanth.We Will check..

**Comment by YashwanthGowdaJ** [comment]
While selecting FA as item in Job work orders, FA entity and Job work order entity should be same. - As discussed with @prabhupdesh 

I am not allowing to select FA as Item if entity mismatch b/w FA(created as Item) and job work order.

@IT-Saravanan and @ramapandian14  please check from starting to end once(with dimension flow) and update. If everything is fine, will move to live.

**Comment by IT-Saravanan** [comment]
Test Case 1 Details:
Fixed asset Created FA No. EW-PT-UR-21-3-1,
Job work order created JWO No : 14106210034,
Sub contract order No : 140U06210013,
Purchase Invoice No : 105U06210010,
Division is flowing till Purchase Invoice.

**Comment by IT-Saravanan** [comment]
Test case 2 Details
Fixed asset Created FA No. TD-TD-ED-20-128-4,
Job work order created JWO No : 44106210009,
Sub contract order No : 440U06210004,
Purchase Invoice No : 406U06210001,
Division is flowing till Purchase Invoice.
But FA Posting Type not updating & if it is Fixed asset Gen. Prod Posting group is FA but in purchase invoice its updating SC so need to check.

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan For FA as Item in purchase invoice line, I am doing following changes as per your suggestion.
1. FA posting type is acquisition cost
2. Gen. Prod Posting group is FA
Please check

**Comment by IT-Saravanan** [comment]
I have checked the functionality working fine so move this to live.

**Comment by YashwanthGowdaJ** [comment]
Moved to live.

**Comment by prabhupdesh** [comment]
Please rectify/roll back this development immediately.....
System converting GL also to fixed assets.

**Comment by YashwanthGowdaJ** [comment]
Allowed support dimension selection for all the fixed assets
