### ISSUE TITLE
Job Card Creation For Local Sale

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#113]
Job Card Has been created for Local Sale
----------------------------------------------
If Job Card customer Season is Local Sale we need to bypass the condition " Items no need not Part of BOM".
Production team will issue the material against job card without adding the items in BOM.
Request has given by kanchana

**Comment by YashwanthGowdaJ** [comment]
I am bypassing the "Items should be the part of the BOM" condition for local sales. 

@ramapandian14  please check and confirm. Development done in test server.

**Comment by ramapandian14** [comment]
Noted Yashwanth. I will Check

**Comment by ramapandian14** [comment]
I have checked its Working Fine.(Job Card.No :-44205210266) for reference..
@YashwanthGowdaJ  Moved to Live..

**Comment by YashwanthGowdaJ** [comment]
Changes are done in table 83 Item Journal Line. Moved to live.

**Comment by YashwanthGowdaJ** [comment]
Ram, if working in live, please close this task.

**Comment by YashwanthGowdaJ** [comment]
@ramapandian14  or @IT-Saravanan  please use this FA(already created as Item) CD-MD-MD-21-16-2 to create job work order and please check whether division is flowing till purchase Invoice.

**Comment by ramapandian14** [comment]
Sure.
