### ISSUE TITLE
Mismatch of Export Invoice and Packing List

### ISSUE THREAD

**Issue by dhivyabarathi** [BPS-Industries/Navision#116]
PA-ORD-B-0012/19-20  PA-ORD-B-0014/19-20  PA-ORD-B-0015/19-20
1.There was mismatch of layout.
2.In Invoice the scheme and description is mismatch.
3.There some minor mismatch.

**Comment by dhivyabarathi** [comment]
1. Invoice discount percentage .
2. Invoices with grouped lines. Will work on them individually or case by case like PA-ORD-B-0015/19-20.
3. Invoices showing DBK SR code for each line.
4. Invoices with Custom reference field (below other references).

**Comment by NiteshTLW** [comment]
PA-ORD-B-0012/19-20 PA-ORD-B-0014/19-20 are matching with original Export Invoice and Packing List
