### ISSUE TITLE
ESI Exemption for daily wage < 176/-

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#117]
Employees in receipt of a daily wage upto rs. 176/- (wef 01.09.19) are exempted from payment of contribution. Employers will however contribute their own share in respect of these employees.

**Comment by prabhupdesh** [comment]
![IMG_20210619_154241](https://user-images.githubusercontent.com/61455315/122639010-2b8b4d00-d115-11eb-9f54-d9ad4d0e8cb4.jpg)

**Comment by prabhupdesh** [comment]
ESI gross / working days (days in month - 4), if less than 176/- then employees contribution will be 0. Change to be done while payroll calculation.

**Comment by prabhupdesh** [comment]
@NiteshTLW / @IT-Saravanan to take care of this

**Comment by NiteshTLW** [comment]
WIP

**Comment by prabhupdesh** [comment]
@YashwanthGowdaJ

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan I am not calculating ESI for those, whose daily wages is less than 176/-

Calculation for Daily Wages: Employee Gross Salary/Total days in the month.

Development is done in test server. Please test the development.

**Comment by prabhupdesh** [comment]
@YashwanthGowdaJ as dicussed, please create a setup field in ESI setup. Field name will be: ESI Daily wage limit
Also note, system should only place control on employee esi amount calculation, employee esi amount should get calculated as usual

**Comment by YashwanthGowdaJ** [comment]
@prabhupdesh I have moved this development to live with separate function called as "ESI calculationforDailyWages" but I am not calling that function.
