### ISSUE TITLE
Attempted to divide by zero

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#118]
![image](https://user-images.githubusercontent.com/61455315/122641759-dc4d1880-d124-11eb-81e1-ee99593793ee.png)

**Comment by ramapandian14** [comment]
Right Now we have placed the condition in Item Tracking Lines
In Req.Worksheet Template ->Type of Indent is PD
User creating a requisition in MRP(Those users type of Indent is PD we are updating PO Type as PD in Purchase Order.
If Other than PD those users are creating a PO it will update as Bulk.
So System will throw the error as ''Attempt to divide by zero''.

We need to place another condition based on Location Code is 44-PD.
Then PO type updated as PD
So system will not ask item tracking lines.

**Comment by prabhupdesh** [comment]
What is the reason behind this error?

**Comment by ramapandian14** [comment]
Item Tracking Lines are not generating for these PO

We have handled these scenario
--------------------------------------
In Req.Worksheet Template ->Type of Indent is PD
User creating a requisition in MRP(Those users type of Indent is PD we are updating PO Type as PD in Purchase Order.
If Other than PD those users are creating a PO it will update as Bulk.

We need to place another condition based on Location Code is 44-PD.
Then PO type will updated as PD.
System will not ask Item Tracking Lines

**Comment by YashwanthGowdaJ** [comment]
If requisition is raised for sample(PD) then PO type in Purchase orders will be PD, or else PO type will be Bulk. 

If PO type is PD, then no need to create item tracking lines while approving purchase order (As per @ramapandian14 )

Here request has been raised from Buy-to stock indent. So PO type will be Bulk in Purchase orders. So it is trying to create item tracking lines. While creating item tracking lines, it is executing @surajsrivastava1991  code, it is checking for the corresponding sales orders, while was not found. So it is throwing this error.

Attached is the snap of Suraj's code.

![image](https://user-images.githubusercontent.com/61491976/122719811-5815a500-d28c-11eb-945f-798435e43e87.png)

@ramapandian14 @IT-Saravanan @prabhupdesh  please suggest here.

**Comment by ramapandian14** [comment]
Completed.Closed the Task
