### ISSUE TITLE
Fixed Asset No. Mandatory

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#124]
1.Purchase Order
2.Job Work Order
3.Purchase Invoice(Using Get Receipt Lines Functionality)
4.Transfer Order

**Comment by YashwanthGowdaJ** [comment]
1. Purchase Order : Users cannot able to create new lines in purchase orders for fixed assets. If PO needs to be created, then they should use MRP. In MRP already this filter is applied(Only approved fixed assets can be used)
2. Jo work Order : I have placed a control. If FA is selected(as Item) in job work order, it should be in released state
3. Purchase invoice : They have to create PI with receipts(Get receipt line). We have already taken care in PO and job work order. Same will be flown to PI also.
4. Transfer Order : I have applied a condition that only approved fixed assets can be used.

Changes are done in test server in table level. Please check and confirm @ramapandian14

**Comment by IT-Saravanan** [comment]
we have restricted Fixed asset only released should allow PI, PO, JWO & TO. i have checked this functionality, Its working fine so move this functionality to live.

**Comment by YashwanthGowdaJ** [comment]
Moved to Live. Close the task

**Comment by IT-Saravanan** [comment]
Functionality working fine in live.
