### ISSUE TITLE
Item PM-OT Child Card Creation Additional Option

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#126]
PPC team need additionally (Width Option) while creating child cards for PM-OT items. 

They need for this type selection option in PM-OT Child Card Creation
![image](https://user-images.githubusercontent.com/61489309/122901616-5242c100-d36b-11eb-90e8-969fa5d49737.png)

![image](https://user-images.githubusercontent.com/61489309/122900751-95506480-d36a-11eb-8027-706d1ddd3036.png)

**Comment by YashwanthGowdaJ** [comment]
WIP

**Comment by YashwanthGowdaJ** [comment]
In PM-OT, there are many groups, 

We need to change the vattributes structure for CW(Cling Wrap).

Earlier we have only width option. Now they need both length and width(As per the mail attached above)
UOM should be changed from cm to mm and same should flown to the item card.

**Comment by YashwanthGowdaJ** [comment]
Changes are done in vattributes page and also in item variants table(To move length to variant name). Moved to live.

@IT-Saravanan , check and close the task.

**Comment by IT-Saravanan** [comment]
As per the requirement we have given the changes in vattributes page working fine.

![image](https://user-images.githubusercontent.com/61489309/123035811-a13f3380-d409-11eb-9926-751c7fdd450f.png)
