### ISSUE TITLE
Notes to be copied from warehouse Master to FGP 

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#127]
![image](https://user-images.githubusercontent.com/61489309/122918193-7b1f8200-d37c-11eb-9242-bdeaeab2d7d4.png)

**Comment by YashwanthGowdaJ** [comment]
WIP

**Comment by IT-Saravanan** [comment]
warehouse master Notes is flowing to warehouse BOM in Fgp creation.
