### ISSUE TITLE
Multiple OK confirmation while sending for approval in journals

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#128]
Issue from kamalakannan accounts:

For ex:  On sending a journal entry with 10 lines then confirmation message to send for approval shows up 10 times. Need to rectify and show the confirmation message only once.

**Comment by YashwanthGowdaJ** [comment]
Now pop up message will come only once for the set of selected records in journals.

Taken care in both sending and canceling the request.

please check and confirm

**Comment by IT-Saravanan** [comment]
This functionality working fine in payment journal. For this same we need to do in all journal entries and customer season transfer., Physical inventory journal. Before we will discuss with prabh sir

**Comment by YashwanthGowdaJ** [comment]
I have made changes in all the journal entries.

**Comment by IT-Saravanan** [comment]
This functionality working fine in customer season transfer. move this to live

**Comment by IT-Saravanan** [comment]
Multiple ok confirmation we have fixed now, it will pop up one time. at the time of send for an approval.
