### ISSUE TITLE
Payment Journal -Bank Charges

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#129]
Users are creating two lines in Payment Journal.
First Lines -Account Type - Vendor/Bal.Account Type -Bank.No and linking PO in Payment Journal.
Second Lines-Bank Charges.

Correct Solution will be.
------------------------------
No Need of Creating second Line.User Can Select a bank charges in same line.
I have Created a entry in test and i have click ->Preview posting entries are flowing properly..
Reference.No:-B/VOU18026(Payment Journal-BPS-Ram Batch)

**Comment by prabhupdesh** [comment]
This has been addressed. Basis posted document no. of advance payment division can be evaluated
