### ISSUE TITLE
Sales Debit Note

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#130]

**Comment by ramapandian14** [comment]
Sales Debit Note is the reverse of a sales invoice.
A debit note is very similar to an invoice. The main difference is that invoices always show a sale, where debit notes and debit receipts reflect adjustments or returns on transactions that have already taken place.

**Comment by ramapandian14** [comment]
![IMG-20210617-WA0002](https://user-images.githubusercontent.com/61492205/123501425-7d2a5f00-d662-11eb-96af-5d4dfa4be72b.jpg)

**Comment by ramapandian14** [comment]
![IMG-20210617-WA0001](https://user-images.githubusercontent.com/61492205/123501493-fb870100-d662-11eb-8ddf-69dbf91034c8.jpg)

**Comment by YashwanthGowdaJ** [comment]
@ramapandian14 I have designed a report based on above image.

Report ID : 33010267
Please check and confirm

**Comment by ramapandian14** [comment]
I will check and update the status on today

**Comment by ramapandian14** [comment]
I have checked the report
Please check from your end also@Yashwanth
I am attaching the report for your reference..

![image](https://user-images.githubusercontent.com/61492205/124224464-5026f200-db23-11eb-8ac7-3119b8097329.png)
![image](https://user-images.githubusercontent.com/61492205/124224500-603ed180-db23-11eb-9247-1b07a0ecb899.png)
