### ISSUE TITLE
Purchase invoice - Check mandatory dimensions while sending for approval

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#131]
Need to place a control in purchase invoice to check mandatory dimensions at the time of sending for approval.

**Comment by YashwanthGowdaJ** [comment]
I am checking the mandatory dimensions in purchase invoice while sending for an approval.

Changes are done in test server. I have checked and found working.
Test Case : Purchase Invoice No : 105U06210007(contains GL account 217100)

Moved to live.

**Comment by prabhupdesh** [comment]
@IT-Saravanan please check

**Comment by IT-Saravanan** [comment]
Test case in test Server
Purchase invoice No 106U06210004
G/L A/c No: 217600, 217100, 203730, 203720

**Comment by prabhupdesh** [comment]
Moved to live
