### ISSUE TITLE
Employee Salary (Pay Elements Revision & Arrear Processing) 

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#132]
To update employee Revision pay elements. 
Go to Revision Header List. => Actions => continue the following steps
Step 1 Upload xml (Need to upload CSV File contains Emp No & Revision Amount)
Step 2 Get pay elements after clicking this (Auto fill Revision line subform)
Step 3 Pay revision update 
Step 4 Post to Emp_pay Elements after pressing this (it will update the details in employee card pay elements)

Need to add functionality : Arrear Processing & Arrear OT calculation

**Comment by YashwanthGowdaJ** [comment]
Arrear Processing and Arrear OT calculation functionalities are added in list page

**Comment by IT-Saravanan** [comment]
Added funtionality Arrear process and Arrear OT calculation in test server, working fine in test value is populated in Arear head and the value is flowing till Misc- Add/Deduction Page. 
Updated Revision Pay element also flowing till employee pay elements.
Multiple selection lines is working in arrear process and arrear ot calculation but after clicking Arear ot calculation button multiple time asking ok confirmation. please fix it then move this funtionality to live

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan I have moved this to live

**Comment by IT-Saravanan** [comment]
jeyakumar has confirmed the values are flowing properly. He was uploaded the tritan employees.
