### ISSUE TITLE
TDS on purchase of RM Section 194Q

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#133]
New TDS section 194Q that will come in to effect from 1st July 2021. This section will be applicable on:

Purchase of goods.
Tax payers whose annual turnover is greater than 10 crores in the immediate preceding financial year.
Tax is required to be deducted by such person if the purchase of goods by him from the seller is of the value or aggregate of such value exceeding fifty lakh rupees.
 

The tax rate applicable is 0.1% on purchases exceeding 50 Lakh rupees.

**Comment by prabhupdesh** [comment]
Dear @ramapandian14,

Please plan what needs to be done to incorporate this in navision. We will meet at 3 PM today to discuss further on what you have planned.

**Comment by ramapandian14** [comment]
(Not applicable for Import Purchase from a supplier outside India) for purchase of goods (NA to services)
Where PAN has been provided | 0.1%
Where PAN has not been provided | 5%

**Comment by YashwanthGowdaJ** [comment]
Changes are done in below tables. Added option values for the fields TDS Goup and TDS Section.

1. 13726(TDS Nature of Deduction)
2. 13728(TDS Setup)
3. 13729(TDS Entry)
4. 13731(TDS Group)

In test server

**Comment by ramapandian14** [comment]
**Steps to create a Process for TDS**

Set up TDS Groups
·        Set up TDS Nature of Deductions
·        Set up Assessee Codes
·        Set up Concessional Codes
·        Set up TDS Setup
         Set up NOD/NOC List

**Comment by ramapandian14** [comment]
I have created a Purchase Invoice and posted with Document.No:-10507210001
Entries are flowing correct..
System is creating a TDS Entries and storing a data in TDS Table..
![image](https://user-images.githubusercontent.com/61492205/123758074-35167100-d8dc-11eb-94a5-e192cdb9d4c7.png)

**Comment by ramapandian14** [comment]
![image](https://user-images.githubusercontent.com/61492205/123758219-570ff380-d8dc-11eb-94e5-4043ece58a32.png)

**Comment by ramapandian14** [comment]
I am Checking for more scenarios also..

**Comment by YashwanthGowdaJ** [comment]
Done the table changes in live

13726(TDS Nature of Deduction)
13728(TDS Setup)
13729(TDS Entry)
13731(TDS Group)

**Comment by prabhupdesh** [comment]
Controls:
1. TCS applicable on all invoices before 01.07.21, as per present working
2. TDS applicable only for invoices post 01.07.21, but threshold should be taken care from 01.04.21

**Comment by ramapandian14** [comment]
1.NOD/NOC list for Purchase of Goods applicable to vendors should be created through batch job.
2.Scenarios.
Vendor has crossed a Threshold value of 4900000 Lakhs
I have received a invoice from supplier with value of 500000 Lakhs
Total Purchase of Vendor will be 5400000 Lakhs(
TDS Should be calculated from after crossing Threshold Value .(5400000-5000000)=400000 Lakhs
1% of 400000 Lakhs will be 400(TDS Value)

**Comment by YashwanthGowdaJ** [comment]
@ramapandian14 , I have placed a control in purchase invoice, if posting date is greater or equal to 01/07/21 then TCS structure is not allowed to select. Please check in test server to move to live


@YashwanthGowdaJ 

**IF I am Selecting these Structure :-GSTEX+TC.1 its allowing me to select in purchase header.
But it should not allow to select the structure**
**Reference Document.No :-105U05210116**

**Comment by YashwanthGowdaJ** [comment]
**For selecting TDS nature of deduction as Goods**

As our invoices have multiple lines, user cannot able to select for individual lines. So we have already given a Summary Page based on item numbers.

So I have given TDS nature of deduction field in summary page, on selecting it will flow to all the invoice lines with that item No.

@ramapandian14 please check...

**Comment by prabhupdesh** [comment]
Partial TDS calculation required? @ramapandian14 status please

**Comment by ramapandian14** [comment]
Partial TDS Calculation required should be yes sir..

**Comment by prabhupdesh** [comment]
I am asking the status whether development completed?

**Comment by ramapandian14** [comment]
Development Not completed Sir

**Comment by YashwanthGowdaJ** [comment]
Ram, please create a testing scenario to check the development in test server

**Comment by ramapandian14** [comment]
Ok.I will create a testing scenario

**Comment by ramapandian14** [comment]
Moved to Live
