### ISSUE TITLE
Need xml port to update Duty Roster

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#134]
Every month we are updating employee working division daywise, we are getting this data from duty roster google sheet. 

We are downloading the data everymonth and updating the duty roster table, then we are running the code unit to update the employee daywise division in daily attendance. 

Duty Roster Table ID : 33010336
Code unit No : 50069

**Comment by YashwanthGowdaJ** [comment]
WIP

**Comment by IT-Saravanan** [comment]
[99-Duty Roster.xlsx](https://github.com/BPS-Industries/Navision/files/6746162/99-Duty.Roster.xlsx)
PFA. They are updating this format Duty roaster everymonth.

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan  I have developed an xmlport to upload duty roster.

I have added into frontend "Upload duty roster" in test server. 
[duty Roster.xlsx](https://github.com/BPS-Industries/Navision/files/6763769/duty.Roster.xlsx)


Please check

**Comment by YashwanthGowdaJ** [comment]
As per @IT-Saravanan Duty roster xmlport is working fine. Moved to live

**Comment by IT-Saravanan** [comment]
Xmlport values are flowing properly in duty roster table. 
pending for code Running part

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan those 2 functions are now running along with xmlport.

Please check. Development done in test server

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ please check code unit part not running

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ this functionality is working fine. move this to live

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan. Moved to live.

**Comment by IT-Saravanan** [comment]
This functionality is working fine in live. how to do the process shown to jayakumar he is confirmed working fine the division updating properly. 

Task completed
