### ISSUE TITLE
Block Parent FA cards

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#135]
1. Block all existing Parent FA cards
2. While creating any new fixed asset parent card, the new card should be blocked.

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ block the FA parent card after released and allow to create child card for that parent card

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan I have blocked all the papa Fixed Asset cards. And also I am blocking the FA by default while creating.

Sending for an approval, creating child cards are happening even if FA papa is blocked.

Please check

**Comment by IT-Saravanan** [comment]
Yes @YashwanthGowdaJ its hapening.

Please check while creating child card papa card status is pending approval and the child card also created pending approval, after approved the papa card child card status not changing.

If it is child card FA dont show the create child card button.

**Comment by YashwanthGowdaJ** [comment]
As per @IT-Saravanan , if parent FA is not released, then do not allow to create child cards for that parent. I have incorporated this in test server

**Comment by YashwanthGowdaJ** [comment]
Create Child Card button is visible only in Parent FA

**Comment by YashwanthGowdaJ** [comment]
Blocked all FA parent cards in live

**Comment by YashwanthGowdaJ** [comment]
Moved to live
