### ISSUE TITLE
Entity Fixed Asset

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#136]
Entity is choosen in the fixed asset card as default dimension.
System should not allow any transaction with different entity from the one choosen in default dimension in FA card

**Comment by YashwanthGowdaJ** [comment]
As discussed with @IT-Saravanan 

1. If Fixed Asset selected in MRP-Buy to stock indent, then flow Entity selected in FA to MRP lines, do not allow them to change entity in lines.
2. In indent n sourcing page, Change Entity button should not work for fixed assets.
3. Purchase invoice, while selecting FA, do not allow if entity is different.
4. Need to take care in transfer Orders too.
5. In job work order, we have already placed this entity mismatch error.

Working on this.

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan I have taken care all the above points in test server.

Please check and confirm.

**Comment by IT-Saravanan** [comment]
1.Buy to stock  fixed asset entity is flowing need to restrict if fixed asset entity, location code non editable
2.Purchase invoice working fine
3.Job work order working fine

**Comment by IT-Saravanan** [comment]
Buy to stock now entity is non editable 
Transfer order now fixed asset they select worng entity FA system showing error

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan based on your confirmation, I have moved this development to live
