### ISSUE TITLE
Division dimension Mismatch

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#137]
![image](https://user-images.githubusercontent.com/61455315/123777457-d9ed7a00-d8ed-11eb-863a-56111c8716a7.png)

**Comment by prabhupdesh** [comment]
Refer above screen shot:

Customer season is Belt season but division dimension in line cannot be wallet.
Repeatedly it was discussed to use dimension combination to avoid these types of mismatch. @ramapandian14

**Comment by prabhupdesh** [comment]
@IT-Saravanan @dhivyabarathi

**Comment by prabhupdesh** [comment]
This needs to be handled using dimension combination. System shows error if mismatched dimension is selected. This same error should be shown in MRP at the time of raising an indent

**Comment by YashwanthGowdaJ** [comment]
I have done changes in MRP-buy to stock indent while confirming the items. 

If dimension combination is blocked for that particular combination, then system will throw the error at the time of confirming itself.

Need to place the same control in Production indent and management indents

Changes are done in test server.

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan changes are done in all MRP pages. 

Please check and confirm

**Comment by prabhupdesh** [comment]
We will not use dimension combination as of now, but control in MRP should work according to setup done in Dimension value.
@ramapandian14 #149

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan I am controling the selection of customer season and division from the setup done in dimension values.

The combination of customer season and division is allowed only as per the dimension values.

Development done in test server. Please check and confirm.

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ that functionalty is working fine in buy to stock indent, while creating buy to stock indent if i select belt season and select division as wallet system showing error message. so move this functionality in live.

**Comment by YashwanthGowdaJ** [comment]
Moved to live

**Comment by YashwanthGowdaJ** [comment]
[MRP pages as on 090721.txt](https://github.com/BPS-Industries/Navision/files/6788688/MRP.pages.as.on.090721.txt)

This includes the pages
1. Management indent
2. Buy to stock indent
3. production indent lines
4. PD indent
