### ISSUE TITLE
Need Send Approval option for Parent card 

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#139]
In 21-TRT-ALL-ALL-AS Season only child card going to approval, need to include parent card also, because some product group they are populating parent card updating price in parent card.But parent card send approval is not happening in customer season card page.

**Comment by prabhupdesh** [comment]
need to discuss with saravanan

**Comment by prabhupdesh** [comment]
IN customer season items , page id 50042, sending for approval for parent item was not allowed, now allowing.

![image](https://user-images.githubusercontent.com/61455315/124923063-baee9680-e017-11eb-82f5-9a78313d11b7.png)
