### ISSUE TITLE
Total Consumption Report Problem

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#140]
While generating total consumption Report in production BOM page Visible items not flowing in that report.

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan please check in test server

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan  I have modified the report in test server. Will move to live tomorrow @7 to 8 am slot

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan done changes in live

**Comment by IT-Saravanan** [comment]
Quantity's flowing correctly, confirmed by Sreejothi (Costing Team)
