### ISSUE TITLE
Sales Order Linking to Payment received from customer(Block Order Restriction)

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#141]
Customer Payment Should be linked to sales order.
We need to place a control that block order cannot be selected in payment Journal(Purchase/Sales Order.No Field).

**Comment by YashwanthGowdaJ** [comment]
It is a table change. We can do at the end of the day...

**Comment by YashwanthGowdaJ** [comment]
Blocked selection on block orders in payment journal.

Changes are done in live
