### ISSUE TITLE
PO with Testing Requirement

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#142]
This is from rafik.
Need a report in attached format to be sent along with purchase order to vendors.

**Comment by prabhupdesh** [comment]
[TR.docx](https://github.com/BPS-Industries/Navision/files/6752509/TR.docx)

**Comment by IT-Saravanan** [comment]
[Test Requirement for CRG group -TR.WT.CR.docx](https://github.com/BPS-Industries/Navision/files/6898370/Test.Requirement.for.CRG.group.-TR.WT.CR.docx)
[Test Requirement for BRAND BANK group -Seed.Commanry.docx](https://github.com/BPS-Industries/Navision/files/6898371/Test.Requirement.for.BRAND.BANK.group.-Seed.Commanry.docx)

**Comment by dhivyabarathi** [comment]
Test.Requirement.for.Karl.Lagerfield.docx
Test.Requirement.for.SIBCO.-.Naturalizer.Anine.Bing.docx
Test.Requirement.for.Patricia.nash.and.Nash.-.Womens.and.Mens.docx

**Comment by dhivyabarathi** [comment]
In Test Requirement all the requirement is same for CRG,TBG, CAL, SE, KL and PND except Light Source value will be change.
