### ISSUE TITLE
Apply alert while purchase invoicing 

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#143]
While purchase invoicing, system should alert for applying against the payment if any outstanding is present against the vendor.

**Comment by prabhupdesh** [comment]
Alert at the time of sending approval.

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan I am alerting while sending an approval if any outstanding is present against the vendor in purchase invoice. Please check and confirm

In test server

**Comment by prabhupdesh** [comment]
Check the outstanding payment by entity as per updated in purchase invoice.

**Comment by YashwanthGowdaJ** [comment]
I am checking the outstanding amount by entity wise. Please check

**Comment by prabhupdesh** [comment]
Ram to check , if instead of alert , and error can be shown to apply purchase invoice before posting

**Comment by ramapandian14** [comment]
I have Checked its showing Only Document Type ->Invoice alone sir..
