### ISSUE TITLE
String Length Error in Fixed Asset List

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#145]
![image](https://user-images.githubusercontent.com/61492205/124352407-aa0be280-dc1d-11eb-8e16-addc97e73ba6.png)

**Comment by YashwanthGowdaJ** [comment]
The fixed asset picture has been stored in a lengthy path.(more than 100 characters). Text variable is  defined to store the file path has only 100 characters in page 805(online map parameter factbox).

I have extended the length of a variable. This resolves the issue.

@ramapandian14  please check..

**Comment by prabhupdesh** [comment]
Resolved
