### ISSUE TITLE
Approval mail for vendor approvals

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#146]
Mail should be sent, only while below:

when vendor is first approved.
If the vendor status changes from RD to PD to Bulk and,
Mail should contain status of approval - RD PD or Bulk
Mail should also show the sender and approver id

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan I have worked on below points

1. Sending a mail, when vendor is 1st approved or vendor status changed from RD to PD to Bulk.
2. Mail is containing RD, PD or Bulk
3. Sender and approver ID is added in the mail body.

Please check and confirm.

Development has been done in test server.

**Comment by YashwanthGowdaJ** [comment]
[Vendor Approval testcases.xlsx](https://github.com/BPS-Industries/Navision/files/6770079/Vendor.Approval.testcases.xlsx)

**Comment by IT-Saravanan** [comment]
i have checked the functionality for the vendor approval for first time mail is going and vendor status changes is there mail is going.

**Comment by YashwanthGowdaJ** [comment]
Moved to live...
