### ISSUE TITLE
Advance Payment Linking to Subcontracting Order

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#148]
Please Provide me the functionality for Selecting Subcontracting Order in Payment Journal..

![image](https://user-images.githubusercontent.com/61492205/124467017-e887d580-ddb4-11eb-9a71-a19b3c5056a3.png)

**Comment by ramapandian14** [comment]
Please Provide me the button to select in payment Journal page

1. Purchase Order
2. Job Work Order
3. Select Job Work Order
4. Select Purchase Invoice

**Comment by YashwanthGowdaJ** [comment]
@ramapandian14 I have given 4 buttons in payment journal
1. Select Sales/Block Order
2. Select Purchase Order
3. Select Sales Invoice
4. Select Job Work Order

And Purchase Order No. field has made non editable. Users need to select the records from the appropriate buttons.

Development has been done in test server. Please check and confirm.

**Comment by prabhupdesh** [comment]
![image](https://user-images.githubusercontent.com/61455315/124702544-1e8c9d00-df0e-11eb-9e21-ab38d10267c1.png)

**Comment by prabhupdesh** [comment]
![image](https://user-images.githubusercontent.com/61455315/125026740-d3f05980-e0a2-11eb-8127-9576dc514e11.png)
Need to take care of posted document no. as well

**Comment by prabhupdesh** [comment]
1. Create a table.
2. Fields:
3. Journal template Name
4. Journal Batch name
5. Line No.
6. Document No.
7. Posted Document No.
3. Document no. to Link



![image](https://user-images.githubusercontent.com/61455315/125059264-bf26bc80-e0c8-11eb-91b9-ca82d6c46cfc.png)

**Comment by NiteshTLW** [comment]
In testing phase.

**Comment by prabhupdesh** [comment]
Select Sales/Block Order: 
1. Select sales/block order works only if customer has been chosen in payment entry line. 
2. lookup to sales / block order should only open sales/block order pertaining to customers selected in payment journal
3. Show external document no. for the document no. selected
4. Selecting same document no. in multiple line should not be possible
5. Currency code, exch, rate, show Advance Amount (FCY), Advance Amount( LCY), Prepayment %

Select Purchase Order/Invoice
1. lookup to purchase order/invoice should show only those customers where advance receipt is pending
2. Currency code, exch, rate, show Advance Amount (FCY), Advance Amount( LCY), Prepayment %
Select Sales Invoice
Currency code, exch, rate, show Advance Amount (FCY), Advance Amount( LCY), Prepayment %

Select Job Work Order

**Comment by NiteshTLW** [comment]
Dear @IT-Saravanan, Kindly, share your comments on if functionality to link Sales/Block order documents with advance payment entries is working as per requirement.

**Comment by IT-Saravanan** [comment]
Sales order payment journal funtionality working fine i have posted, Document No :10207210001 posted document no also storing that journal link document table.

**Comment by NiteshTLW** [comment]
Dear @IT-Saravanan, Kindly, share your comments on if functionality to link Purchase order, Purchase Invoice and Job Work Order documents with advance payment entries is working as per requirement.

**Comment by IT-Saravanan** [comment]
Dear @NiteshTLW 
In payment journal if i select the Account type is vendor please show in document link drop down list purchase order, purchase invoice, posted purchase invoice and job work order. if it is customer show sales order/Block order & sales invoice .
![image](https://user-images.githubusercontent.com/61489309/126482160-a37b02fa-5ec7-4a42-8620-6942a32d7f75.png)

instead of showing purchase order no (1True) place a link of the document link page. if i click the link need to show drop downlist which document i have linked 
![image](https://user-images.githubusercontent.com/61489309/126482894-ab1a0606-e463-4aca-8bae-b606afb664ad.png)

**Comment by NiteshTLW** [comment]
Dear @IT-Saravanan 
It is showing accordingly, when you select the line.
![Screenshot (48)](https://user-images.githubusercontent.com/86042081/126483788-ba4c0409-2727-4760-8725-f2745f0279bf.png)
![Screenshot (47)](https://user-images.githubusercontent.com/86042081/126483876-ffab060e-0b8b-45e2-b7f4-0cdcc7a6588c.png)

**Comment by IT-Saravanan** [comment]
This functionality is working fine in test server move to live

**Comment by YashwanthGowdaJ** [comment]
Moved to live.

**Comment by nagalakshmi2022** [comment]
1. Document selection from button only.
2. Extra line getting created.
3. **Account no** & **External Document no** should get flow and make it non-editable.
4. Hide or Remove **Amount**, **Amount LCY**, **Currency code**, **Exchange rate**, **Prepayment %**.
5. Include or add up **Vendor No**, **Vendor Name** 
6. Give buttons for all options in **Document Type**

**Comment by Abigaiel** [comment]
Dear @nagalakshmi2022 please check the functionality to linked documents button in payment journal  as per requierment .

**Comment by Abigaiel** [comment]
Dear @nagalakshmi2022 Please check the functionality to linked documents button in payment journal as per requirement .

**Comment by Abigaiel** [comment]
Dear @nagalakshmi2022 and @IT-Saravanan , 
In Journal Voucher I have given button (**Link Document**). On clicking link Document button have provided five more buttons as per requirement 
1. Sales\Block order
2. G\L Entry
3. Posted Sales Invoice
4. Posted Purchase Invoice
5. Posted Purchase Credit Memo
Please check the functionality of the link document button in journal voucher and please provide the test cases.

**Comment by Abigaiel** [comment]
@IT-Saravanan 
 Sales Invoice & Purchase Invoice Link document Functionality Moved to live.
