### ISSUE TITLE
Commercial courier using select PO in Sales Invoice

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#152]
User will create a sales invoice, Select a customer in Sales Invoice..
Using Select PO functionality user will pick a commercial courier in sales invoice page.

For NON-EXISTING Item -System will pick the unit cost updated in Commercial courier and populate same price in sales invoice lines.

**Comment by ramapandian14** [comment]
Place a control for user can't able to select a Item.No :-NONEXISTING in commercial courier .
Apart from commercial courier user will select a Item.No :-NONEXISTING(sample Order).

**Comment by YashwanthGowdaJ** [comment]
@ramapandian14 
1. For invoicing the commercial courier, if any nonexisting items present, then unit price should flow from commercial courier.
2. From now on they cannot able to select nonexisting items in commercial couriers.

Please check and confirm

**Comment by ramapandian14** [comment]
Working Fine
