### ISSUE TITLE
Need BOM Button on Production indent Page

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#153]
In Production indent page need BOM button. if i click the button need to open BOM page. (Requested for Sobha & Nancy)

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan I have given bom button and item card button in production indent. Please check

In test server

**Comment by IT-Saravanan** [comment]
This funtionality working fine please move to live

**Comment by YashwanthGowdaJ** [comment]
Moved to live..
