### ISSUE TITLE
Vendor PO statistics

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#154]
![image](https://user-images.githubusercontent.com/61455315/125073415-89d69a80-e0d9-11eb-9fd8-341a244a5d1e.png)

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan  I have generated a above report manager's wise.

Seperate mail to Ghouse, Raja  and Rafik.

Now I have included erpsupport as the recepient.

Please test.

Development is done in test server

**Comment by prabhupdesh** [comment]
Move to live
