### ISSUE TITLE
Need Belt size Field in Production Order Line List Page

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#156]
![image](https://user-images.githubusercontent.com/61489309/125392878-8dfa0500-e3c4-11eb-8cad-1616d0351dcf.png)

Page No: 5406

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan how can I give belt size in production order list page?? 

Wat will the case if the production order contains multiple lines with different sizes??

**Comment by YashwanthGowdaJ** [comment]
Added the belt size column in live
