### ISSUE TITLE
Batch job to finish job work order

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#158]
Check if remaining quantity = 0
if zero then call change status function and mark as "finish".

**Comment by NiteshTLW** [comment]
In Testing.

**Comment by NiteshTLW** [comment]
Development complete as per requirement

**Comment by ramapandian14** [comment]
@NiteshTLW :-Batch Job will run by creation date or Posting Date.

**Comment by NiteshTLW** [comment]
Creation Date, as applied

**Comment by ramapandian14** [comment]
@Nitesh :-I have checked for this batch job 
Not Working
Reference.No for Job Work:-14106210030

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ run a baatch job complete this task, this is pending on long back
