### ISSUE TITLE
Create a item: item category code: fgd , product group code : wa

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#16]
![thumbnail_image](https://user-images.githubusercontent.com/61489309/75514814-66e4a280-5a1e-11ea-9eb9-5f8ead5f0158.png)
 
Create a Item

**Comment by IT-Saravanan** [comment]
ITEM NO - D-M-UPC-LE-19-70  Item Card Created

**Comment by prabhupdesh** [comment]
Item code renamed to D-M-UPC-LE-19-41

**Comment by prabhupdesh** [comment]
![image](https://user-images.githubusercontent.com/61455315/75515960-51bd4300-5a21-11ea-8242-47a51c04dc08.png)
