### ISSUE TITLE
Place a Control in purchase invoice

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#160]
1. Need control in purchase invoice if document sent is true dont allow to delete
2. GRN No selected in unposted purchase invoice dont allow to select another purchase invoice.

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan I have placed above mentioned controls in test server. Please check

**Comment by IT-Saravanan** [comment]
In test server working fine move this functionality to live.

**Comment by YashwanthGowdaJ** [comment]
Moved to live..
