### ISSUE TITLE
Invoice Discount Calculation in Sales Invoice

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#161]
If invoice discount amount is specified in sales invoice then it is already calculating invoice discount %, need viceversa for this i.e., if invoice discount % is specified it should auto calculate invoice discount amount

**Comment by ramapandian14** [comment]
I have Checked these functionality .
Working Fine..
Refeerence.No :-412U07210002
@surajsrivastava1991 Need to Move to Live
