### ISSUE TITLE
Item Cart

### ISSUE THREAD

**Issue by YashwanthGowdaJ** [BPS-Industries/Navision#162]
Uploading Customer Code and supplier name as per the google sheet shared by Rumi dated : 12/07/21

The values should be updated in item card, so that same values will flow to item cart.

**Comment by YashwanthGowdaJ** [comment]
@prabhupdesh I have uploaded the shared data in items. And same is flowing to item cart:

Supplier name is updating only if it was blank earlier.

**Comment by prabhupdesh** [comment]
Yashwanth to reply to rumi's mail and also to mention new fields in item card to enter these data
