### ISSUE TITLE
FOPTLL Items -782 with value as 29.8 Lakhs

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#164]
782 no. of  FOPTLL items value being approx. 30L, not colored with any customer season
Items either the stock is 0 or belongs to dead stock.

**Tasks to be do**

IF FOPTLL Items physical Stock is Zero - Pass Negative Adjustment entry in Navision.
IF FOPTLL Items inventory is available/ Veera have marked as dead/scrap/local sale - then moved to dead stock.
IF FOPTLL Items inventory is available and mark other than Dead Stock-Negative entry in FOPTLL/Positive entry to Navision ID.

**Comment by ramapandian14** [comment]
Run a Stock report against item (Report ID :50083)
@NiteshTLW -Provide me the same report to upload the data through (XML) in item  journal page.
Item Journal(Table-83,Page-40)

**Comment by NiteshTLW** [comment]
XML Port and related button provided (Page - 40), Item Journal Negative Adjustment
WIP

**Comment by NiteshTLW** [comment]
Moved to Live

**Comment by ramapandian14** [comment]
Out of 782 Items i have completed 450 Items and value has been reduced from 29.8 to 3 Lakhs.

**Comment by ramapandian14** [comment]
FOPTLL0089|FOPTLL0660|FOPTLL0681|FOPTLL0685|FOPTLL0733|FOPTLL0809|FOPTLL0853|FOPTLL0859|FOPTLL0998|FOPTLL1016|FOPTLL10197|FOPTLL10209|FOPTLL10228|FOPTLL10230|FOPTLL10236|FOPTLL1026|FOPTLL10298|FOPTLL10301|FOPTLL10302|FOPTLL10306|FOPTLL10428|FOPTLL1043|FOPTLL10500|FOPTLL10505|FOPTLL10511|FOPTLL10512|FOPTLL10556|FOPTLL1058|FOPTLL10583|FOPTLL1071|FOPTLL1080|FOPTLL1081|FOPTLL10875|FOPTLL10883|FOPTLL10916|FOPTLL10969|FOPTLL10970|FOPTLL11085|FOPTLL11096|FOPTLL11098|FOPTLL11101|FOPTLL11113|FOPTLL11165|FOPTLL11166|FOPTLL11175|FOPTLL11177|FOPTLL11241|FOPTLL11250|FOPTLL11251|FOPTLL11253|FOPTLL11266|FOPTLL11283|FOPTLL11306|FOPTLL11307|FOPTLL11311|FOPTLL11313|FOPTLL11321|FOPTLL11349|FOPTLL11352|FOPTLL11623|FOPTLL11699|FOPTLL11771|FOPTLL11773|FOPTLL11885|FOPTLL11900|FOPTLL12045|FOPTLL12049|FOPTLL12057|FOPTLL12072|FOPTLL12084|FOPTLL12090|FOPTLL12127|FOPTLL12131|FOPTLL12132|FOPTLL12162|FOPTLL12163|FOPTLL12164|FOPTLL12165|FOPTLL12166|FOPTLL12167|FOPTLL12168|FOPTLL12206|FOPTLL12235|FOPTLL1237|FOPTLL1301|FOPTLL1327|FOPTLL1337|FOPTLL1338|FOPTLL1341|FOPTLL1343|FOPTLL1355|FOPTLL1372|FOPTLL1497|FOPTLL1515|FOPTLL1524|FOPTLL1664|FOPTLL1720|FOPTLL1771|FOPTLL1829|FOPTLL1881|FOPTLL1927|FOPTLL2035|FOPTLL2065|FOPTLL2328|FOPTLL2341|FOPTLL2346|FOPTLL2362|FOPTLL2424|FOPTLL2535|FOPTLL2773|FOPTLL2788|FOPTLL2940|FOPTLL2942|FOPTLL2947|FOPTLL2954|FOPTLL2975|FOPTLL2978|FOPTLL3003|FOPTLL3050|FOPTLL3060|FOPTLL3140|FOPTLL3163|FOPTLL3201|FOPTLL3202|FOPTLL3206|FOPTLL3208|FOPTLL3209|FOPTLL3235|FOPTLL3239|FOPTLL3577|FOPTLL3578|FOPTLL3592|FOPTLL3717|FOPTLL3894|FOPTLL3895|FOPTLL3896|FOPTLL3912|FOPTLL3915|FOPTLL3917|FOPTLL3925|FOPTLL3931|FOPTLL3938|FOPTLL3942|FOPTLL3944|FOPTLL3946|FOPTLL3950|FOPTLL3953|FOPTLL3959|FOPTLL3963|FOPTLL3967|FOPTLL3973|FOPTLL4006|FOPTLL4007|FOPTLL4031|FOPTLL4062|FOPTLL4068|FOPTLL4142|FOPTLL4148|FOPTLL4165|FOPTLL4166|FOPTLL4534|FOPTLL4648|FOPTLL4689|FOPTLL4697|FOPTLL4705|FOPTLL4712|FOPTLL4716|FOPTLL4723|FOPTLL4724|FOPTLL4794|FOPTLL4853|FOPTLL4887|FOPTLL4894|FOPTLL4945|FOPTLL4983|FOPTLL5086|FOPTLL5108|FOPTLL5115|FOPTLL5382|FOPTLL5455|FOPTLL5633|FOPTLL5635|FOPTLL5641|FOPTLL5642|FOPTLL5644|FOPTLL5645|FOPTLL5659|FOPTLL5706|FOPTLL5711|FOPTLL5727|FOPTLL5737|FOPTLL5747|FOPTLL5748|FOPTLL5756|FOPTLL5773|FOPTLL5774|FOPTLL5878|FOPTLL5919|FOPTLL5965|FOPTLL6013|FOPTLL6115|FOPTLL6116|FOPTLL6201|FOPTLL6209|FOPTLL6252|FOPTLL6297|FOPTLL6326|FOPTLL6331|FOPTLL6368|FOPTLL6400|FOPTLL6501|FOPTLL6776|FOPTLL6810|FOPTLL6821|FOPTLL6980|FOPTLL7423|FOPTLL7436|FOPTLL7750|FOPTLL7763|FOPTLL7772|FOPTLL7774|FOPTLL7880|FOPTLL7888|FOPTLL8127|FOPTLL8166|FOPTLL8200|FOPTLL8201|FOPTLL8313|FOPTLL8396|FOPTLL8532|FOPTLL8614|FOPTLL8615|FOPTLL8630|FOPTLL8746|FOPTLL8782|FOPTLL8811|FOPTLL8854|FOPTLL8864|FOPTLL8889|FOPTLL8933|FOPTLL8958|FOPTLL8983|FOPTLL9067|FOPTLL9069|FOPTLL9100|FOPTLL9101|FOPTLL9141|FOPTLL9150|FOPTLL9158|FOPTLL9175|FOPTLL9212|FOPTLL9233|FOPTLL9372|FOPTLL9450|FOPTLL9626|FOPTLL9725|FOPTLL9732|FOPTLL9776|FOPTLL9777|FOPTLL9797|FOPTLL9823|FOPTLL9930|FOPTLLN15033|FOPTLLN15034|FOPTLLN15064|FOPTLLN15065|FOPTLLN15067|FOPTLLN15092|FOPTLLN15100|FOPTLLN15102|FOPTLLN15112|FOPTLLN15185|FOPTLLN15251|FOPTLLN15265|FOPTLLN15277|FOPTLLN15318|FOPTLLN15366|FOPTLLN15371|FOPTLLN15385|FOPTLLN15435|FOPTLLN15439|FOPTLLN15465|FOPTLLN15468|FOPTLLN15483|FOPTLLN15499|FOPTLLN15511|FOPTLLN15512|FOPTLLN15516|FOPTLLN15517|FOPTLLN15520|FOPTLLN15728|FOPTLLN15963|FOPTLLN15981|FOPTLLN15986|FOPTLLN16013|FOPTLLN16295|FOPTLLN16308|FOPTLLN16309|FOPTLLN16310|FOPTLLN16311|FOPTLLN16316|FOPTLLN16320|FOPTLLN16322|FOPTLLN16326|FOPTLLN16327|FOPTLLN16364|FOPTLLN16509|FOPTLLN16518|FOPTLLN16592|FOPTLLN16697|FOPTLLN16838|FOPTLLN16895|FOPTLLN16901|FOPTLLN16986|FOPTLLN17084|FOPTLLN17086|FOPTLLN17132|FOPTLLN17169|FOPTLLN17201|FOPTLLN17297|FOPTLLN17325|FOPTLLN17400|FOPTLLN17403|FOPTLLN17575|FOPTLLN17682|FOPTLLN17688|FOPTLLN17704|FOPTLLN17717|FOPTLLN17749|FOPTLLN17794|FOPTLLN17796|FOPTLLN17806|FOPTLLN17857|FOPTLLN17869|FOPTLLN17870|FOPTLLN17871|FOPTLLN17937|FOPTLLN17953|FOPTLLN17954|FOPTLLN17995|FOPTLLN18053|FOPTLLN18092|FOPTLLN18151|FOPTLLN18155|FOPTLLN18166|FOPTLLN18316|FOPTLLN18354|FOPTLLN18355|FOPTLLN18356|FOPTLLN18382|FOPTLLN18385|FOPTLLN18386|FOPTLLN18396|FOPTLLN18410|FOPTLLN18412|FOPTLLN18413|FOPTLLN18414|FOPTLLN18416|FOPTLLN18417|FOPTLLN18418|FOPTLLN18419|FOPTLLN18420|FOPTLLN18584|FOPTLLN18792

@YashwanthGowdaJ  -**Hide the list of  items in Items Page,ILE,stock Register report, stock report from Item Page**

**Comment by ramapandian14** [comment]
Positive adjustment has been done for all respective navision Items.
