### ISSUE TITLE
Location Dimension Auto population

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#165]
Auto populate location dimension in 
purchase invoice,
MRP, 
purchase order, 
Purchase credit memo,
Sales Order,
Sales invoice,
Sales Credit memo,
Payment journal,
General journal,
Cash Receipt journal,
Cash payment journal,
Journal voucher

**Comment by NiteshTLW** [comment]
@IT-Saravanan  Please advise on MRP setup
