### ISSUE TITLE
Payslip Report

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#168]
Design payslip report from Navision
Payslip email should be automated every month to be sent to staffs email id.

**Comment by dhivyabarathi** [comment]
Completed in test server.

**Comment by IT-Saravanan** [comment]
Print company name as per employee payroll and KM Number also 
@YashwanthGowdaJ please complete this

**Comment by Abigaiel** [comment]
@IT-Saravanan 
Payslip Report has changed as per the requirement, thoroughly tested by you, and moved to live.
