### ISSUE TITLE
Unit 14 Van cost route wise

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#170]
#73 
Pay element as deduction to be updated with relevant amount as per attached excel
Process/Post salary should take care of deduction amount

**Comment by prabhupdesh** [comment]
[Lakshmi  Travels Van List (2).xlsx](https://github.com/BPS-Industries/Navision/files/6867658/Lakshmi.Travels.Van.List.2.xlsx)
[R R Travels Van List (2) (1).xlsx](https://github.com/BPS-Industries/Navision/files/6867660/R.R.Travels.Van.List.2.1.xlsx)

**Comment by prabhupdesh** [comment]
![image](https://user-images.githubusercontent.com/61455315/126760303-89f1369f-2a9c-4329-aca4-7e19c82588ca.png)

**Comment by IT-Saravanan** [comment]
Created Pay Element and i have marked Variable Element as true as per jeyakumar instruction
![image](https://user-images.githubusercontent.com/61489309/126763604-473c85da-dfe1-4f1e-ba3e-50c836009628.png)

**Comment by IT-Saravanan** [comment]
CSV Format For Travel Deduction 
![image](https://user-images.githubusercontent.com/61489309/126764214-10d1aff6-f85e-4e49-bf1b-24592e4e0233.png)

**Comment by IT-Saravanan** [comment]
@NiteshTLW,  Xml port working fine Please move the XML port (Travel Deduction) to live.

**Comment by IT-Saravanan** [comment]
In Live Datebase i have created the Pay element 
![image](https://user-images.githubusercontent.com/61489309/127435413-ca20a1f1-2fae-431b-b912-9bf9c18c1bca.png)

and linked to G/L Account No in  payroll general posting setup

![image](https://user-images.githubusercontent.com/61489309/127435550-a12db4ac-d636-43dc-aa66-f60b8a025f20.png)
and Added the pay slip
![image](https://user-images.githubusercontent.com/61489309/127435806-e4e399f0-b9f3-4159-92df-220d552a0ad9.png)

**Comment by IT-Saravanan** [comment]
This functionality is working fine move this to live

**Comment by IT-Saravanan** [comment]
Please add a field travel deduction for the listed below report
1.Monthly wages (33010128)
2.Salary details summary (33010144)
3.Employee gross details (33010308)

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan Travel Deduction field is added in above mentioned reports. Please check

**Comment by IT-Saravanan** [comment]
Task completed. These reports moved live value flowing properly.
