### ISSUE TITLE
Auto addition of item in customer season from PD indent

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#173]
In PD indent, once a item is selected and customer season is also filled, then while confirming a PD indent, system should auto add item to relevant customer season

**Comment by prabhupdesh** [comment]
This is from kanika

**Comment by prabhupdesh** [comment]
@dhivyabarathi @NiteshTLW  please take care of this. Take understanding from saravanan

**Comment by NiteshTLW** [comment]
The development is complete, as advised. Kindly update the test result.

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan. Please test this to move to live

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan confirm moving this to live.
