### ISSUE TITLE
Accounting Food plus card 

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#175]

**Comment by prabhupdesh** [comment]
As discussed:

1.  A field required in Employee card to hold food plus amount
2.  A field required in processed salary to hold calculated food plus amount
3.  While processing salary, system should calculate food plus amount as the way basic is getting calculated and store the value in food plus amount in processed salary table
4. Accounts should be able to populate this amount directly in payment journal
5. Effect should be shown in salary details summary report as well.

**Comment by prabhupdesh** [comment]
@NiteshTLW please complete this asap

**Comment by IT-Saravanan** [comment]
[
[Food plus card June 2021 - tritan.xlsx](https://github.com/BPS-Industries/Navision/files/6916555/Food.plus.card.June.2021.-.tritan.xlsx)
[Food plus card June 2021 - bps.xlsx](https://github.com/BPS-Industries/Navision/files/6916556/Food.plus.card.June.2021.-.bps.xlsx)
[Food plus card Total.xlsx](https://github.com/BPS-Industries/Navision/files/6916557/Food.plus.card.Total.xlsx)
](url)

**Comment by prabhupdesh** [comment]
Status please

**Comment by prabhupdesh** [comment]
@dhivyabarathi  to update in nav gyan
