### ISSUE TITLE
Transport Usage Employees need to Remove value in Pay element - Bps unit14

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#176]
In pay element Travel conveyance we need to make the value as zero as attached the mentioned below employees. 
![image](https://user-images.githubusercontent.com/61489309/127647213-7a2871f0-2e59-4461-9137-8cd407e2d3a0.png)
[Van ussage employees - bps unit14 Traval conveyance.xlsx](https://github.com/BPS-Industries/Navision/files/6907223/Van.ussage.employees.-.bps.unit14.Traval.conveyance.xlsx)

**Comment by IT-Saravanan** [comment]
Task completed done for live.

**Comment by prabhupdesh** [comment]
#170

**Comment by IT-Saravanan** [comment]
Task Completed confirmed with jayakumar values are flowing properly
