### ISSUE TITLE
Bin Code Bond 99

### ISSUE THREAD

**Issue by dhivyabarathi** [BPS-Industries/Navision#178]

**Comment by ramapandian14** [comment]
Purchase Order

**Warehouse receipt Creation**

**Actions - >Warehouse receipt in purchase order page**

IF Location ->99-MAIN
Entity      ->BPS
Bin will be BOND

**Get Source Document functionality** 

User will click warehouse receipt
Click ->Get Source Document functionality to select purchase order

**Bond Controls** :-Place the control on posting Warehouse receipt

**Comment by ramapandian14** [comment]
**Transfer Order**

If user have selected the bin code in warehouse shipment and posted the shipment against transfer order.
Make the Bin code as Non -Editable in whse receipt and hardcode the bin as Bond(it will flow from whse shipment).

**Comment by YashwanthGowdaJ** [comment]
Conditions are placed in Warehouse receipts while posting as per @IT-Saravanan in live server.

@IT-Saravanan please mention what all conditions we have placed in the system.
