### ISSUE TITLE
TDS Rounding

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#179]

**Comment by YashwanthGowdaJ** [comment]
TDS Rounding off Invoice Wise.

Earlier TDS used to round line wise. So this needs to be changed.

Changes are done in,
1. Rounding off in GL setup should be changed to 0.01
2. Code changes are in CU 90(Purch Post)

**Comment by prabhupdesh** [comment]
Please attach the relevant text object from live and close @YashwanthGowdaJ

**Comment by YashwanthGowdaJ** [comment]
Given 1 boolean field in TDS group (Allow Forex). On enabling this field, while calculating TDS, it will not check for any conditions(TDS will calculate always). 

If we encounters any such invoices(TDS should calculate for foreign currency) then one should enable this, post the invoice and disable.

Changes are done in Purchase Line table.
[Table Purchase Line 120821.txt](https://github.com/BPS-Industries/Navision/files/6972942/Table.Purchase.Line.120821.txt)

Moved to live
