### ISSUE TITLE
Splitting GST Assesable Value + Custom Duty fields in purchase header

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#180]
We need to create a field in purchase header

**GST Assessable value
Custom Duty Amount**

User will enter the GST Assessable value +Custom Duty in purchase Header

system will automatically split the lines based on Qty * unit cost of Items.

**Comment by prabhupdesh** [comment]
@dhivyabarathi please update status. 
Also update the working in nav gyan

**Comment by NiteshTLW** [comment]
It has been moved to live.

**Comment by YashwanthGowdaJ** [comment]
As discussed with kamalakanan, after splitting, we need to show the entered values in the same fields(Variables). 

So need to do reverse calculation on "On After Get Record" to populate the values.

**Comment by NiteshTLW** [comment]
@YashwanthGowdaJ  The values are now populating.

**Comment by YashwanthGowdaJ** [comment]
Moved to live. 

Tested by Divya
