### ISSUE TITLE
Cutting Dies

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#186]
Job Work Location is 99-MAIN and I have received a GRN against job work for 99-MAIN.
User will create a purchase invoice in 28-29 .
system will allow me to select a 99-MAIN/GRN in same purchase invoice.
This will applicable only for FA Block Code -CD(Cutting Dies).

**Comment by YashwanthGowdaJ** [comment]
@ramapandian14 I have made changes.

While doing get Receipt lines, if fixed asset of CD encounters, then I am inserting invoice line with header location, instead of receipt location. Development done in live server.

Please check..

**Comment by ramapandian14** [comment]
Working fine.
