### ISSUE TITLE
Spliting purchase Invoice line 

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#187]
Need functionality to Spliting purchase Invoice line based on selecting employees.
We are deduction Travel deduction from employees that amount need to flow while selecting the employee in purchase invoice.
G/L Account : 122502 Travel Deduction 
G/L account NO :217100 Bus hire charges

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan , in purchase invoice, "Select Employee" button will do the following.

1. Based on the entered line amount, and the basis of selected employees, Bus hire charges will calculate for each employee (average) and Travel deduction will calculate based in processed salary.
2.  Calculation for Bus hire charges for individual employee : Average bus hire charge - Travel Deduction for that particular employee
3. So on clicking the button, automatically, 1 invoice line will be splitted for Travel deduction and Bus hire charges.

Development done in live server. Please check

**Comment by IT-Saravanan** [comment]
Task completed Functionality working fine in live
