### ISSUE TITLE
Anaysis by dimensions Bus hire charges

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#188]

**Comment by YashwanthGowdaJ** [comment]
Need to bring bus hire charges, employee wise in salary details summary report.

Requirement from Subash.

For this, we need to create analysis by dimension employee wise with Bus hire charge G/L account.

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan , I have create analysis by dimension for G/l account **217100**(Bus hire charges) employee wise.

And using analysis view entry table, I am bringing the value in salary details summary report.

Development done in live server. Please check and confirm.
