### ISSUE TITLE
Warehouse Receipt multiple items one Inward Receipt

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#189]
In purchase order having multiple items Ex: 100 Items
 We need to create each item to create inward lines and attach while creating warehouse receipt so we need to simply this one inward receipt to link multiple items

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan I am attaching the gate entry for selected lines. Development done in test server. Please check

**Comment by IT-Saravanan** [comment]
Inward receipt attaching selected lines in  Warehouse Receipt its working fine in test server please move this to live

**Comment by YashwanthGowdaJ** [comment]
Moved to live

**Comment by IT-Saravanan** [comment]
Task completed. This fuctionality working fine in live.
