### ISSUE TITLE
Order Multiple and handling Surplus

### ISSUE THREAD

**Issue by YashwanthGowdaJ** [BPS-Industries/Navision#197]
@IT-Saravanan , explain here what and all we have discussed regarding this development.

**Comment by IT-Saravanan** [comment]
Need a functionality for order multiple.
Order Multiple 
what this functionality do means
while creating purchase order vendor supply only rounded qty.so we need to add qty those items rounding off in purchase order
in purchase order we need to create seperate line for order multiple qty, and requistion no as order multiple customer season as (free stock Season), after we need to allocate the qty for proper requisition lines.

Allocation Functionality
Need on functionality in purchase order & indent n sourcing to allocate 
what this button do is 
by clicking this button need to open requistion lines in purchase order page user need to select the lines for equal to freestock qty, after selecting the lines that lines will populate the purchase order and freestock lines qty need to reduce.

Adding lines to existing purchase order  for allocation should use existing functionality "add to purchase order ".
No where spliting is requires.

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan I have developed a functionality for order multiple and for allocating surplus quantity.

Order Multiple : Button was given in purchase order, on clicking that button, an extra order multiple line will be created for each item based on the order multiple value specified in the vendor item parameters.

Allocation of Surplus :This can be done done in 2 places
1. From Purchase Lines : User should go to respective order multiple lines, and a button is given in lines to allocate. On clicking, Req lines page will get open, user should select the multiple requisition lines(whose summation of quantity should be less than or equal to surplus quantity) then newlines will get created in the selected purchase order and simultaneously quantity from order multiple decreases.

2. From IndentnSourcing page : User will select multiple requisition lines and a button is given (Allocate),on clicking the button, purchase lines page will get open and user should select line(Quantity should be less or equal) and new purchase lines will get created and decreases the surplus quantity.

Like this the link will be generated from purchase line to MRP.

Please check the functionality in detail

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan Confirm moving this development to live.

**Comment by IT-Saravanan** [comment]
Customer season needs to be change Free stock. Location code

**Comment by YashwanthGowdaJ** [comment]
On the confirmation from @IT-Saravanan, moved this functionality to live.

**Comment by IT-Saravanan** [comment]
Task completed Fuctionality working fine in live.
[Order Multiple Functionality.docx](https://github.com/BPS-Industries/Navision/files/7134373/Order.Multiple.Functionality.docx)

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ Please block quantity field in purchase order.
