### ISSUE TITLE
Transfer note Add Description 2 Field

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#198]
In transfer order while sending material stores users taking warehouse shipment report, in that report only description 1 only available need to insert description 2 also.

Report ID : 5704

**Comment by dhivyabarathi** [comment]
Completed in Test Server. @IT-Saravanan  Please check.

**Comment by YashwanthGowdaJ** [comment]
On the confirmation from @IT-Saravanan moved this to live.

**Comment by IT-Saravanan** [comment]
Task completed working fine in live.
