### ISSUE TITLE
Split sales Order

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#2]

**Comment by prabhupdesh** [comment]
On re approving a block order, Block quantity should not get updated in Quantity if Quantity booked is more then zero. _**If Status is in Order Quantity Modification is restricted**_

**Comment by prabhupdesh** [comment]
Quantity field to be relabeled to Block Quantity _**Completed**_
If block order stage is order, Quantity cannot be changed _**Completed**_
Block quantity to be replaced by a variable field showing addition of Quantity booked + Remaining _quantity**Completed**_

**Comment by prabhupdesh** [comment]
While splitting a sales order, specifying "New buyer PO no." is mandatory.
In split SO dialog box:

1. Create a filed called "Split type" with option: Create New PO , Add in Existing PO
2. If create new PO is selected, then existing method with PO no. mandatory
3. If "Addin Existing PO", then lookup to sales header (block order = false, doc type = order, customer is relevant customer, entity, customer season) for external document no.
4. Sales order no. should  pick correct no. series while splitting
5. Split PO from : 11002200097 / old External document no.
6. Change external document no. label to "Buyer PO No." .Existing Sales Order : 13102200127 with Buyer PO No. : SPLITSO002 will be Updated!
7. After split, if quantity is 0, then delete sales line

**Comment by prabhupdesh** [comment]
> While splitting a sales order, specifying "New buyer PO no." is mandatory.
> In split SO dialog box:
> 
> 1. Create a filed called "Split type" with option: Create New PO , Add in Existing PO : **_Completed_**
> 2. If create new PO is selected, then existing method with PO no. mandatory **_Completed_**
> 3. If "Addin Existing PO", then lookup to sales header (block order = false, doc type = order, customer is relevant customer, entity, customer season) for external document no. **_Completed_**
> 4. Sales order no. should  pick correct no. series while splitting **_Completed_**
> 5. Split PO from : 11002200097 / old External document no. **_Completed_**
> 6. Change external document no. label to "Buyer PO No." .Existing Sales Order : 13102200127 with Buyer PO No. : SPLITSO002 will be Updated! **_Completed_**

**Comment by prabhupdesh** [comment]
BO: 800
Prod. order: 800
Create SO: 300
Prod Order: 800 should be linked to Block Order 500 qty. and sales order 300 qty.

**Comment by prabhupdesh** [comment]
Check issue while updating existing SO with split qty if no lines are in destination SO **_Completed_**

**Comment by prabhupdesh** [comment]
Qty. to convert while "Get block order lines" and also reservation should flow
Reservation should flow when creating sales order from block order (if block order is already having a production order)

**Comment by prabhupdesh** [comment]
Remove "Qty. to reduce" _**Completed**_

**Comment by prabhupdesh** [comment]
[Reservation Entry.docx](https://github.com/BPS-Industries/Navision/files/4265459/Reservation.Entry.docx)

**Comment by julfikar-tritan** [comment]
Roll out 1:

1. Correct remaining qty. _**Completed**_
2. Update quantity & quantity (base) _**Completed**_
3. Split SO

Roll out 2:
 
1. Block order to sales order reservation flow  _**Completed**_
2. Qty. to convert in sales order selection page in "get block order lines" functionality  _**Completed**_

**Comment by julfikar-tritan** [comment]
Sales Order Updated for SO Number 13102200128 against 11002200098 change this message to
Buyer PO .... splitted to buyer po no....! and open the splitted buyer PO _**Completed**_

Add comments  in source SO as well as destination SO providing relevant information
Add quantity as well in comment as well as notes _**Completed**_

Add  notes in source SO as well as destination SO providing relevant information
Add quantity as well in comment as well as notes

**Comment by julfikar-tritan** [comment]
Linking 2 Source Sales Order as 1 source and 1 Split Sales Order.

If from Block Order(1000 Qty),
the first Source Sales order(1001011) is created for (200 Qty), 
A Second Source Sales Order(1001012) is created with (100 Qty).

Later found out that Second Source Sales Order is actually needs to be Split of first Source Sales Order. So both Sales Orders need to be linked accordingly with Split information indicated in both Sales Orders.
The fresh link should look like:-
Source Sales Order(1001011) (200 Qty).
Split Sales Order(1001012)(100 Qty). [LINKED TO ITS SOURCE SALES ORDER(1001011) THROUGH COMMENTS]

**Comment by prabhupdesh** [comment]
Split So -> create new po -> enter new PO no. On clicking OK a dialog box as attached appears. If "no" is selected still a SO gets created and quantity gets wrongly updated in blockl order. This should not happen. If "no" is clicked then it should not move further. _**Completed**_


![image](https://user-images.githubusercontent.com/61455315/75602385-919c2d00-5aea-11ea-85b5-311bb82df345.png)

**Comment by prabhupdesh** [comment]
![image](https://user-images.githubusercontent.com/61455315/75602374-86490180-5aea-11ea-932c-9517837d5725.png)

**Comment by prabhupdesh** [comment]
![image](https://user-images.githubusercontent.com/61455315/75602391-a37dd000-5aea-11ea-84e5-33217ff2d453.png)

**Comment by julfikar-tritan** [comment]
Creation of New Item in the Split Sales Order

1. Creating a new item in the Destination Sales Order.  _**Completed**_
2. Creating a new line in the respective Block order with the Quantity of new split Order.  _**Completed**_

**Comment by julfikar-tritan** [comment]
_1_> On Comment, 
While Splitting will contain Item No. detail as:
**_Split PO [**ITEM NO**] from : SO NO  / BUYER PO NO / SPLIT QTY
Split PO Created [**ITEM NO**] with : SO NO  / BUYER PO NO / SPLIT _QTY_****Completed_**

_2_> While Splitting Source Sales order to existing Sales Order with status as _Pending Approval_,
On Such cases, Users Need to _Re-Open_ or keep the Sales Order in _Released_ state.  **_completed_**
  
[_A_]While splitting to existing Sales Order, 
 We need to Put a Filter at SO selection Page where User can select Sales Order whose 
status is in Open and _Released.  _**Completed**_

[_B_]While splitting to New Sales Order, 
Need to Check if the Sales Order is in Pending approval state(If the user manually enters Existing Sales Order as New Sales Order no on _creation). _**Completed**_

**Comment by julfikar-tritan** [comment]
In Split Sales Order

1.To Reuse Quantity to Convert instead of Creating new Field. _**Completed**_
2.If source sales order is in Pending Approval status,Creation of Split Order should not be allowed **Completed**

**Comment by prabhupdesh** [comment]
Rename the otions:

Create New PO -> Split & create new PO
Add in Existing PO -> Split & add in existing PO

Remove above option

Split should be at line level _**Completed**_

**Comment by julfikar-tritan** [comment]
Please refer to the Split Sales Order Documentation for further reference.


[Split Sales Order Documentation.docx](https://github.com/BPS-Industries/Navision/files/4301673/Split.Sales.Order.Documentation.docx)

[Split Sales Order Documentation.pdf](https://github.com/BPS-Industries/Navision/files/4301674/Split.Sales.Order.Documentation.pdf)

**Comment by julfikar-tritan** [comment]
As on working on the second Phase,

If the user creates a Sales Order from Block Order. Wherefrom Block Order, Released Production Order(RPO) is already created.
in such a case, Reservation entry is also moved.
If the user has done a mistake while creating the Sales order with less quantity, then the user can call more of the same item by using BLOCK ORDER LINES function.


But, _if the user has done a mistake while creating the Sales order with more quantity, then the user does not have the feature to reduce the quantity, where the reservation is also moved to Block order lines._ **_COMPLETED_**

For the above scenario, we are working on providing a solution.

**Comment by julfikar-tritan** [comment]
Request to take off filters for add in existing PO request page based on customer no, customer season, entity and place a filter based on block order no. _**Completed in LIVE**_

**Comment by julfikar-tritan** [comment]
**A)** For Non-Randa Cases in Block Order,

Based on _CS Customer_ and _Customer Season_ There should not be any Duplicate Block Order creation.
Upon selecting location and in the approval setup it should check. _**Completed**_

**B)** In Block Order Lines,


Item Dropdown should filter items based on Customer Season (Global dimension field)available in the lines. 
The same filter will work on _Sample Order, Sales Invoice, Commercial Courrier and Sample Order_, as it is working on Block Order. (if the Customer Season is removed from the lines then all the items will be available). _**Completed : As discussed we have now moved the code from table level to page level**_

**Comment by julfikar-tritan** [comment]
Reading data from csv for splitting and processing the data to a new sales orders.
Current Format //Kiran
SO No | Line No | Quantity | Item No | Existing Buyer PO No | New Buyer PO No
CSV Format

**Comment by prabhupdesh** [comment]
[Split Sales & Reservation Documentation.docx](https://github.com/BPS-Industries/Navision/files/4336812/Split.Sales.Reservation.Documentation.docx)
[Split Sales & Reservation Documentation.pdf](https://github.com/BPS-Industries/Navision/files/4336814/Split.Sales.Reservation.Documentation.pdf)

**Comment by julfikar-tritan** [comment]
[Split Sales & Reservation Documentation III.docx](https://github.com/BPS-Industries/Navision/files/4348680/Split.Sales.Reservation.Documentation.III.docx)
[Split Sales & Reservation Documentation III.pdf](https://github.com/BPS-Industries/Navision/files/4348681/Split.Sales.Reservation.Documentation.III.pdf)

Modified Documentation
