### ISSUE TITLE
Bin Transfer -Shipment of FG in Intransit Bin

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#202]
Provide me the functionality to ''Select PO" in internal movement page.
Fields to be added in internal movement page
Sales Order.No
Customer.No
Buyer.Po.No
Shipment Date

**Comment by YashwanthGowdaJ** [comment]
@ramapandian14 I have given "Select PO" functionality in warehouse receipts. Please check and confirm.

Development done in test server.
