### ISSUE TITLE
 Fix the qty as 1 in purchase order and purchase invoice if it is fixed asset

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#205]
In purchase order and purchase invoice dont allow to add more quantity, the quantity as 1 Nos, not greated than 1, or not  less than one. and MRP Buy to stock, PD indent also.

**Comment by YashwanthGowdaJ** [comment]
Development done is live server.

For fixed assets, quantity will be always 1.

**Comment by IT-Saravanan** [comment]
Task completed Working fine in live.
