### ISSUE TITLE
Fixed Asset Card

### ISSUE THREAD

**Issue by dhivyabarathi** [BPS-Industries/Navision#207]
1.Release approval for Prabh, Ram, Dhivya - Only if status is open, release button should work.
2.If Fixed Asset card is clicked for approval the actual fixed asset card also should go for approval and while approving fixed asset automatically actual fixed asset card should go for approval.
3.In Fixed Asset label while printing Tritan\Ram - name only should printed.

**Comment by YashwanthGowdaJ** [comment]
@dhivyabarathi I have made the necessary changes as mentioned above in live server. Please check & confirm.

**Comment by dhivyabarathi** [comment]
Another point to be added as discussed with sir today.

- If they Print label from FAV Card it should not allow to print, it should allow to print label from Actual Fixed Asset card.

**Comment by YashwanthGowdaJ** [comment]
Label cannot be printed from FAV cards. I have included this control in fixed assets.

Development done in live server.
