### ISSUE TITLE
Suggest ESI, PF Payments

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#208]
Suggest ESI payment button required in Payment journal.

Functionality:

This function creates payment journal line from posted entries in ESI payable & for the month

**Comment by YashwanthGowdaJ** [comment]
I have created button called as "ESI Payable" in payment journal which gets details from GL Entries and creates journal entries.

check. Development done in live server.

**Comment by YashwanthGowdaJ** [comment]
No need to create entries in journals employee wise. We have decided to split the entries after posting. 

ESI, PF payments will work as before(Removed restrictions on employee & Dept for those Ledgers)
