### ISSUE TITLE
Warehouse Shipment need this in points to be added

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#211]
- Unit Price column in warehouse shipment will flow from sales order unit price
- Warehouse should flow from item card if sales order amended then flow from sales order lines
- Purchase Order ( Buyer's Original PO) link should travel and flow automatically from the sales order so as to do cross verification prior to proceeding the booking.
- Standard Tolerance level to be included so as to skip additional block order / sales order  - For example - + or - 2% (plus or minus 2% allowed on all CRG brands)
-  Image Guide should flow from sales order 
-  Email / Alert notification to be accessed for both sender and assigner ! 
![image](https://user-images.githubusercontent.com/61489309/135086376-ad1cac17-4d04-45bc-8dc7-ba5ce4c7ab86.png)

**Comment by YashwanthGowdaJ** [comment]
Name : Automated Shipment Worksheet

I have given a button in warehouse shipments, to create warehouse shipments for the selected po's. 

Links are also copied. Given access to image guide. 

@IT-Saravanan Please check and confirm.

Development done in test server.

**Comment by YashwanthGowdaJ** [comment]
Development moved to live.

@IT-Saravanan  Please mention the working process here.

**Comment by IT-Saravanan** [comment]
Need carton properties Button, the moment i click the button Carton details need to show FG based BOM on the FG's weight & carton Dimensions and weight .
Show the Field in FG Card Page to update the Net weight for the FG,
Need Weight Field on Carton Item Attributes to update the carton weight.
based on FG' weight system should automatically calculate the weight in Net weight quantity Field on packing list
Gross weight should calculate based on carton weight +Net weight
