### ISSUE TITLE
Product Group Code-BWGS

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#213]
Belt Wallet as Gift Card

**Comment by IT-Saravanan** [comment]
Product Group Code Created as BWGS (Belt Wallet Gift Set).
FGD/FGP creation is happening. 
Shipper BOM Addition is working.
Block order / Sales order creation is happening. 
Explode BOM is Working in sales order and Block order.
Needs Form showing the proper Item quantity's in Sales order.
Item Card Customer Season fixed as 21-RAND-ALL-ALL-AS

**Comment by YashwanthGowdaJ** [comment]
Development moved to live as confirmed by Saravanan.
