### ISSUE TITLE
Export Invoice From Navision

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#215]
For Developing Export invoice Find the Image
![Export Invoice](https://user-images.githubusercontent.com/61489309/142975212-c3e0f3a5-3c17-41ca-a71d-59c0d2e20f5b.png)

**Comment by surajsrivastava1991** [comment]
Hi @IT-Saravanan ,

Please check the report once ,need to know the few things related to packing or courier cost . and discount amount as well

**Comment by IT-Saravanan** [comment]
For Develping Packing Order Find the image
![Packing List](https://user-images.githubusercontent.com/61489309/143861945-1fb86f41-ef93-4bf4-8033-ebef20cadf88.png)

**Comment by IT-Saravanan** [comment]
[Bond doc.xlsx](https://github.com/BPS-Industries/Navision/files/7653724/Bond.doc.xlsx)
GRN No (Posted Purchase Receipt No) : 40412210001
