### ISSUE TITLE
Not to check for GST Registration No. for Location 11

### ISSUE THREAD

**Issue by YashwanthGowdaJ** [BPS-Industries/Navision#219]
While taking PO print, system is checking for GST registration No. 

Still we have not received GET No. for location 11. So need to bypass this condition for location 11.

Changes are done in GST Management(16401) codeunit under below 2 functions
1. PurchasePostValidations
2. CheckLocation

In live server.

**Comment by prabhupdesh** [comment]
@YashwanthGowdaJ @IT-Saravanan : Seems now ABPS gst no. is available. Please remove this check.
GST no. to be mandatorily available for all locations

**Comment by YashwanthGowdaJ** [comment]
Enabled the code to check GST Registration No.
