### ISSUE TITLE
Prices for Liability seasons flow from Actual seasons

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#220]
Merchants raise the Our liability indent. while raising the indent sourcing team need to update the price master in each items. so we need to develop the functionality copy the price master from actual season to our liability season. 

Filter is required : <>All season

**Comment by YashwanthGowdaJ** [comment]
Development is done in test server.


Given a button in customer season page, on clicking a customer season list page will get open, where users will select a destination customer season(filtered only on actual seasons, our liability & customer liability seasons). And thus a record will get created in customer season Item table and also all released prices flow from source customer season to destination customer season with released status itself.

Table Change : Added an option under "Cust. season type" called "Our Liability" in "Dimension Value" table

**Comment by IT-Saravanan** [comment]
[Price Master Copy one season to Another season Functionality.docx](https://github.com/BPS-Industries/Navision/files/7685136/Price.Master.Copy.one.season.to.Another.season.Functionality.docx)
Attached the User manual Document. This Functionality Moved to live.
