### ISSUE TITLE
Bin transfer Ware house Journal with Source no and GRN no

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#222]
In purchase order Some Orders Sourcing Team creating In-Transit GRN With (In-transit Bin), After physically receiving the Goods stores Users Making Internal movement (Bin Transfer). While making Internal movement (Bin transfer) Source no Source Line No Reference no and Reference Line no Not coping , so we cant find which purchase order Goods lying in the in In-transit. so need one functionality to create internal movement in purchase order page. 

What that functionality do is when i click that button internal movement page will open with Item no From bin In-transit and Quantity, Flow from purchase order and To bin UA . then user will enter the physically received Quantity and Click the button Create inventory movement. While clicking the button in Warehouse Journal will create with purchase order no purchase order line no and GRN no and GRN line No.

**Comment by prabhupdesh** [comment]
Test cases: 

https://docs.google.com/spreadsheets/d/1VzTT_R9C4C4zcfERzfRyRu1DYGKKn_CsMDLtZ74w6YY/edit?usp=sharing

**Comment by shankar0517** [comment]
Have developed the functionalities based on the above given test cases and moved changes to live. Kindly check it and let me know in case of any changes or issues.
