### ISSUE TITLE
To handle Intransit Stock

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#223]
While Creating purchase order Example : location Code  44-main then user creating Warehouse receipt the movement they selected the Bin as 44-In-T. after physically received the stock in stores they are transferring the bin 44-In-T to 44-UA. this is the process going on. For this process we cannot find any tracking on IN-Transit qty purchase order wise. 

As discussed to resolve this type of issues  to create a In transit location and (IN-T) in transit bin.
so the movement user post the warehouse receipt for IN transit  materials will receive the proper location and suddenly material will go to IN transit location via Item reclassification, and stocks received physically users need to transfer the bin internal movement need to do via posted purchase receipt 

In posted purchase receipt place a button. that button what do is ?
It will create internal movement for bin transfer and location transfer.

**Comment by IT-Saravanan** [comment]
INTRASIT

**Comment by IT-Saravanan** [comment]
Later we have discussed creating of Intransit location will handle this issue for internal movement itself via copying the Posted purchase receipt no while transfer the stock intransit to unassinged bin.

**Comment by IT-Saravanan** [comment]
#222

**Comment by prabhupdesh** [comment]
Now with every stock movement in internal stock movement from intransit bin, system captires relevant posted purchase receipt no / GRN no..

Using this value , we can know if relevant intransit stock has been physically received at our location.

Closing this requirement
