### ISSUE TITLE
Navision controls

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#224]
As per our discussion we are going to do this controls on Navision
1.Qty to consume 0 qty not allowed while receiving Job work order.
2.Job work order fully received, Qty to consume cannot be editable.
3.Customer season mandatory in job work order.
4.Sub contract order approval is required. without approval not allowed send or receipt.
5.Warehouse receipt need check mark for stores manager, give a Boolean field user will assign to stores manager for warehouse receipt after stores managers confirm receipt should post.
6.In consumption journal not allowed to enter more than job card quantity.
7.In consumption journal users will enter more than job card quantity stores manager should approve.
8.Output journal Job card division wise needs to show output quantity at the bottom.
Ex. If the wallet Production only show wallet output quantity if belt production show belt output quantity at bottom output journal page.
9.Gate entry error to be correct.
10.Job work order report and delivery challan report show approved by in signature part.

**Comment by IT-Saravanan** [comment]
11. Purchase order Report signature approved by should take last approved by

**Comment by IT-Saravanan** [comment]
12.Bring notes and links from Item Journal to Item ledger entries

**Comment by prabhupdesh** [comment]
1.Qty to consume 0 qty to accept not allowed while receiving Job work order...incomplete
2.Job work order fully received, Qty to consume cannot be editable........done
3.Customer season mandatory in job work order.done
4.Sub contract order approval is required. without approval not allowed send or receipt.
5.Warehouse receipt need check mark for stores manager, give a Boolean field user will assign to stores manager for warehouse receipt after stores managers confirm receipt should post.
6.In consumption journal not allowed to enter more than job card quantity.
7.In consumption journal users will enter more than job card quantity stores manager should approve.
8.Output journal Job card division wise needs to show output quantity at the bottom.
Ex. If the wallet Production only show wallet output quantity if belt production show belt output quantity at bottom output journal page.
9.Gate entry error to be correct.
10.Job work order report and delivery challan report show approved by in signature part.
