### ISSUE TITLE
Flow Emp Info to Daily Attendance

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#226]
Department, Section, Sub Section, Division, Physical Location (Nav).
Above 5 fields are available in employee card. Please ensure that values of these fields are being captured in daily attendance table.

**Comment by shankar0517** [comment]
Have added one field physical location in Daily Attendance table and have added the logic for capturing five fields (Department, Section, Sub Section, Division, Physical Location (Nav)) in Daily Attendance Date Wise1 page where we are capturing day to day In & Out time for all the employees . Have done all these modifications in TEST Server. Kindly Check and let me know so that I can move it to Live Server.

**Comment by shankar0517** [comment]
@nagalakshmi2022
 Kindly update the process from end to end. Update the tested employee cases.

**Comment by nagalakshmi2022** [comment]
Division updation in Employee Daily attendance
1.	Go to Employees
2.	Filter by Employee No  Edit  Navigate  Employee Record Update
3.	Enter Details in the following fields, Up dation Date, New Department, New Physical Location, Section, Sub section, 
Division
5.	Click Update Employee Record (this update the employee record as per the details entered effective from up dation date)
6.	Go to Daily attendance , then Enter Employee No.
7.	Will get the details of the employee with changes from updation date in Department, Division, Section, Subsection, Physical Location and Division.


Have tested this for the employee numbers  9313, 9375,9404

**Comment by prabhupdesh** [comment]
Please make this functionality live today.

**Comment by shankar0517** [comment]
The functionality have been moved to Live yesterday.

**Comment by prabhupdesh** [comment]
Issue found wherein their are two columns for department serving same purpose in Daily attendance,
Please flow department code value to already existing column name i.e., "Department" and not to "Department code"

**Comment by shankar0517** [comment]
Have made the changes in Live and made department field to flow in "Shortcut Dimension 3 Code " in Daily Attendance table.
