### ISSUE TITLE
Link document Functionality

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#227]
Need Functionality to link the documents
In Payment Journal Page while making the payment journal entry against Purchase order, Job work order, unposted purchase invoice, unposted sales invoice and Sales/Block order user need to select multiple document in one shot. 

We need to store the linked document no in separate table.
If we select "Link documents" for payment against purchase order, Unposted purchase invoice, Job work order, Vendor documents are need to getting listed below mentioned filter .
1.Vendor No
2.Document sent = True
3.Contract = False 
4.Date = 3 Months period
5.Entity

If we select "Link documents" for payment against Sales/Block order and unposted sales invoice Filters Customer documents are need to getting listed below mentioned filter
1.Customer no
2.Entity
3.Date = 3Month period

**Comment by IT-Saravanan** [comment]
Journal vouchers need the link document functionality if the GL account is Prepaid Expenses then document link should be mandatory.
Open GL entry Table Filter 
1.GL Account no
2.Document type: Invoice
3.Amount =>0
4.Posting date =3Month Period.

**Comment by IT-Saravanan** [comment]
Payment Journal link document functionality moved live.

**Comment by YashwanthGowdaJ** [comment]
#148
