### ISSUE TITLE
Consumption journal positive entries

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#228]
While making consumption journal positive entries make applied entry no is mandatory..
![image](https://user-images.githubusercontent.com/61489309/176987655-0feda5f4-980d-4da9-9096-689c36a34d73.png)

**Comment by prabhupdesh** [comment]
Status please : choosing entry no. while posting positive consumption was to be made mandatory

@IT-Saravanan

**Comment by prabhupdesh** [comment]
@IT-Saravanan : if done , please close this

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ Status please?
