### ISSUE TITLE
Salary Register 

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#229]
Align the salary register for attached Excel F
[Monthly Salary Dtl Sign Report.xlsx](https://github.com/BPS-Industries/Navision/files/9036417/Monthly.Salary.Dtl.Sign.Report.xlsx)
ormat.

**Comment by Abigaiel** [comment]
@IT-Saravanan 
   Salary register report is aligned as per attached Excel File in test server. please check.

**Comment by IT-Saravanan** [comment]
![image](https://user-images.githubusercontent.com/61489309/177111543-ed0f4f8c-26a4-4dac-9bfa-861cbf7efecf.png)
Correct the layout and show the numbers in same way Ex: Somewhere showing 100, some where showing 100.00

**Comment by IT-Saravanan** [comment]
![image](https://user-images.githubusercontent.com/61489309/177112400-b8dd6b37-e45a-4a92-9d55-ef63caa0aef9.png)
Check the travel ded Value this employee there is no travel ded for the selected employee no.

**Comment by Abigaiel** [comment]
![image](https://user-images.githubusercontent.com/105533910/177127663-41781f6e-d865-4892-8f7f-dd087bf3e678.png)

All the values are coming fine.

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ This Report Working fine Move this to live.

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan Report has moved to live.

**Comment by prabhupdesh** [comment]
Closing this issue as report moved to live
