### ISSUE TITLE
Purchase invoice while posting it is checking Prepayment Amount. 

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#230]
![image](https://user-images.githubusercontent.com/61489309/177247262-be7cb38f-746e-46a3-8669-4cd6b3d7112c.png)

**Comment by YashwanthGowdaJ** [comment]
What needs to be done here?
Should I remove error message?
Should I change the error message?
Should I need to show this error message while sending for an approval?
Should I comment ?

**Comment by IT-Saravanan** [comment]
First check why this error coming while posting?

**Comment by prabhupdesh** [comment]
Status please @YashwanthGowdaJ @IT-Saravanan
