### ISSUE TITLE
Purchase Invoice Default MIS Dimensions

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#234]
In payment Journal dimension Mark Department, Division, Mis Location as Linked, while applying the entries

**Comment by prabhupdesh** [comment]
**Purchase invoice**

**Header:**
MIS Location: BL: By linked
Division: BL: By Linked
Department: BL: By Linked

**Lines:**
IF Type: Item (Charge): 
MIS Location: BL: By linked
Division: BL: By Linked
Department: BL: By Linked

IF Type: G/L account: Below values should not be allowed for MIS dimensions
MIS Location: BL: By linked
Division: BL: By Linked
Department: BL: By Linked

IF Type: Item and receipt no. = '': Below values should not be allowed for MIS dimensions
MIS Location: BL: By linked
Division: BL: By Linked
Department: BL: By Linked

IF Type: Item and receipt no. <> '': 
MIS Location: BL: By linked
Division: BL: By Linked
Department: BL: By Linked

IF Type: Fixed Asset: populate 
MIS Location, Division, Department from fixed asset card
