### ISSUE TITLE
New Product Group : PVC

### ISSUE THREAD

**Issue by nagalakshmi2022** [BPS-Industries/Navision#235]
Create New Product Group PVC under Item Category RM
Templates same as PU

**Comment by Abigaiel** [comment]
Dear @nagalakshmi2022 and @IT-Saravanan 
 I have created PVC Product group in test server.
please check.

**Comment by IT-Saravanan** [comment]
@Abigaiel Item description not flowing to child card. Please check

**Comment by Abigaiel** [comment]
@IT-Saravanan 
Now Item description is flowing in child card. Please check.

**Comment by IT-Saravanan** [comment]
@Abigaiel item description not coming properly please check.

**Comment by Abigaiel** [comment]
![image](https://user-images.githubusercontent.com/105533910/181876170-2a60ddab-6b38-4c67-adca-04e62345c820.png)

Description is flowing same as PU. What else should be added here?

**Comment by IT-Saravanan** [comment]
![image](https://user-images.githubusercontent.com/61489309/181876330-c9702c51-3192-4a00-b837-7a0623c03966.png)

not flowing the description properly

**Comment by Abigaiel** [comment]
This is PU
![image](https://user-images.githubusercontent.com/105533910/181877174-f6f2c525-db52-402e-8d56-72ec2eed8efc.png)
This is PVC
![image](https://user-images.githubusercontent.com/105533910/181877268-bc240f51-8fba-46cc-9193-4fbef0895b09.png)

**Comment by IT-Saravanan** [comment]
This is PU
![image](https://user-images.githubusercontent.com/61489309/181877946-fd7601aa-bc72-40ac-a30a-f82837d53474.png)

This is PVC
![image](https://user-images.githubusercontent.com/61489309/181877968-e1d08aa1-0104-45c9-8b3e-226cd98ef486.png)
Check the Description is not flowing properly.

**Comment by IT-Saravanan** [comment]
PVC Items description creating properly please move this to live.

@ yashwanth Please add this product group in BOM Wherever Pu is there, so that costing team to add this items in there BOM.

**Comment by Abigaiel** [comment]
New product group PVC moved to live .

**Comment by prabhupdesh** [comment]
![image](https://user-images.githubusercontent.com/61455315/186856041-392fc4af-81ad-40bc-9962-c1ff94079e4e.png)
