### ISSUE TITLE
Documents to be created only in tritan

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#236]
Creating Purchase orders (for domestic suppliers at present, for import suppliers to be added later)  in BPS should not be allowed.
While creating purchase order from MRP, users should get a error message if they try creating purchase orders in BPS.

At present the process is, 
From MRP requisition line, users clicks on Create purchase order which opens a Request page.

Solution proposed is to provide an Entity field in this request page wherein users can select relevant entity. Default entity in this field should be what has been updated in requisition line.

Fixing open purchase orders:

1.  All the partially received / not received domestic purchase orders (currency code = '')  in the system in entity BPS should be marked with entity as Tritan
2. If entity = Tritan and delivery location is 44,99,14 then gst remains the same as of Tritan's
3. If entity = Tritan and delivery location is mepz location (15,17,28) then GST is "Applied for". This to be shown in purchase order
4.  IF PO is partialy received, then purchase order to show remaining qty. only
5. Purchase order no. should not change

**Comment by YashwanthGowdaJ** [comment]
If entity is tritan and location is 15,17,18 then GST registration No is updated as 'A/F'

**Comment by IT-Saravanan** [comment]
Add Unit 14 Also GST No as A/F

**Comment by YashwanthGowdaJ** [comment]
Added unit 14 under 'A/F' registration

**Comment by IT-Saravanan** [comment]
Confirm once done

**Comment by IT-Saravanan** [comment]
Any Updates in purchase order.

**Comment by IT-Saravanan** [comment]
![image](https://user-images.githubusercontent.com/61489309/181877188-a1afb6b9-2493-4db5-a6fe-5dc2de669c23.png)
GST A/F not Showing

**Comment by IT-Saravanan** [comment]
In purchase order check Bill to location  and ship to location
![image](https://user-images.githubusercontent.com/61489309/181877280-22bb4291-ee8a-4fd4-b3df-e9c918a16261.png)
If Bill to location is blank  Print location code Address, Bill to location having some value print bill to location address.

**Comment by Abigaiel** [comment]
@IT-Saravanan 
As per your confirmation we have made the following changes and moved it to live in purchase order.
1. location code address
2. bill to location address
3. GST Reg no

**Comment by prabhupdesh** [comment]
@IT-Saravanan : if working fine then close this

**Comment by IT-Saravanan** [comment]
Waiting For GST No to update, then will close.

**Comment by IT-Saravanan** [comment]
GST No Updated for Locations 17, 28-29, 15-18.
[GST TRITAN MEPZ Certificate.pdf](https://github.com/BPS-Industries/Navision/files/9487653/GST.TRITAN.MEPZ.Certificate.pdf)

**Comment by Abigaiel** [comment]
@IT-Saravanan 
As per your requirement , We have created  GST amount field in purchase return order report same as purchase order GST .
Please check GST values are coming properly or not. please confirm.

**Comment by IT-Saravanan** [comment]
CGST,SGST and IGST Showing Properly in the report Please move this report in live.

**Comment by Abigaiel** [comment]
Purchase return order GST calculation moved to live.

**Comment by IT-Saravanan** [comment]
Working fine.
