### ISSUE TITLE
BPS to Tritan Entity Change 

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#237]
1.Give a button in purchase order to change the purchase order entity .
2.Entity transfer allowed BPS to Tritan
3.Sales order need to change the entity requested by amudha ( already functionality is there)

**Comment by shankar0517** [comment]
Have created the button based on the logics provided and have checked with @IT-Saravanan and he said it to move the button to live and have moved it in both sales order and purchase order.

**Comment by IT-Saravanan** [comment]
In customer season transfer page allow entity transfer from BPS to TRITAN, and Dont allow entity transfer from Tritan to BPS ,from Tritan to ABPS , ABPS to TRITAN and BPS, Tritan, BPS to ABPS.

**Comment by IT-Saravanan** [comment]
@shankar0517 @Abigaiel  Status please

**Comment by Abigaiel** [comment]
@IT-Saravanan 
In customer season transfer page and customer season stock transfer page we have gave the functionality Entity Transfer BPS to TRITAN.
In customer season stock transfer page New Entity column is added.
please check and confirm.

**Comment by IT-Saravanan** [comment]
@Abigaiel BPS entity to Tritan only allowed, not allowed Tritan to BPS or ABPS. Place the control and confirm

**Comment by Abigaiel** [comment]
@IT-Saravanan  I have placed the required control in Customer-Season Transfer page and Customer Season Stock Transfer page. Please check and confirm.

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ 
I have checked Please move this to live.

**Comment by Abigaiel** [comment]
Entity change functionality is moved to live in Customer-Season Transfer and Customer Season Stock Transfer pages.

**Comment by IT-Saravanan** [comment]
moved live
