### ISSUE TITLE
Released Production Orders

### ISSUE THREAD

**Issue by nagalakshmi2022** [BPS-Industries/Navision#239]
Automatic mail has been sent for material requisition in released production orders by clicking the below button for unit 14. We need the same for Unit 44 & 99 based on user setup
![image](https://user-images.githubusercontent.com/101811185/183020556-6c4f9c0a-c999-4d0a-819a-dbe40bd8a44e.png)

**Comment by YashwanthGowdaJ** [comment]
How system know to whom mail should go based on the location?

**Comment by prabhupdesh** [comment]
@YashwanthGowdaJ @shankar0517 : Status please?

**Comment by IT-Saravanan** [comment]
How system know to whom mail should go based on the location?
Based on user setup
![image](https://user-images.githubusercontent.com/61489309/186878842-84398ba4-52ad-45ce-99be-eeb6ec050cbf.png)

**Comment by prabhupdesh** [comment]
@IT-Saravanan @YashwanthGowdaJ @shankar0517 : status?
