### ISSUE TITLE
Sample Order/Non Sample Order

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#240]

**Comment by prabhupdesh** [comment]
Sample Order/Non Sample Order

**Comment by prabhupdesh** [comment]
Abigaiel/Nagalakshmi , please update the status on this

**Comment by Abigaiel** [comment]
@nagalakshmi2022 
->In Sample order list page on clicking New we have provided two options
   1. Sample Order
   2. Non Sample Order 
->In Non sample order page I made all the ship-to fields editable
->Only TRITAN Customer is allowed to flow in the CS- Customer in  Non-Sample order page.
->Name of the Sample Order Page has been changed into Sample/Courier Order.

**Comment by Abigaiel** [comment]
Development done in test server. check and confirm

**Comment by IT-Saravanan** [comment]
![image](https://user-images.githubusercontent.com/61489309/186903806-3b2ad1d7-067e-4a34-8d01-ab59f005e489.png)

Non sample order while selection the tritan customer am getting this error

**Comment by IT-Saravanan** [comment]
If i select only buyer as tritan i cant able to select All Season

![image](https://user-images.githubusercontent.com/61489309/186904191-0c1606d8-7de6-49d9-9387-301f442c7f32.png)

**Comment by prabhupdesh** [comment]
@Abigaiel : please upadte the status on issues raised by saravanan

**Comment by Abigaiel** [comment]
@IT-Saravanan 
Now only TRITAN & VENDOR customers is allowed to flow in the CS- Customer and 'ALL' customer season is allowed  in Non-Sample order. Check and confirm.

**Comment by IT-Saravanan** [comment]
@nagalakshmi2022 Create some sample order and non sample order and give the feedback.

**Comment by Abigaiel** [comment]
@IT-Saravanan @nagalakshmi2022 
In sample order page SUP division  is not allowed to flow in Division and  'ALL' customer season is not allowed.
we have created division column in sample order lines.
In sample order and Non sample order page division will flow based on customer season.
In both pages Dimension button have  hidden as per your requirement please check and confirm.

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ @Abigaiel please move sample order and non sample order to live.

**Comment by Abigaiel** [comment]
Sample order and Non sample order  moved to live.

**Comment by IT-Saravanan** [comment]
moved live
