### ISSUE TITLE
Employee Transfer from BPS to Tritan

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#241]
Saravanan, list down all the tasks to be done here

**Comment by prabhupdesh** [comment]
@IT-Saravanan

**Comment by prabhupdesh** [comment]
Assigned to @shankar0517

**Comment by IT-Saravanan** [comment]
![image](https://user-images.githubusercontent.com/61489309/186878338-831e31c6-364d-4973-823c-bd13e034de7f.png)

**Comment by IT-Saravanan** [comment]
1.Employee transfer done
2.Pay Element created for all transferred employees
3.No series created
4.General business and prod posting Setup done
5 Hr location created.
6.New loan cards created
Pending loan closure.( waiting for Accounts suggestions)

**Comment by prabhupdesh** [comment]
Dear Sir

Please make a correction in the pay slip for New payroll locations. (Tritan, Tritan 15, 14,17,28 &99)

1. Address is not shown, as well as factory license number and pay slip month.
2. Page setup. (A5)

3. Signature of the Manger

Tritan 44 - Mr. KV. Rao sir
Tritan 15 - 28 - Mr. Akhtar sir
Tritan14 - Mr  Sathishlingam
Tritan 99 - Mr. MN Rao

**Comment by Abigaiel** [comment]
@IT-Saravanan 
In payslip report we have added the address for new payroll locations(Tritan unit 14,15,17, 28 and 99) and signature of the manager also changed . changes are done in live server .please check and confirm.

**Comment by prabhupdesh** [comment]
Done
