### ISSUE TITLE
Mapping COA Fixed entries with actual FA cards

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#242]
@IT-Saravanan , @nagalakshmi2022 : Update daily status of how many done out of how many fixed asset pending

**Comment by prabhupdesh** [comment]
@nagalakshmi2022 @IT-Saravanan : please update the status on daily basis

**Comment by prabhupdesh** [comment]
1.  Creating BPS PM cards as Tritan prefixed card. Batch job. Depreciation book code to be company act
2. Change entity in new FA card
3. Create reclassification journal for posting the entries
4. BPS FA. Gross block: 100000, IT Act depr.: 70000. WDV: 100000-70000=30000. 30,000 becomes gross block/ Acquisition Cost in new FA Tritan's card
5. Depreciation starting date : 01.10.21
6. Update depreciation in already existing tritan's  card  to be updated as on 31.03.22.
7. From 01.04.22 onwards, run depreciation batch job in navision to calculation depreciation every month. Need to check program related to calc. depreciation in nav

**Comment by prabhupdesh** [comment]
1. Vehicles : nagalakshmi to clear. Value, information.
2. Office equipment: 
3. Electrical equipments
4. Leasehold
5. Furniture & fixture

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan 
Button given in fixed asset list page, which will create tritan cards for the selected lines, and FA reclassification journal will get created to move values from BPS card to TRITAN card. Development is done in test server. 

Please check & confirm.

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ 
Tritan Fixed asset Card Creation is working fine, 
Book Value need to flow for fa journal 
now it is flowing total asset value.

**Comment by YashwanthGowdaJ** [comment]
Now corrected. Book value is flowing to journals.
