### ISSUE TITLE
Changes related to order multiple in purchase order

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#243]
For order multiple functionality in purchase order, lines to be splitted by MIS location, Department, Division. Customer season to be respective divisionalised "our liability" season

**Comment by prabhupdesh** [comment]
@IT-Saravanan @YashwanthGowdaJ: to take care

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ Any update

**Comment by prabhupdesh** [comment]
Saravanan has checked with purchase team. it is working fine.
