### ISSUE TITLE
Sustainable Type

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#244]
Sustainable type field required in Item card. Basis sustainable type MOQ pick up from vendor item parameter changes.

@Abigaiel @nagalakshmi2022: to take care

**Comment by prabhupdesh** [comment]
@prabhupdesh

**Comment by prabhupdesh** [comment]
@prabhupdesh

**Comment by prabhupdesh** [comment]
<html>
<body>
<span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Hi Prabh,</span><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">find below a list of sustainable types </div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br></div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Abbreviation | Standard Name
-- | --
LWG Gold | Leather Working Group - Gold
LWG Silver | Leather Working Group - Silver
LWG Bronze | Leather Working Group - Bronze
GRS | Global Recycled Standard
RCS | Recycled Claim Standard
GOTS | Global Organic Textile Standard
CCS | Content Claim Standard
RDS | Responsible Down Standard
RWS | Responsible Wool Standard

</div><br class="Apple-interchange-newline">
</body>
</html>

**Comment by Abigaiel** [comment]
@IT-Saravanan @nagalakshmi2022 
1. We have created  Sustainable field and placed it in create item. Selected sustainable type will flow in description prefix , item attribute and item attribute fact box. we have done this only for product group PU if it is working fine we will do for other product groups.
2. For Product group LE sustainable type gets updated from vendor card.
3. In vendor card we have added the sustainable field.

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ @Abigaiel 
Sustainable type working fine in Test Server Move this to live

**Comment by prabhupdesh** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/prabh/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/prabh/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Sl. No. | Remarks
-- | --
1 | In   create item page, while selecting "sustainable type", description   field should get updated.
2 | In   leather, sustainable type flows from vendor card to create item. So, the   field in create items should be non editable
3 | Sustainable   type to appear in description
4 | The   field should be non editable  in item   attributes page of leather card as value flows from vendor card



</body>

</html>

**Comment by prabhupdesh** [comment]
In other product groups, sustainable type doesn't flow from vendor card and is a part of item attributes which should appear in item description

**Comment by prabhupdesh** [comment]
After leather, lining & interlining

**Comment by Abigaiel** [comment]
@IT-Saravanan 
Have Created "Sustainable type"  field for product group LE , LI and IL .
1. For Product group LE sustainable type gets updated from vendor card .
2. I have made "Sustainable type" field as non editable in item attribute for LE , LI and IL product groups.
3. While selecting  sustainable type, description field gets updated.

**Comment by prabhupdesh** [comment]
Please move this development  to live

Below google sheet contains sustainable types that needs to be updated for each vendor card. Please update this also in vendor card.

https://docs.google.com/spreadsheets/d/1TtasfLNXUHOF78ZRfc1nBrOAgl-s8pO5PiAA16o6z9g/edit?usp=sharing

**Comment by Abigaiel** [comment]
Sustainable types have been updated in Vendor card and has been moved to live.

**Comment by IT-Saravanan** [comment]
working fine.
