### ISSUE TITLE
MSP-Machinery Spare Parts

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#245]
All changes related to MSP goes here

**Comment by YashwanthGowdaJ** [comment]
While creating a MSP card, Gen Prod. Posting Group has changed to "MSP-S" from RM. Changes are done in live.

**Comment by prabhupdesh** [comment]
@IT-Saravanan :  for all MSP items, Machinery spare parts ledger to be debited. Please change the same in all item cards and update here

**Comment by IT-Saravanan** [comment]
All MSP Item card updated Gen.Prod Pos Group as MSP-S

**Comment by prabhupdesh** [comment]
Saravanan - In test server,

Mark an item's gen prod posting group as "MSP-s"
Perform/post a transaction related to purchase invoice by selecting such
item.
Check if gl posting is going to correct / required GL's

also share the posted document no. here.

Prabh Singh | Chief Information Officer





44 anna salai, nagalkeni, chromepet, chennai 600 044. india | mobile: +91
99405 21846 | board: +91 44 4207 3000 | Linkedin
<https://www.linkedin.com/company/2099701?trk=tyah&trkInfo=tarId%3A1406614068860%2Ctas%3Atritan%20leather%2Cidx%3A1-1-1>
 | Office Map <https://goo.gl/maps/ZbsCZ>
