### ISSUE TITLE
Link Documents- Link to Posted purchase invoice

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#246]
@Abigaiel @IT-Saravanan  : need functionality to link to posted purchase invoice in link document functionality

**Comment by Abigaiel** [comment]
Dear sir 
We already gave that posted purchase invoice button in link document functionality . In payment journal now we gave all the buttons.

**Comment by Abigaiel** [comment]
As discussed location code filter removed in every button in link document functionality.

**Comment by Abigaiel** [comment]
@IT-Saravanan 
In Purchase Invoice we have gave link document functionality in purchase line .
In link document functionality have placed  a button named sample order as per your requirement. Please check and confirm.

**Comment by Abigaiel** [comment]
@nagalakshmi2022 
In payment journal  I have created employee button in link document functionality. Please check and confirm.

**Comment by nagalakshmi2022** [comment]
Employee Linking functionality is working fine. 
Selected Employees were able to view in Journal linked documents in General Ledger Entries.
![image](https://user-images.githubusercontent.com/101811185/194697255-9e93f174-f3bb-4554-9c14-19f381956034.png)

**Comment by IT-Saravanan** [comment]
completed
