### ISSUE TITLE
Order multiples - move to our liability season

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#247]
our liability season to be division wise

**Comment by prabhupdesh** [comment]
@YashwanthGowdaJ @IT-Saravanan : please prioritise this

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ any update

**Comment by YashwanthGowdaJ** [comment]
Hello, I am not aware what to do here?
Nothing explaining, and asking the update for every task??
First prioritize the existing tasks, and give the works priority wise.
And just asking the update will not yield any result.
First create the possible scenarios and then tell the development along with testing scenarios.

**Comment by IT-Saravanan** [comment]
Functionality moved live
