### ISSUE TITLE
MRP Requisition Dimension combination check

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#249]
Need to place dimension combination check in MRP while raising a request, so that wrong combination of mis location  Division and department cannot be chosen as below:

![image](https://user-images.githubusercontent.com/61455315/187023976-2a42b3eb-c72f-465f-92dc-cd98dbcd06e0.png)

**Comment by prabhupdesh** [comment]
@shankar0517 : please do

**Comment by prabhupdesh** [comment]
@nagalakshmi2022 to check

**Comment by IT-Saravanan** [comment]
Please Give a Function to auto update all dimension, because  some times we are allowing wrong dimension, because of older entries. so give a function to auto update all dimension by clicking the button.

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan 
Where it should auto update?
From where I should take values for auto updation?
Where you need button?

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ 
1. In dimension combination
2. Take the values from BUCL from 349 Table.
3. Dimension combination page No 9251.

**Comment by YashwanthGowdaJ** [comment]
Oh. you have added comments in "MRP Requisition dimension combination check" github task. 
So I thought its for MRP.

So this functionality you need in Dimension combination page, which is nowhere related to MRP. Kindly close the task and create a new one.

**Comment by IT-Saravanan** [comment]
Oh, As per your view this dimension combination not related to MRP.

I also thought you will aware this dimension combination related to MRP also.

it is related to MRP also so we cannot Create new git hub.

**Comment by YashwanthGowdaJ** [comment]
This task has been created in the month of Aug. The main purpose of this task is to place dimension combination check in all the MRP pages. This has been moved to live long back. 

And now instead of closing that old task, u keep on loading on the same task (which is not at all related). That means, we have not closed this task from Aug month. Try to understand and create the new tasks and close the same as soon as it completes.

We cannot consider both tasks are same here.

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ If we create a new task for dimension combination, we need to relook this same task only so please close this issue this task itself. we cannot create new task for this.

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan  As this is a new task, need to create a new task. 
Kindly create to take it into further.

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ this is not a new task do it in this task itself or else any error comes take care of users.

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan I am already handling the users. U alone is not handling. FYI

**Comment by IT-Saravanan** [comment]
I know Please take care on future also.

**Comment by YashwanthGowdaJ** [comment]
If u cannot able to handle, definitely I will.

**Comment by IT-Saravanan** [comment]
Okay Handle
