### ISSUE TITLE
Phy Inventory Journal Variance

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#25]
Steps:-
---------
1.User Will Click Calculate inventory and Enter Item.No and click ok
2.Item lines will populate in Phy inventory journal. 
3.User will change the qty in Qty (Phy. Inve) after checking physically from Store.

Scenarios:
--------------
Qty Calculated will be 155.4 for unit cost 120 =18648
Qty (Physical Inventory) will be 100 for unit cost 120 =12000

Difference Amount for Qty(Calc)-Qty (Phys.Inv) =18648 -12000 =6648
Variance will be =Difference amount/18648 
Total Variance % =35 %

Requirement
------------------
Three fields should be added in Physical inventory Journal Page

1.Total Amount of Qty (Calculated).
2.Total Amount of Qty (Physical.Inventory)
3.Difference or Variance % =Qty(Calculated -Qty (Physical Inventory)

**Comment by YashwanthGowdaJ** [comment]
As per the requirement 3 fields were added in bottom of the page(physical inventory journal) as below,
1. Total cost of calculated Qty --> Qty(calculated) * unit cost
2. Total cost of physical Qty  --> Qty(Physical inventory) * unit cost
3. Variance --> ((Total cost of calculated Qty - Total cost of physical Qty)/Total cost of calculated Qty)*100.

If user is creating new record in physical inventory page, then on validation of Qty(Physical inventory) field the above fields gets updated.
For existing records - If user selects the record, then values for that particular record gets updated.

Dear Ram, I have tested from my end. Test from your end and update.

**Comment by ramapandian14** [comment]
I have tested in Phy inventory journal for three fields which has been newly added in bottom of Page.

Total Cost of Qty - Qty (Physical)showing correct as well as variance % also showing correct

Positive Adjustment Entry -> Variance % will be -ve 
Negative Adjustment Entry ->Variance % Will be +ve.

**Comment by ramapandian14** [comment]
As discussed with Veera he has given me additional two points
1.Variance Amount(Navision Stock value -Physical Stock Value) field added in Phy. Inventory Journal.
2.User will create a 100 line of items in Batch & system will show sum of all the values for
Navision Stock value 
Physical Stock Value
Variance Amount
Variance %
