### ISSUE TITLE
Mark Shipped in Sales Order

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#253]
Dear Saravanan / Prabh,
Below explained corrections needed for us to further work on Shipped details to post in Navision Sales order, pls. do the needful and confirm back.

1/ New field needed to update Actual Ex factory date (Shipment Out from factory) as Posting date we will follow document posted date.
2/ Filter by Randa PO needed instead of Planned ship date as too many PO's on same date, difficult to find out.
3/ Location Code flows from sales order, Production location details missing view, Pls. add it and Bin code should have available Prod. locations instead of Location code which flows from Sales order as Production location will be different, but shipping location code would be as Sales order booked as both are different, keeping the entity as same.
4/ Mail pop up to the export team once Shipped posted on the PO's as there is no need for separate mail communications.

**Comment by prabhupdesh** [comment]
@shankar0517 working on this

**Comment by shankar0517** [comment]
Mail template has been created in test and was checked by IT-Saravanan. So have moved the same to live. Mail will be received by Documentation team. Along with it have included "erpsupportmailId" also. At the time of using "Post Shipment" button in Warehouse shipment page the shipment gets posted and then mail will reach to documentation team. Moved to live on 16-09-22.

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan  Given Production location in warehouse shipments in test server. 
Please check & confirm to move live.

**Comment by IT-Saravanan** [comment]
Please Move this functionality to live

**Comment by YashwanthGowdaJ** [comment]
Moved to live
