### ISSUE TITLE
navision to do

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#255]
1.Output journal while selecting the FG no, need to show Belt size 
2.Output journal dashboard Cut, prep, line and pack total need to show based on RPO line wise.
3.Need Belt size in output journal Lines
4.Show belt size in warehouse shipment lines.
5.Discussed packing order to be created from output journal.
6.Need to discuss about carton creation from where
7.To generate Delivery challan without amount while shipping, delivery challan like sales invoice,

**Comment by shankar0517** [comment]
1.&3."Belt size" column has been created as variable in "Output journal" in test. Once the "Item No" is selected in the the "Belt Size" column gets auto populated  from "Sales Line". Have added "Belt Size" column along with Cut,Prep,line columns as per @IT-Saravanan requirement.
2.Cut,Prep,line etc. all these values where flowing based in the "Production Order No". Now these values will get populated based on the "Production Order No" and the selected "Item No". So now on line wise value will flow in these fields. 
4."Belt size" column has been created as variable in "Warehouse Shipment" in test and was checked by @IT-Saravanan and later it has been moved to live.
Kindly Check and let me know in case of any changes. Have discussed with Prabh sir and as of now 5th ,6th & 7th are in hold.

**Comment by prabhupdesh** [comment]
Need clarification for pt. 7

**Comment by prabhupdesh** [comment]
@Abigaiel Enhancing capacity ledger entry screen by adding Item description and factboxes in the right side.
RemoveScrap qty, Direct cost, Overhead cost

Add belt size column

**Comment by Abigaiel** [comment]
@nagalakshmi2022 @IT-Saravanan 
In capacity ledger entry have removed  "Scrap qty" , "Direct cost" , "Overhead cost", "Entry time" column .
In that same page have added "Item description" , "Belt size" column and "Picture" , "Item attributes" factboxes in test server.
please check and confirm.

**Comment by nagalakshmi2022** [comment]
"Item description" , "Belt size", "Picture" , "Item attributes" fact boxes has been added in capacity ledger entries. 
Also removed "Scrap qty" , "Direct cost" , "Overhead cost", "Entry time" column.
Checked and all are ok.
Move to Live.

**Comment by Abigaiel** [comment]
Capacity ledger entry changes are moved to live.
