### ISSUE TITLE
Consumption Journal | fields to be uneditable

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#256]
In consumption journal, make all those fields uneditable which can be populated directly from  job card / sales order selection.
@IT-Saravanan : Please specify those fields here to take this further.

**Comment by prabhupdesh** [comment]
@Abigaiel to take this ahead for tech changes

**Comment by IT-Saravanan** [comment]
In Consumption journal Need Non editable field for Location code, Customer season, Entity. that should flow from Actual released production order. Show all dimension in a fact box.

**Comment by IT-Saravanan** [comment]
If the Released production order no is Starting with RPO and Consumption type is Sample customer season need to auto flow, and Consumption type is consumable location code need to auto flow.

**Comment by Abigaiel** [comment]
@IT-Saravanan 
In consumption journal page, I have added dimension factbox . 
If consumable type is Blank, "Location code" , "Entity" , "Customer season" will auto flow from actual released production order 
If consumable type is Sample, "Customer season" will  auto flow .
If consumable type is Consumable, "Location code" will auto flow.
I have made that auto flow fields as non editable .

**Comment by nagalakshmi2022** [comment]
Consumable type 'Sample' and 'Consumable' is working good.

**Comment by Abigaiel** [comment]
Consumption journal changes are moved to live .
