### ISSUE TITLE
Unit - 44 Belt Navision Journal Entry

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#257]
<html>
<body>
<div class="gE iv gt" style="font-size: 0.875rem; padding: 20px 0px 0px; cursor: auto; color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Bala Suganthi | Bala Suganthi | 12:56 PM (56 minutes ago) |   |  
-- | -- | -- | -- | --
Bala Suganthi
to me, Saravanan, Venugopala | to me, Saravanan, Venugopala
to me, Saravanan, Venugopala

</div><div id=":2vo" style="color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="qQVYZb"></div><div class="utdU2e"></div><div class="lQs8Hd" jsaction="SN3rtf:rcuQ6b" jscontroller="i3Ohde"></div><div class="btm"></div></div><div class="" style="color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="aHl" style="margin-left: -38px;"></div><div id=":2v5" tabindex="-1"></div><div id=":35r" class="ii gt" jslog="20277; u014N:xr6bB; 4:W251bGwsbnVsbCxbXV0." style="direction: ltr; margin: 8px 0px 0px; padding: 0px; position: relative; font-size: 0.875rem;"><div id=":35q" class="a3s aiL " style="font: small / 1.5 Arial, Helvetica, sans-serif; overflow: hidden;"><div dir="ltr">Dear Prabh sir,<div><br></div><div>For 99 Belt Journal entry they are using only four stage Cut / Prep / line / Pack.</div><div><br></div><div>For 44 Belt Navision Journal entry - Nine Stage coming (Lay cut / Strap cut / Size cut / Coloring / Stitching / Embossing / Buckle fixing / Final Inspection / Packed)</div><div><br></div><div>Can you please change the four stage format to 44 Belt journal entry.</div></div></div></div></div>
</body>
</html>

**Comment by prabhupdesh** [comment]
@Abigaiel @nagalakshmi2022 : please take this up

**Comment by prabhupdesh** [comment]
Done changes

**Comment by IT-Saravanan** [comment]
@Abigaiel Please update operation no which you have done.
