### ISSUE TITLE
Allow sales invoice to select multiple location shipment.

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#258]
While creating the sales invoice allow multiple sales shipments lines need to populate and post the invoice.

**Comment by prabhupdesh** [comment]
While doing Get shipment lines in sales invoice, system should allow selection of shipments from all location irrespective of that chosen in the header.

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan I am allowing to select the shipment lines with the location other than header location. Development has done in test server. Please check and confirm.
Table change is involved here.

**Comment by YashwanthGowdaJ** [comment]
Moved this to live as per the confirmation

**Comment by prabhupdesh** [comment]
Working fine
