### ISSUE TITLE
Purchase invoice charge item linking

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#259]
While creating purchase invoice for forwarders users selecting the charge item and assigning the item charge selecting posted sales shipment, While select the sales shipment user need to filter the posted sales invoice external document no,

**Comment by YashwanthGowdaJ** [comment]
So what changes we should do?
Please specify.

**Comment by prabhupdesh** [comment]
While posting sales invoice,

Doc team does "get shipment lines". This updates Shipment no. & shipment line no. in sales invoice line.

While posting the sales invoice, pick external document no. (i.e., export invoice no...ex: TWD-018/22-23) from sales invoice header, using shipment no. & shipment line no. as a reference to sales shipment line,  update external document no. (from sales invoice header) in external document no. field (to be newly created for the purpose) in sales shipment lines

**Comment by prabhupdesh** [comment]
IN nutshell, while posting sales invoice, system has to go back and update sales shipment by external document no. which has been picked from sales invoice header

**Comment by YashwanthGowdaJ** [comment]
Moved to live

**Comment by prabhupdesh** [comment]
Working fine
