### ISSUE TITLE
Logic for Vendor Inv Nos - Reg

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#260]
![image](https://user-images.githubusercontent.com/61455315/194033478-63b7f6d3-31a3-464f-a6be-d172bc8749ca.png)

**Comment by prabhupdesh** [comment]
@Abigaiel  to develop
@nagalakshmi2022  to check

**Comment by Abigaiel** [comment]
@nagalakshmi2022
1. In incoming document, previous financial year Vendor Inv Nos are allowed in current financial year .If that vendor inv no is 
   already in current financial year error will come .
2. Same logic applied in Purchase invoice for Vendor Inv Nos.
3. we have make "Document date " field as mandatory.
4. Development done in Test server please check and confirm.

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ @Abigaiel Working fine please move this to live

**Comment by IT-Saravanan** [comment]
any update ??

**Comment by Abigaiel** [comment]
Logic for vendor inv Nos  functionality moved to live.

**Comment by Abigaiel** [comment]
While posting the purchase invoice there was a standard code to check the external document no, Now we have modified that code to check the financial year of that external document no. Changes are done in 2 codeunits (12,90).

Standard  Code(codeunit 90)

     IF PurchSetup."Ext. Doc. No. Mandatory" OR
        (GenJnlLineExtDocNo <> '')
     THEN BEGIN
  
       VendLedgEntry.RESET;
       VendLedgEntry.SETCURRENTKEY("External Document No.");
       VendLedgEntry.SETRANGE("Document Type",GenJnlLineDocType);
       VendLedgEntry.SETRANGE("External Document No.",GenJnlLineExtDocNo);
       VendLedgEntry.SETRANGE("Vendor No.","Pay-to Vendor No.");
       IF VendLedgEntry.FINDFIRST THEN
         ERROR(
           Text016,
           VendLedgEntry."Document Type",GenJnlLineExtDocNo);
     END;

Modified code(codeunit 90)

     IF PurchSetup."Ext. Doc. No. Mandatory" OR
       (GenJnlLineExtDocNo <> '')
    THEN BEGIN
    //>>Abigaiel-291122-Calculate accounting period-Reviewed by yashwanth
      IF "Document Date" <> 0D THEN BEGIN 
        CLEAR(LRecAccountingPeriod);
        LRecAccountingPeriod.SETRANGE("Starting Date");
        LRecAccountingPeriod.SETRANGE("New Fiscal Year"); 
        LRecAccountingPeriod.SETFILTER("Starting Date",'<=%1',"Document Date");
        LRecAccountingPeriod.SETFILTER("New Fiscal Year",'%1',TRUE);
        FYStartDate := 0D;
        IF LRecAccountingPeriod.FINDLAST THEN 
          FYStartDate := LRecAccountingPeriod."Starting Date";
      END;//<<Abigaiel-291122-Calculate accounting period-Reviewed by yashwanth

      VendLedgEntry.RESET;
      VendLedgEntry.SETCURRENTKEY("External Document No.");
      VendLedgEntry.SETRANGE("Document Type",GenJnlLineDocType);
      VendLedgEntry.SETFILTER("Posting Date",'%1..%2',FYStartDate,CALCDATE('-CM+1Y-1d',"Document Date"));//Abigaiel-291122-Posting date filter-Reviewed by yashwanth
      VendLedgEntry.SETRANGE("External Document No.",GenJnlLineExtDocNo);
      VendLedgEntry.SETRANGE("Vendor No.","Pay-to Vendor No.");
      IF VendLedgEntry.FINDFIRST THEN
        ERROR(
          Text016,
          VendLedgEntry."Document Type",GenJnlLineExtDocNo);
    END;

Standard  Code(codeunit 12)

       PurchSetup.GET;
       IF NOT (PurchSetup."Ext. Doc. No. Mandatory" OR (GenJnlLine."External Document No." <> '')) THEN
         EXIT;


       GenJnlLine.TESTFIELD("External Document No.");
       OldVendLedgEntry.RESET;
       OldVendLedgEntry.SETRANGE("External Document No.",GenJnlLine."External Document No.");
       OldVendLedgEntry.SETRANGE("Document Type",GenJnlLine."Document Type");
       OldVendLedgEntry.SETRANGE("Vendor No.",GenJnlLine."Account No.");
       OldVendLedgEntry.SETRANGE(Reversed,FALSE);
       IF NOT OldVendLedgEntry.ISEMPTY THEN
         ERROR(
           PurchaseAlreadyExistsErr,
            GenJnlLine."Document Type",GenJnlLine."External Document No.");

Modified Code(codeunit 12)

    PurchSetup.GET;
    IF NOT (PurchSetup."Ext. Doc. No. Mandatory" OR (GenJnlLine."External Document No." <> '')) THEN
     EXIT;
    //>>Abigaiel-291122-Calculate accounting period-Reviewed by yashwanth
    IF GenJnlLine."Document Date" <> 0D THEN BEGIN 
      CLEAR(LRecAccountingPeriod);
      LRecAccountingPeriod.SETRANGE("Starting Date");
      LRecAccountingPeriod.SETRANGE("New Fiscal Year"); 
      LRecAccountingPeriod.SETFILTER("Starting Date",'<=%1',GenJnlLine."Document Date");
      LRecAccountingPeriod.SETFILTER("New Fiscal Year",'%1',TRUE);
      FYStartDate := 0D;
      IF LRecAccountingPeriod.FINDLAST THEN 
        FYStartDate := LRecAccountingPeriod."Starting Date";
     END;
     //<<Abigaiel-291122-Calculate accounting period-Reviewed by yashwanth

    GenJnlLine.TESTFIELD("External Document No.");
    OldVendLedgEntry.RESET;
    OldVendLedgEntry.SETRANGE("External Document No.",GenJnlLine."External Document No.");
    OldVendLedgEntry.SETFILTER("Posting Date",'%1..%2',FYStartDate,CALCDATE('-CM+1Y-1d',GenJnlLine."Document 
    Date"));//Abigaiel-291122-Posting date filter-Reviewed by yashwanth
    OldVendLedgEntry.SETRANGE("Document Type",GenJnlLine."Document Type");
    OldVendLedgEntry.SETRANGE("Vendor No.",GenJnlLine."Account No.");
    OldVendLedgEntry.SETRANGE(Reversed,FALSE);
    IF NOT OldVendLedgEntry.ISEMPTY THEN
      ERROR(
        PurchaseAlreadyExistsErr,
        GenJnlLine."Document Type",GenJnlLine."External Document No.");
