### ISSUE TITLE
PF Extract Report Changes

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#264]
IN report PF extract, add 2 columns:
1. P.F.Administration Charges Payable
2. EDLI Payable

For column P.F.Administration Charges Payable, the formula to calculate value will be EPF wages*0.5%

For column  EDLI payable, the formula to calculate value will be =ROUND(IF(J4>=15000,15000*0.5%,J4*0.5%),0)
IF EDLI Wages > = 15000 then
EDLI Payable := 15000*0.5%
else
EDLI Payable  := EDLI wages * 0.5%

**Comment by prabhupdesh** [comment]
@Abigaiel to do

**Comment by Abigaiel** [comment]
In PF extract Report have added 2 columns "P.F.Administration Charges Payable" and "EDLI Payable" . Values for these columns will flow based on given formula. Changes are done in test server.

**Comment by prabhupdesh** [comment]
Add Column ABRY Amount: Value comes directly from processed salary field "ABRY Amount"
Add column Employees Provident Fund Payable:
Formula: 
EPF Contribution (EE Share) Due + EPS Contribution Due+ Diff EPF and EPS Contribution (ER Share) - (ABRY Amount * 2)

**Comment by Abigaiel** [comment]
In PF extract Report have added 2 columns In "ABRY Amount" and "Employees Provident Fund Payable".
Value for ABRY Amount directly flow from "ABRY Amount"  field  in processed salary.
Value for Employees Provident Fund Payable will flow based on given formula .

**Comment by Abigaiel** [comment]
Previously I placed these calculating formula in report layout. Now I have placed formula using coding.

**Comment by prabhupdesh** [comment]
Further to above change, 
a boolean field  to be created in the report called "Post to payment journal".
A selection field for journal template name & journal batch name should also be provided.

If ticked then , system should create payment journal entry in selected batch as per below, ex:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/prabh/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/prabh/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Posting   Date | Document Type | Document No. | Sales Invoice   No. | External   Document No. | Location Code | Party Type | Party Code | T.A.N. No. | Account Type | Account No. | Recipient Bank   Account | Description | TDS Nature of   Deduction | Nature of   Remittance | Act Applicable | Amount | Bal. Account   Type
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
12-09-2022 | Payment | T/VOU47517 |   |   | 44-MAIN |   |   |   | G/L Account | 120200 |   | Employees Provident   Fund Payable |   |   |   | 27,74,855.00 | G/L Account
12-09-2022 | Payment | T/VOU47517 |   |   | 44-MAIN |   |   |   | G/L Account | 121000 |   | P.F.Administration   Charges Payable |   |   |   | 62,432.00 | G/L Account
12-09-2022 | Payment | T/VOU47517 |   |   | 44-MAIN |   |   |   | G/L Account | 120700 |   | EDLI Payable |   |   |   | 28,386.00 | G/L Account
12-09-2022 | Payment | T/VOU47517 |   |   | 44-MAIN |   |   |   | Bank Account | TB06 |   | HDFC Bank Chennai |   |   |   | -28,65,673.00 | G/L Account



</body>

</html>

**Comment by prabhupdesh** [comment]
Along with these journal lines, relevant employee no. and amount will also get updated in linked document.

If account no. = 120200, then employe code gets updated form PF extract and employeewise value showin in column "Employees Provident Fund Payable" in the report to be updated.

If account no. = 121000, then employee code gets updated form PF extract and employeewise value showin in column "PF Admin Charges Payable" in the report to be updated.

If account no. = 120700, then employee code gets updated form PF extract and employeewise value showin in column "EDLI Payable" in the report to be updated.
