### ISSUE TITLE
Warehouse shipment-Show stockout error message

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#266]

**Comment by YashwanthGowdaJ** [comment]
Development done in test server. Confirm moving to live

**Comment by IT-Saravanan** [comment]
Check quantity to ship field, don't check item quantity in shipment page.

**Comment by YashwanthGowdaJ** [comment]
Checking with Qty. to ship field only. I am nit taking from item quantity

**Comment by IT-Saravanan** [comment]
WSHPMT-50542 try to post this shipment in test

**Comment by YashwanthGowdaJ** [comment]
Check now.

**Comment by IT-Saravanan** [comment]
if any error gets shipment should not create but its creating. check

**Comment by YashwanthGowdaJ** [comment]
what error u got?

Right now I have placed only inventory check.

**Comment by IT-Saravanan** [comment]
There is two sales order selected in warehouse shipment one sales order i have selected all dimension and another I didn't selected dimension ,while posting am getting error dimension department not selected, but which i updated all dimension that sales order get posted second sales order not posted.

**Comment by IT-Saravanan** [comment]
Warehouse shipment list page and card page Create fields to show the customer no, customer name Buyer Po, need filter option Customer No, in list page. Hide fields zone code, Sorting method. If customer is different Throw Error.

Check: When I update the external document no its updating all sales order which I selected while posting.

**Comment by Abigaiel** [comment]
@IT-Saravanan 
In Warehouse shipment card page have added "Customer No" and "Customer Name ". Customer No get populated while clicking on the release button. These two field are made non editable .
"Zone code" and "Sorting method" fields have been hidden from the page view.
While selecting multiple sales order if different customers is present in the selected list then system will throw an error. 
In Warehouse shipment list page have added "Customer No" ,"Customer Name " ,"Buyer Po" field.

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ @Abigaiel  Customer No, Name , buyer po & hiding Zone code and sorting method  is working fine in test server please move this to live.

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan we have 2 customer No's.
1. CS Customer
2. Buyer No.

The values for 2 fields differs in sales order. Which customer No. to bring in warehouse shipments?
Clarify to add relevant field in production server.

**Comment by IT-Saravanan** [comment]
Show Buyer No in warehouse shipment.

**Comment by Abigaiel** [comment]
Warehouse shipment changes are moved to live .

**Comment by IT-Saravanan** [comment]
Export invoice no and Ex factory date mandatory only if lines having source document sales order. not applicable for all.

**Comment by Abigaiel** [comment]
please check now.

**Comment by YashwanthGowdaJ** [comment]
**Issue** : While creating the warehouse shipment from sales order, by default external document No. in WH shipment will be updated as sales order's external document No. And users can also select multiple sales orders using "Get source documents" button. 

Now WH shipment contains multiple Buyer PO's but header is updated as single buyer PO which was the 1st sales order's.
So while posting the shipment, there is a standard code that the WH shipment's External Document No. will get updated in all the sales orders selected in WH shipment and also in respective warehouse requests. 

As users can change in sales orders, they used to change in SO and they are not changing in warehouse request. So WH requests will be keep on showing the wrong Buyer PO which was upadted while posting multiple PO's WH shipment.
Mail by Arokia dated 161122.

**Resolution** : As we are allowing users to select multiple PO's in single shipment. we should avoid copying Buyer PO number to WH shipment. If the field is blank, then wrong updation will be avoided.


Changes are done in test server, @IT-Saravanan please check & confirm to move to live.

**Comment by YashwanthGowdaJ** [comment]
Given Preview Posting button in warehouse shipments in test server.
@IT-Saravanan check this preview posting functionality. This should give you errors if any exists and if not exists, then it will not post.

If this works fine, then this same functionality we will move to assigned user ID field, so that if any errors, can be arrested at source itself. Test this functionality thoroughly.

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ Preview posting button working fine in test server.

**Comment by IT-Saravanan** [comment]
completed
