### ISSUE TITLE
Close Button in Sales Order

### ISSUE THREAD

**Issue by shankar0517** [BPS-Industries/Navision#270]
Need to create a button in Sales order which will mark the completely shipped column as 'Yes' and the corresponding lines for the document to be also marked as completely shipped 'Yes'.

**Comment by shankar0517** [comment]
Created the button in test and asked @IT-Saravanan to check.

**Comment by IT-Saravanan** [comment]
Button is working fine in test, move this to live.

**Comment by shankar0517** [comment]
Button is renamed as 'Short Shipped' and moved to live.

**Comment by IT-Saravanan** [comment]
Working fine in live.
