### ISSUE TITLE
output Journal controls

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#271]
1.while posting output journal only tritan entity allowed.
2.if released production entity is BPS Bypass Entity to select Tritan.
3.while posting output journal, selection of  R (Receiving) Bin code only allowed otherwise show error message.

**Comment by Abigaiel** [comment]
@IT-Saravanan 
While posting I have placed an error and from now on it will allow only 'TRITAN' entity.  Selecting only R(Receiving) in Bin Code is allowed, if other bin codes are selected then system will throw an error.
If Released Production order Entity is 'BPS' have bypassed it and have allowed to post using 'TRITAN' entity in Output Journal.
please check and confirm

**Comment by IT-Saravanan** [comment]
Working fine in test server. move this functionality to live. 
Note : change the Error message not allowed to (R- Bin only) only Allowed.

**Comment by IT-Saravanan** [comment]
Throw an error if the output quantity more than released production order line quantity .

**Comment by Abigaiel** [comment]
@IT-Saravanan 
In output journal, while posting  If output quantity more than released production order line quantity then system will throw an error.
Development done in test server. Please check and confirm.

**Comment by IT-Saravanan** [comment]
Development working in test server move this to live.

**Comment by Abigaiel** [comment]
Output journal controls are moved to live.

**Comment by IT-Saravanan** [comment]
Controls working fine in live
