### ISSUE TITLE
Debit Note Report Changes

### ISSUE THREAD

**Issue by Abigaiel** [BPS-Industries/Navision#272]
In Debit Note the company name is flowing as 'BPS Industries' for the following locations (99,14,17,15-18,& 28-29) .Now we have to change the company name to "Tritan Leather Works" for these locations.

**Comment by Abigaiel** [comment]
@IT-Saravanan 
 In Debit Note report  company name have been updated for locations(99,14,17,15-18,28-29). please check and confirm (in test server)  .

**Comment by Abigaiel** [comment]
As per confirmation , debit note report changes are moved to live.

**Comment by IT-Saravanan** [comment]
Working fine in live.
