### ISSUE TITLE
Lights on Nov-Dec'22

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#275]
In fixed asset card:
1. If MIS location in 14,15,17,28,99,11,44M then department should be auto updated as PROD
2. if MIS location is 44PD then department should be auto updated as PD

**Comment by prabhupdesh** [comment]
IN fa card:

if department = 'PD' then MIS location should be 44PD
if department is selected as prod then mis location can only be 14,15,17,28,99,11,44M. System to flash error.

**Comment by Abigaiel** [comment]
In FA card I have placed control to check MIS Location .
If department is selected as PD then mis location should be 44PD & If department is selected as PROD then mis location should be 14,15,17,28,99,11,44M. Otherwise system will throw an error.

**Comment by YashwanthGowdaJ** [comment]
Moved to live

**Comment by prabhupdesh** [comment]
@Abigaiel @IT-Saravanan  In purchase order/purchase invoice/sales order/sales invoice.
Place fields which shows information on created by & approved by, Send for approval date, Approval date

**Comment by prabhupdesh** [comment]
@Abigaiel @IT-Saravanan 
Create a page called "Expense Invoice". This page to be based on purchase invoice and should contain below fields (remove red marked fields and button) from the new page

![image](https://user-images.githubusercontent.com/61455315/204714355-20b285b1-5dfe-4afd-9703-f1ba9f8ade8a.png)

**Comment by prabhupdesh** [comment]
![image](https://user-images.githubusercontent.com/61455315/204714579-4cc1b37a-5257-4741-8abf-11e7b838bee2.png)

**Comment by prabhupdesh** [comment]
![image](https://user-images.githubusercontent.com/61455315/204714719-0ce5947c-a9ca-45bf-90f7-97732fcd32cc.png)

**Comment by IT-Saravanan** [comment]
In FA card While creating child card & New FA card check Entity, Entity only allowed (Tritan & ABPS). 
ABPS Entity Only Allowed if the Mis location = 11
If Mis Details not present in FA Card not allowed to raise any indent and purchase related activities.
In Pd indent User can select only PD Department related FA cards only. Else Through error (Selected Fixed asset card department not PD).

Mis Location and Entity Mismatch ERROR,  Please change the error message. Show error with details.

**Comment by Abigaiel** [comment]
@IT-Saravanan 
Based on Purchase invoice  I have created a new page called "Expense Invoice" as per requirement . Development done in test server.

**Comment by prabhupdesh** [comment]
@Abigaiel @nagalakshmi2022 @IT-Saravanan 
Show customer season field in fixed asset card
Disable Dimensions button
Make division field non editable
Auto populate division on the basis of customer season selected.
These changes to be done while creating fixed asset card as well as child card
show customer season in fact box

**Comment by prabhupdesh** [comment]
![image](https://user-images.githubusercontent.com/61455315/204986497-b60cccf6-8e29-4bf4-9ec5-4d7ffc3e5ea3.png)

If type = fixed asset in the line, then clicking on "Item card" should open fixed asset card
and if type = item, then should open "Item card"

Label of "Item card" should also be changed on the basis of type

@Abigaiel @IT-Saravanan @nagalakshmi2022

**Comment by prabhupdesh** [comment]
![image](https://user-images.githubusercontent.com/61455315/205034925-a7305b70-f6aa-4006-92ff-64113f943edf.png)
@nagalakshmi2022 @Abigaiel 

Please fix this. Open purchase order in this invoice is not working

**Comment by Abigaiel** [comment]
@IT-Saravanan @nagalakshmi2022 
1.While creating new FA card and child card I have placed control to check Entity. Tritan and ABPS entity only allowed to select.
    ABPS only allowed if MIS Location = 11 . Otherwise system will throw an error.
2. Division will flow based on customer season and I have made the division field  non editable.
3. "Customer season" field have added in "Fixed asset card "page and "Create Fixed asset" page.
4. In FA Card "Dimension" button Disabled and "Customer Season " field shown  in factbox.
5. While raising Indent If MIS details not present in Selected FA card , system will throw an error. In PD indent I have placed  error as per your requirement.
development done in test server . please check and confirm.

**Comment by Abigaiel** [comment]
@nagalakshmi2022 
I have fixed  "Open purchase order" button in posted purchase invoice ( in test server). please check and confirm.

**Comment by nagalakshmi2022** [comment]
@Abigaiel @YashwanthGowdaJ 
Purchase Order is opening for all posted purchase invoices which is having receipt no (G/L account, Item & Fixed Asset).
Move this functionality to live.

**Comment by Abigaiel** [comment]
@IT-Saravanan @nagalakshmi2022 
In Purchase Invoice page , The "Item Card" button is already present in the purchase invoice line. Previously it was working only  for item . Now, if type is item , item card will open. if  type is fixed asset, fixed asset card will open.

**Comment by nagalakshmi2022** [comment]
@Abigaiel @YashwanthGowdaJ 
In purchase invoice, Item card button is working fine as per requirement. Move this to live.

**Comment by Abigaiel** [comment]
posted purchase invoice changes & Purchase invoice, "item card" button changes are moved to live.

**Comment by Abigaiel** [comment]
@IT-Saravanan 
In incoming document card page , I have created a button called "Auto create expense invoice". This button will be visible only when the incoming document is in released state and the vendor no.  should be an Expense Payable.
In incoming document list page , have given a button to open expense invoice("Open Expense Invoice").

**Comment by Abigaiel** [comment]
Fixed asset changes and MRP related fixed asset changes  are moved to live.

**Comment by prabhupdesh** [comment]
Journal linked documents - functionality to link documents from general ledger entries

**Comment by nagalakshmi2022** [comment]
@Abigaiel 
1. In job work order, "bin code" is mandatory in Production order component page. Else throw an error msg  while clicking "job work dispatch"

**Comment by nagalakshmi2022** [comment]
@Abigaiel 
Need to add "Export Invoice No" column in warehouse shipment list page.

**Comment by nagalakshmi2022** [comment]
@Abigaiel 
Division should flow from Customer season in sales invoice lines.

**Comment by Abigaiel** [comment]
@IT-Saravanan  @nagalakshmi2022 
In the job work order, while clicking on the "Job work order dispatch" button, I have placed an error to check the "Bin code" value in the production order component. If "Bin code" does not have a value then system will throw an error. development done in test server . please check and confirm.

**Comment by Abigaiel** [comment]
@nagalakshmi2022 
In warehouse shipment list page, have added "Export invoice no" column in live server. please check and confirm.

**Comment by nagalakshmi2022** [comment]
@Abigaiel 
![image](https://user-images.githubusercontent.com/101811185/206379611-75381296-414e-497f-a53d-2e96eb60cb14.png)
Yes.. Export invoice no column has been added.

**Comment by IT-Saravanan** [comment]
Bin code Error in Job work order working fine in test server, move this to live.

**Comment by Abigaiel** [comment]
job work order changes are moved to live.

**Comment by Abigaiel** [comment]
@nagalakshmi2022 
In Sales Invoice, Have added "Division" column in sales invoice lines. Division will flow based on Customer season . development done in test server . please check and confirm.

**Comment by Abigaiel** [comment]
@IT-Saravanan 
In "Sales order", "Sales invoice", "Purchase order", "Purchase invoice" list pages, have added 4 columns. "Created by", "Approved by", "Last approval sent date", "Approved date ". development done in test server. please check and confirm.

**Comment by IT-Saravanan** [comment]
In sales invoice Division flowing from customer season is working fine in test server. move this to live.

**Comment by prabhupdesh** [comment]
> @IT-Saravanan In "Sales order", "Sales invoice", "Purchase order", "Purchase invoice" list pages, have added 4 columns. "Created by", "Approved by", "Last approval sent date", "Approved date ". development done in test server. please check and confirm.

Don't add fields, create as variables

**Comment by Abigaiel** [comment]
@IT-Saravanan @nagalakshmi2022 
In payment journal and journal voucher, If status is not equal to open , then the system will not allowed to modify the record. 
Development done in test server please check and confirm.

**Comment by IT-Saravanan** [comment]
@Abigaiel @YashwanthGowdaJ In payment journal placed control working fine move this to live.

**Comment by Abigaiel** [comment]
payment journal and journal voucher controls are moved to live. I have placed this control in "General Journal ",'Cash Payment Voucher" and "Cash Receipt Voucher".

**Comment by Abigaiel** [comment]
Sales invoice changes  are moved to live (Division auto flow from customer season).

**Comment by Abigaiel** [comment]
we have added "created by," "approved by," "send for approval date," and "approval date" fields in the list page of the sales order, sales invoice, purchase order, and purchase invoice. development moved to live.

**Comment by Abigaiel** [comment]
Journal link document changes are moved to live

**Comment by IT-Saravanan** [comment]
All Task Completed Working fine in Live
