### ISSUE TITLE
Fixed asset Depreciation Calculation and Additional Requirments

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#277]
[St Line Vs Declining Balance.xlsx](https://github.com/BPS-Industries/Navision/files/10163069/St.Line.Vs.Declining.Balance.xlsx)

**Comment by IT-Saravanan** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/IT-SAR~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/IT-SAR~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Add   Field
--
Field Name
Accumulated   Depreciation (Income Tax)
Accumulated   Depreciation (Company Act)
Gross Block
Net Block (   Company's Act)
WDV Applicable   for (Income tax Act)
Depreciation   Start Date
Acquisition   Date
External   Document
Vendor Name
Balance Useful   life



</body>

</html>

**Comment by IT-Saravanan** [comment]
<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/IT-SAR~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/IT-SAR~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Add   Field
--
Field Name
Accumulated   Depreciation (Income Tax)
Accumulated   Depreciation (Company Act)
Gross Block
Net Block (   Company's Act)
WDV Applicable   for (Income tax Act)
Depreciation   Start Date
Acquisition   Date
External   Document
Vendor Name
Balance Useful   life



</body>

</html>

**Comment by IT-Saravanan** [comment]
**Field's To be added in Fixed asset Page**
Accumulated Depreciation (Income Tax)
Accumulated Depreciation (Company Act)
Gross Block
Net Block ( Company's Act)
WDV Applicable for (Income tax Act)
Depreciation Start Date
Acquisition Date
External Document
Vendor Name
Balance Useful life

**Comment by IT-Saravanan** [comment]
Calculation of the Fields
1 Accumulated Depreciation (Income Tax) = Depreciation
2.Accumulated Depreciation (Company Act)=Depreciation
3.Net Block ( Company's Act) =Gross Block +Depreciation
4.WDV Applicable for (Income tax Act) =Gross Block +Depreciation

**Comment by Abigaiel** [comment]
@IT-Saravanan 
Fields have added in Fixed asset Page.
  1.Gross Block
  2.Net Block ( Company's Act) values will flow as per the given calculation.
  3.WDV Applicable for (Income tax Act) values will flow as per the given calculation.
  4.Depreciation Start Date
  5.Acquisition Date
  6.External Document
  7.Vendor Name
development done in test server please check and confirm.

**Comment by IT-Saravanan** [comment]
Move this to live

**Comment by Abigaiel** [comment]
Fixed asset changes are moved to live

**Comment by Abigaiel** [comment]
@IT-Saravanan 
While creating the fixed asset card, "company" and "income tax" lines will be created automatically. If the depreciation book code is "Company" , then  depreciation book method is "straight-line.". If the depreciation book code is "income tax" then  depreciation book method is "declining balance-1" .While sending for  approval, I have placed an error to check that two lines are present, otherwise the system will throw an error. Development done in test server please check and confirm.

**Comment by IT-Saravanan** [comment]
1).While Sending for an approval the fixed asset card, Depreciation book code "company" and "income tax" lines need to be created automatically.

**Comment by Abigaiel** [comment]
@IT-Saravanan 
In fixed asset card page have given 2 buttons called "FA Record Update" and "FA Update History". This functionality is similar to the functionality present in the Employee card (Employee record update and Employee Update history)buttons.
Development done in test server please check and confirm.

**Comment by Abigaiel** [comment]
@IT-Saravanan 
In the fixed asset card , while sending an approval request, "company" and "income tax" lines will be created automatically.
Development done in test server please check and confirm.

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ
FA Update Page working Fine. and depreciation book code its automatically updating. in test server. so move this functionality to live.

**Comment by Abigaiel** [comment]
@IT-Saravanan 
In the fixed asset card , have added the field " Balance Useful Life " . Values will flow as per the given calculation. Development done in test server please check and confirm.

**Comment by Abigaiel** [comment]
@nagalakshmi2022 
While creating a fixed asset, if the fa category is Tools and dies, then actual seasons are allowed. Otherwise, the system will throw an error. Development done in test server please check and confirm.

**Comment by Abigaiel** [comment]
FA Record Update functionality moved to live .

**Comment by Abigaiel** [comment]
FA card changes are moved to live.

**Comment by YashwanthGowdaJ** [comment]
While sending any FA to an approval, if Depreciation Book Code is INCOMETAX and Depreciation method is Straight Line, then we are updating Depreciation method as Declining Balance-1 and then sending for an approval.

This change has been done in live.
