### ISSUE TITLE
Dec'22 Tools & Dies Expensed-Showing value in blank division

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#283]
IN tools & Dies expensed MIS parameters to flow from related cutting die fixed asset card.
Ideally, cutting die cannot be in support division.
So, in case customer season/division from fixed asset card is  all season/support division check purchase invoice for actual division/customer season.

Other changes required is:

In fixed asset card, for cutting dies, only actual season can be selected
Must be sent for approval
No approval without specifying MIS parameters

**Comment by prabhupdesh** [comment]
Also check for values lying in support division

**Comment by nagalakshmi2022** [comment]
MIS parameters flowing for Tools &  Dies Expensed..
