### ISSUE TITLE
Show "Tritan" in Item sticker

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#29]
Show "Tritan" in bottom left in Item stickers

**Comment by prabhupdesh** [comment]
Yashwanth/Ram, Once completed inform kanika

**Comment by YashwanthGowdaJ** [comment]
Ram, I have included "Tritan" in bottom left of the sticker. Once check and update to Kanika

**Comment by YashwanthGowdaJ** [comment]
[50086 Rep Story Board Sticker.txt](https://github.com/BPS-Industries/Navision/files/4285445/50086.Rep.Story.Board.Sticker.txt)

**Comment by ramapandian14** [comment]
TRITAN will be in capital format
Done sir
We have Checked and updated to kanika also..
