### ISSUE TITLE
Lights on 2023

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#294]
In Incoming document, After creating the expense invoice document no and document type is not updating in incoming document page and open purchase invoice button too.

**Comment by Abigaiel** [comment]
@IT-Saravanan 
Have populated the document no and and document type in incoming document  . development done in test server.

**Comment by IT-Saravanan** [comment]
Functionality working fine in test server, @YashwanthGowdaJ move this to live.

**Comment by IT-Saravanan** [comment]
Fixed asset if depreciation code for Income tax update declining balance1

**Comment by Abigaiel** [comment]
In Approval entries page , "Record" button is not working for expense invoice. Have now fixed this issue and from now "Record" button will also work for Expense Invoice Page.

**Comment by IT-Saravanan** [comment]
In customer season transfer page except tritan AS not allowed direct posting 
Page Nos: 393 & 33010120.

**Comment by Abigaiel** [comment]
@IT-Saravanan 
In Customer season transfer, while posting have placed an error to check  whether the customer season is "Tritan AS" or not . if it is not "Tritan AS"  system will not allow it  to post. development done in test server please check and confirm.

**Comment by Abigaiel** [comment]
@IT-Saravanan 
In the vendor card, I have created a button called "Create Jobwork Location". It will create the job work location and inventory posting setup by clicking this button. Development  done in test server. please check and confirm.

**Comment by IT-Saravanan** [comment]
Vendor card, Creation of job work location and Inventory posting setup was working fine in test server. @YashwanthGowdaJ move this to live.

**Comment by Abigaiel** [comment]
"Create job work location" button moved to live.

**Comment by IT-Saravanan** [comment]
While adding Fixed asset in purchase order Populate quantity from Set of in fixed asset card.

**Comment by IT-Saravanan** [comment]
Create Button in Item card page called generate UOM, While clicking on this button the item unit of measure will create automatically. Table no 5404.

**Comment by Abigaiel** [comment]
@IT-Saravanan 
In Item card page , I have given  a button called "Generate UOM"  as per the requirement. development done in test server . please check and confirm.

**Comment by prabhupdesh** [comment]
Please don't club multiple lights on issues inside one github id. Create separate github id for each issue. If it is a lights on then mark under lights on project
