### ISSUE TITLE
Stock Thread Issue

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#296]

**Comment by prabhupdesh** [comment]
![image](https://user-images.githubusercontent.com/61455315/216305130-8eb088ee-c31b-4f4e-b0f0-112b503f6cd4.png)

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan 

What to do here?
No description

**Comment by prabhupdesh** [comment]
As per in above screen shot, user will select actual job card id/ item no. in consumption journal, and then use a new button called "Select Thread" .

On clicking "select thread", item list will open filtered by TKT no. (TKT no is stored in item group), & select relevant thread id.
