### ISSUE TITLE
Local Sales Item Creation and Production Order

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#297]
In item card FGD Creation for local sales to be simplified. 
Give the button in item Card called Create Local Sales Production Order.
While clicking the button Released production order should create. 
In that Released production order
No, source No, Line Item no will be item no
Location and production at to be 44-Main
Customer Season will be Latest Local Sales customer season mentioned below.
For Bag 23-TRT-ALL-ALL-LS  
For Belt 23-TRT-ALL-MB-LS
For Wallet 23-TRT-ALL-MW-LS

Status Should be Released, there is no approval (Auto release)

**Comment by Abigaiel** [comment]
@IT-Saravanan 
In the item card page, I have created the button called "Create LS Production Order" as per the requirement. Development done in test server please check and confirm.

**Comment by IT-Saravanan** [comment]
This button working fine in test server @YashwanthGowdaJ review the code ASAP. move this to live.

**Comment by Abigaiel** [comment]
"Create LS Production Order" button moved to live.
