### ISSUE TITLE
Creating Purchase Order from Fixed Asset

### ISSUE THREAD

**Issue by YashwanthGowdaJ** [BPS-Industries/Navision#298]
Give a button in fixed assets page, on clicking purchase order should be created for that asset.
Derive all the parameters from fixed asset.

**Comment by Abigaiel** [comment]
@IT-Saravanan 
I have created a button called "Create Purchase Order" in fixed asset card page. Development done in test server. Please check and confirm.

**Comment by IT-Saravanan** [comment]
@Abigaiel Purchase order creating from fixed asset, what is the concept? for which basis this functionality was developed. please explain.

**Comment by YashwanthGowdaJ** [comment]
No need to raise MRP for the fixed assets(Now I am going to block MRP for fixed assets). 
All the FAs POs should be created from this new button.
MRP should be raised only for the raw materials which are being ordered against Buyer PO and also for PD.
