### ISSUE TITLE
Automatic updation of Location code for Employee loan

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#30]
While Posting Employee loan from HR Location code is not updating in G/L Entries

**Comment by YashwanthGowdaJ** [comment]
While posting the employee loan, G/L entries will be updated with physical location of the respective employee.
[Page 33010218 Employee Loan.txt](https://github.com/BPS-Industries/Navision/files/4285514/Page.33010218.Employee.Loan.txt)
