### ISSUE TITLE
Sample order Not required Positive Adjustment

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#306]
In Sample order Not required positive Adjustment for If the Sample order No Series LS-ORD-T

**Comment by Abigaiel** [comment]
@IT-Saravanan 
In Sample order, Positive adjustment functionality will not work for local sales items. development done in live server . please check and confirm.

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ @Abigaiel Please find the attachment and modify the existing report based on Request page option selection.
[20230405102531.pdf](https://github.com/BPS-Industries/Navision/files/11155341/20230405102531.pdf)

**Comment by Abigaiel** [comment]
@IT-Saravanan 
Report has been modified as per requirement(Delivery Challan) . development done in test server. please check and confirm.

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ in test its working fine move this to live.

**Comment by YashwanthGowdaJ** [comment]
Moved to live

**Comment by IT-Saravanan** [comment]
@YashwanthGowdaJ If Customer Id is B2CFG-INR-IN-15-1 allow to enter Edit Address field. like TRT customer card.

**Comment by Abigaiel** [comment]
@IT-Saravanan 
In the sample order page, if the CS Customer  is B2CFG-INR-IN-15-1 or B2CFG-INR-IN-16-2, the system will allow you to edit the address fields. Development done in test server . please check and confirm.

**Comment by IT-Saravanan** [comment]
Development Working fine in test server move this to live

**Comment by Abigaiel** [comment]
Sample order changes are moved to live.

**Comment by IT-Saravanan** [comment]
Working fine in live
