### ISSUE TITLE
GRN & Issue date restricted to creation date

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#309]
As discussed, following control will be placed for all GRNs and issue entries  from April'23 & onwards.  Please note that this change will not affect march month entries and can be done the way they are being done.

All GRNs & issues will be allowed only on "creation date", which means, for example: on 5th Apr '23, system will not allow any entry with prior posting date. "Posting date" will be defaulted to 5th April'23 only.

@YashwanthGowdaJ @IT-Saravanan Control to be placed while posting any GRN or consumption journal

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan 
I have placed a control in warehouse receipts & consumption journal that all the postings from 1st april should be posted on the creation date. That means posting date should be defaulted to today's date. Development done in live server.
Please check & confirm.

**Comment by IT-Saravanan** [comment]
Working fine this functionality in live
