### ISSUE TITLE
Job card Components list report in sales order 

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#31]
Issue
------------------
In report user will select all FGP lines ->Click Job order components list for Wallets
Qty is summing for 2 FGP(100+100)=200
Qty is summing up for 3 FGP(100+100+100)=300

Wallets
------------------
For Wallet Case using Get Block order lines  user will select multiple block order lines in sales order.
FGP1 -100
FGP2-100
FGP3 -100

While taking print out it showing in these format
Qty for 1 FGP           =100
Qty is summing for 2 FGP(100+100)=200
Qty is summing up for 3 FGP(100+100+100)=300

Correct Output
------------------------
FGP1 Qty -100
FGP2 Qty -100
FGP3 Qty -300

**Comment by YashwanthGowdaJ** [comment]
I have included a condition in such a way that, if sales order is for Belt, then add the quantity based on size, or else take individual quantities of production order. 

Ram test this case.

[Rep 50034 Job card comp list 040320.txt](https://github.com/BPS-Industries/Navision/files/4285706/Rep.50034.Job.card.comp.list.040320.txt)

**Comment by ramapandian14** [comment]
Done
