### ISSUE TITLE
Fixed asset Edit entity

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#311]
Attached sheet mentioned fixed asset modify entity as BPS

**Comment by Abigaiel** [comment]
[
[Fixed Asset Entity Updation .xlsx](https://github.com/BPS-Industries/Navision/files/11201363/Fixed.Asset.Entity.Updation.xlsx)
](url)

**Comment by Abigaiel** [comment]
@IT-Saravanan 
Updated

**Comment by IT-Saravanan** [comment]
completed
