### ISSUE TITLE
Location code mandatory while posting

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#32]
Specifying Location should is mandatory while posting.
First need to check below areas if location is flowing to GL entries:

Location code should be mandatory in below documents and should flow to GL entry:

1. Posting Purchase invoice
2. Posting payment by applying to invoice from payment journal. Location code should auto flow to GL entry
3. Posting any journal entry (Location code should be mandatory)
4. Posting sales invoice
5. Posting prepayment
6. Posting location transfers

**Comment by IT-Saravanan** [comment]
* As per Mentioned above task (Location Code has been mandatory while posting ) and Moved to live
