### ISSUE TITLE
 Auto release for Warehouse BOM

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#34]

**Comment by YashwanthGowdaJ** [comment]
I have given a button "Release" in warehouse BOM masters. This button will help them to release Warehouse BOM masters.

**Comment by YashwanthGowdaJ** [comment]
And also I have written a condition on "send approval request" button, 

If type of BOM is "Warehouse Master" then no need to send an approval

**Comment by ramapandian14** [comment]
No Need of Placing Separate Release Button..
You need to Place control  by 
Click ->Approvals
Approvals -> Release in Warehouse BOM Master..

**Comment by YashwanthGowdaJ** [comment]
Placed code in already existing Release button.

**Comment by ramapandian14** [comment]
Completed..

**Comment by YashwanthGowdaJ** [comment]
We have forgotten to place same condition in versions which I have taken care now. This issue was raised by Venkatesh.
