### ISSUE TITLE
Item Creation For FGD TO FGD With Different Color Code 

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#36]
Same Item Creation For Existing FGD Item Card With Different Color Code

**Comment by IT-Saravanan** [comment]
As per the Requirement is copy of the Existing FGD item card  to create another FGD item card same BOM With Different Color Code and Customer Season. checked in the Test the FGD 
Card is Created in the same BOM With Different Color Code. 
Requirement is from Kanika.

*But the creating item for different customer season working on that

**Comment by prabhupdesh** [comment]
Copy from existing item in "create item cannot be used because this functionality only allows to copy from papa card and also does not copy bom

**Comment by prabhupdesh** [comment]
So using FGD to FGP logic in BOM screen

**Comment by prabhupdesh** [comment]
While creating a FGD card from existing FGD card, all the BOM items must be auto added in relevant destination customer  season. 

Make a codeunit called, "FGD-FGP-BOM functionality"

Technically, create a new function called " Auto add to customer season" in above codeunt
Also see, if we can auto add item in price master with approved & latest price auto updated.

**Comment by YashwanthGowdaJ** [comment]
I have created a new codeunit as suggested above, and added a new function "Auto add to customer season" to add items into destination customer season.

Working on updating price

**Comment by YashwanthGowdaJ** [comment]
As Item number remains same, only customer season is changing, no need to user populate ICL report(which is used while populating price manually). Just need to copy Item cost lines from souce customer season to destination customer season because all the parameters remains same

**Comment by IT-Saravanan** [comment]
Copy of the Existing FGD item card to create another FGD item card same BOM With Different  Customer Season. checked in the Test the FGD Card is Created in the same BOM With Different  Customer Season and While creating the New Item with different CS the RM items is automatically updated the new customer season.

Working on updating price

**Comment by prabhupdesh** [comment]
Please update

**Comment by YashwanthGowdaJ** [comment]
We have left this in middle. Need to work on this..
