### ISSUE TITLE
Unit cost field in purchase order should be made as non editable 

### ISSUE THREAD

**Issue by YashwanthGowdaJ** [BPS-Industries/Navision#37]
We have to make direct unit cost field in purchase order as non editable for items. As soon as they enter quantity, the price will automatically picked from price master based on customer season, starting date, item No, price basis

**Comment by YashwanthGowdaJ** [comment]
Made direct unit cost and Line amount fields as non editable in purchase order subform. Ram/Saravanan, kindly test..

**Comment by IT-Saravanan** [comment]
Purchase Order Direct Unit Cost & Line amount Fields now updated as Non Editable 

* one more requirement We have to Add one button Called Update the Unit cost in the Item for the Selected Line in Purchase order

**Comment by IT-Saravanan** [comment]
Yashwanth kindly check, while creating the new purchase order again the direct unit cost field goes to editable, make it non editable.

**Comment by YashwanthGowdaJ** [comment]
Added a button in purchase order. This button will simply validate the Item No & quantity for the selected line. Because the code for updation of price is written under on validation of item No & quantity....

**Comment by YashwanthGowdaJ** [comment]
Kindly test & close the task..

**Comment by YashwanthGowdaJ** [comment]
If item product group is 'PU' then direct unit cost field is made editable.

**Comment by ramapandian14** [comment]
Unit Cost is Editable for PU Items

**Comment by ramapandian14** [comment]
If item product group is 'CB' then direct unit cost field is made editable only for Housekeeping Items
Under Product group CB 
Item Group will HK

**Comment by YashwanthGowdaJ** [comment]
Reverted back.

Now for PU items, direct unit cost field is uneditable

**Comment by YashwanthGowdaJ** [comment]
For autoupdate price in purchase line from price master, in function "FindPurchPriceCS" under codeunit 7010, while filtering customer season from DimVal table, included 1 more filter on business classification of customer season.

**Comment by YashwanthGowdaJ** [comment]
"Update Price" button is renamed as "Refresh Price"

**Comment by prabhupdesh** [comment]
Direct unit cost is editable in purchase order only for consumables
