### ISSUE TITLE
GRN/Invoicing Status Report

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#39]
Need reports for materials, where:

1. Gate entry done but GRN not done
2. GRN done but Invoice not created
3.Invoice created but not posted
4. GRN done but invoice not posted

Show incomign document no. in all the reports.

**Comment by Santhosh-r15** [comment]
1. Gate Entry done GRN not Done (33010241) report completed in the test server.

**Comment by IT-Saravanan** [comment]
IN-RCPT-0120035

**Comment by IT-Saravanan** [comment]
**Gate Entry done But GRN Not Done Report**
Added for front end in the test server  To take this report - Departments/Warehouse/Gate Entry/Reports/Gate entry Done GRN not Done, to check whatever the date and gate entry no wise,

**Comment by Santhosh-r15** [comment]
2. GRN done but Inv not created (33010242) report is completed in test server,

Filter to be added is 'Order date'.

**Comment by IT-Saravanan** [comment]
GRN Done Inv Not Created 
Added for front end in the test server To take this report - Departments/Warehouse/Gate Entry/Reports/GRN Done Inv Not Created ,to check Filter date wise or  P.O no wise.
Checked on 01.01.2020 to 29.02.2020

**Comment by Santhosh-r15** [comment]
1.Gate entry done but GRN not done
2.GRN done but Invoice not created
3.Invoice created but not posted 
All three are combined in a single report (33010241), which displays GRN status, GRN Recipt NO, GRN Posting date, Invoice Status, Invoice Posting Status.

Added to the Front End in the name "GRN & Invoice Status Report".

**Comment by Santhosh-r15** [comment]
IN-RCPT-0119094

**Comment by prabhupdesh** [comment]
Gate   Entry No | Gate   Entry Date | Item   No | Item   Description | From   Vendor No. | From   vendor name | External   Document NO. | UOM | Received   Quantity | Status | GRN   Posting Date | Invoice   Posting date


Column sequence
