### ISSUE TITLE
Vendor Shipment/Link Mandatory for Warehouse receipts

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#40]
Purchase Team will create a warehouse receipts and attach the Purchase Order via Get Source Documents.
Vendor Shipment.No & Link should be mandatory Before assigning the user ID in Whse Receipts.

**Comment by YashwanthGowdaJ** [comment]
I have made vendor shipment No. & link as mandatory while selecting user ID in warehouse receipts.

Technically I have written code under "On validate" trigger of user ID field.
[Page warehouse receipt as on 100320.txt](https://github.com/BPS-
Industries/Navision/files/4310752/Page.warehouse.receipt.as.on.100320.txt)

Ram, kindly check from your end too.

**Comment by YashwanthGowdaJ** [comment]
Additional requirement..

Automatically notes needs to be added with created user ID.

**Comment by YashwanthGowdaJ** [comment]
Ram I have added notes in warehouse receipt page with user ID. Kindly check...

**Comment by prabhupdesh** [comment]
Please suggest

**Comment by YashwanthGowdaJ** [comment]
This is completed. It is in live
