### ISSUE TITLE
Physical inventory Journal 

### ISSUE THREAD

**Issue by YashwanthGowdaJ** [BPS-Industries/Navision#44]
Batch job is written to copy phy. inventory data from 1 batch to other batch. 

Currently data copied from 'CB' batch to 'SARAVANAN' batch.

**Comment by IT-Saravanan** [comment]
For Physical Inventory Journal breaking, the activity is completed. Some items we could not break because the items in current stock is not equal to calculated stock 
Please find the list of items along with the batch name where inventory is not matching
[Physicak Stock  Journal unupdated Items.xlsx](https://github.com/BPS-Industries/Navision/files/4332384/Physicak.Stock.Journal.unupdated.Items.xlsx)

**Comment by IT-Saravanan** [comment]
Created  (To Approve Batch)
For Physical Inventory Journal breaking, Now What are the items Lying in the SAR Batch All the Breaked items Moved To (To Approve Batch)

**Comment by IT-Saravanan** [comment]
In Test Server Created New Report for Physical Inventory Journal (To Approve) Batch, Report Name Called Phys Invt Stock Value. that report shows Whatever the stock lying in the to approve batch.

**Comment by IT-Saravanan** [comment]
From Sar Batch  Items Qty Calculated  Column 0, But Phy Stock > 0 that items moved to To approve Batch

**Comment by IT-Saravanan** [comment]
[Physical journal.xlsx](https://github.com/BPS-Industries/Navision/files/5093908/Physical.journal.xlsx)

Add a button in physical inventory Journal, if i click the button the difference Qty flown from selected Batch to To Approve Batch and Posting Batch

**Comment by IT-Saravanan** [comment]
44 Main Location - Physical Inventory Journal Breaking has been done for Below Mentioned Batch.
1. Webbing                  -      WE
2. Sack Bag                  -      PK-DB
3. Tag                           -      PK-TG
4. Fixed Length Zip      -      ZF
5. Chemical                  -      CH 
6. L                               -      LB
7. Leather                     -      LE
8. Poly Bag                    -      PK-PB / PM-PB
9. Consumable              -      CB
10. Slider                      -      ZS 
11. Thread                    -      TH

**Comment by IT-Saravanan** [comment]
99 Main Location - Physical Inventory Journal Breaking has been done for Below Mentioned Batch.

1.	Belly Band      - PK-BB
2.	Bungee Fixed Length - PK-BL
3.	Box	- PK-BX
4.	Dust Bag	- PK-DB
5.	Hanger	- PK-HA
6.	HEADER	- PK-HE
7.	ID Card	- PK-IC
8.	Polybag	- PK-PB
9.	Sticker	- PK-ST
10.	Tag	- PK-TG
11.	Tray	- PK-TY
12.	Tin	- PK-TI
13.	Carton	- PM-CA
14.	Other Packing Materials	- PM-OT
15.	Alarm	- PK-AL
16.	Polybag	- PK-PB
17.	Adhesive	- AD
18.	Chemical used in prod	- AC
19.	Consumables	- CB
20.	Other Visible Materials	- OV

**Comment by IT-Saravanan** [comment]
Requirements
1. Need Option for Multi-selection For Sending Approval.
2.Recent customer Season need to update the Physical Stock  (Based on Dimension Set ID)

**Comment by IT-Saravanan** [comment]
Steps For Physical Inventory Journal
Step 1: Open Physical inventory Journal Page
Step 2: In Home Tab there is button Calculate Inventory  Click after
Step 3:Update date, Doc No: & Update item No. Click Ok
Step 4: Items will Generate on that Page
Step 5: Go to Navigate tab, Here button called Copy Difference click and select Which batch u want it will flow difference for all item for Your selected Batch. after
Step 6: In Navigate tab here one button break after clicking the button system will break based on all item entity, Location,Bin,customer Season.
