### ISSUE TITLE
Purchase Order Price Population

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#48]
Item no -> Vendor No in Item Card.
Vendor Card ->Linked Vendor
Vendor Group

Based on Below Parameters I have updated price in Vendor A 
In Purchase Order price should populate based on above parameters through linking of vendor.

**Comment by YashwanthGowdaJ** [comment]
I have given button in purchase order subform called "Select diff Vendor(To update price)". This button will open vendor list page(filtering records on Linked Vendors & vendor group). On selecting the vendor in which they have updated price, direct unit cost & Line amount will get populated corresponding to the item No & selected vendor No.

Technically I have rewritten existing functions to a new function and passing one additional parameter "Vendor No" which holds the selected vendor. And also I am validating line amount to get updated.

**Comment by ramapandian14** [comment]
Completed
