### ISSUE TITLE
Reclassification of Entity in Stock Items

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#51]
All the Stock Items is lying the Entity MEPZ | DTA to Reclassification to BPS Entity

**Comment by IT-Saravanan** [comment]
2000 Items entity transferred in test Server

**Comment by prabhupdesh** [comment]
Saravanan, Please again evaluate the stock lying in these entities

**Comment by IT-Saravanan** [comment]
200 Items entity transfer done

**Comment by IT-Saravanan** [comment]
600 items entity transfer done

**Comment by IT-Saravanan** [comment]
500 Items Entity transfer done

**Comment by IT-Saravanan** [comment]
250 Items Entity Transfer done

**Comment by IT-Saravanan** [comment]
Entity Transfer done, But Foptll items not done, and Remaining 35 items is there
