### ISSUE TITLE
Image guide and Portal entry report for selected lines in block orders

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#52]

**Comment by YashwanthGowdaJ** [comment]
Need to print Image guide and Portal entry report for the selected lines in block orders. Previosly we have given same functionality in needs form. Now kanchana is asking the same functionality in these 2 reports

**Comment by YashwanthGowdaJ** [comment]
I have given a option to select ( selected lines or all the lines) the lines in block orders. Based on the selected lines, they can generate report. Changes are done on block order page, image guide report and Portal PO entry image report. 

Waiting for response from kanchana to close the issue.

**Comment by YashwanthGowdaJ** [comment]
Confirmed from kanchana.
