### ISSUE TITLE
Populate price in PO from papa card

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#54]
For below mentioned product groups:

Labels - LB
Needle - NE
Stickers - PK-ST
PU 
Hanger - PK-HA
Thread - TH

Price should get populated in purchase order from papa card.
Requested by Ghouse.

**Comment by YashwanthGowdaJ** [comment]
I have placed a code to fetch price from Papa card for above mentioned product groups. Changes are done in Codeunit 7010.
