### ISSUE TITLE
Adding the Items in Customer Season 

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#55]
Tritan AS :-
1.Customer Season type will be Non AS,Tritan AS
2.All Customer,Brand,Dept,Seasons

Brand AS(19-CRG-CRG-ALL-AS)
1.Customer Season type will be Brand AS,Non AS
2.Customer -CRG
3.Brand      - CRG
4.Dept       -Any
5.Seas       -Any

Cust AS(20-RAND-ALL-ALL-AS)
Customer Season season type will be Cust AS
1.Customer  -RAND
2.Brand- Any
3.Dept-Any
4.Sea  -Any

NonAS/DEpt AS i will update

**Comment by prabhupdesh** [comment]
Ram, Please suggest

**Comment by ramapandian14** [comment]
User Can add the items in Customer Season.
they can click ->send for approval.
