### ISSUE TITLE
Warehouse change in PO

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#60]
Due to pandemic time , warehouse for lots of FG has changed. So, instead of creating new FGs for every new warehouse change, revised warehouse will be changed in sales order lines itself (there is a warehouse column in sales order lines). Any material changes in relevant job card will be changed as per requirement.
To facilitate these changes, revised warehouse needs to be shown in below reports:
Image guide
Job card components
Material Requisition
Needs form
Production status report

Auto comments in Sales Order
In case of any change in sales order, system should be able to auto insert the changes in notes section like we have in Item card.

**Comment by prabhupdesh** [comment]
If warehouse is specified in sales line then revised warehouse will be picked be picked from sales line else from item card attributes

**Comment by prabhupdesh** [comment]
Ref. above point "If warehouse is specified in sales line then revised warehouse will be picked be picked from sales line else from item card attributes": 

there is a change as per below:

In all cases warehouse will be picked from sales line. If warehouse is blank in sales line then pick blank

**Comment by prabhupdesh** [comment]
Yashwanth,Ram, Saravanan, please suggest if this done

**Comment by ramapandian14** [comment]
Moved to Live.
