### ISSUE TITLE
Changing customer season in Item card and Item attributes

### ISSUE THREAD

**Issue by YashwanthGowdaJ** [BPS-Industries/Navision#61]
1. New Button should be created and named as Change Customer Season.
2. Customer season list Page will open  
3. User will select a customer season to update in Item Card.
4. Multiple selection is allowed in list page.

Change in customer season should be allowed based on below conditions.
1. Only if item is FGD
2. BOM should be empty
3. Sales Order should not be created with that item
4. Status of item card should be open
5. Only approved customer seasons should be selected by the user
6. Notes should be taken care.

**Comment by prabhupdesh** [comment]
Adding: There should not be any transaction done using that item, only then customer season changing is allowed
