### ISSUE TITLE
Loan carry forward

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#62]
All loans falling due in may month for all workers/staff needs to be carried forward by one month. Please do the respective change in monthly attendance and update.

**Comment by YashwanthGowdaJ** [comment]
I have made changes in monthly attendance page to carry forward all the May month's loan to the end of loan period + 1M. (including covid loan).

I have made changes in such a way that on clicking on loan carry forward button for a particular company, it will works for all the employees in that company. 

The loan is getting carry forwarded without checking for negative amount boolean field in monthly attendance. In other words, whatever the condition may be, all the loans of may month will be getting forwarded.

Both Saravana and Ram are tested, and it is working fine according to them.
