### ISSUE TITLE
PK-ST change

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#63]
Add a boolean field called "Add reference code to description". On clicking, reference code should get added in the child card description

![image](https://user-images.githubusercontent.com/61489309/83872862-690e7980-a750-11ea-95c2-e13bc22cfe21.png)
If no. of characters not allowed then should give error

**Comment by IT-Saravanan** [comment]
Added a Boolean field in the vattributes, On clicking the boolean field reference code added in the child card description,

Tested and Created item in the test server, ITEM No : PK-ST-BX-20-7-1, PK-ST-BX-20-10-1, PK-ST-BX-20-8-1,PK-ST-BX-20-13-1,PK-ST-BX-20-19-1,PK-ST-BX-20-14-1

**Comment by IT-Saravanan** [comment]
I have tested in Live
 My test scenario for Item card.No:-PK-ST-BX-20-6-1

Reference code is adding to child card description..

**Comment by YashwanthGowdaJ** [comment]
As saravana has commented, it is working fine, I am closing this task
