### ISSUE TITLE
Material Requirement Planning

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#64]
Need to develop "Needs form" report from Customer SO Buffer

**Comment by prabhupdesh** [comment]
Process:

Upload:

1. Upload VDF
2. Upload from Customer SO Buffer
3. Upload from Block Order
4. Upload from Sales Order

Confirm:
Once uploaded, uploader department will confirm the entries, which then shows in purchase department screen. Uploader department will also trigger a mail for purchase department

Accept:

Purchase department will receive a mail, and accept entries.

Create purchase order:

Once entries accepted, purchase department will create purchase orders

Base document modification:

There is a possibility that FG quantity in base documents (VDF,CSO Buffer,BO,SO) may change due to buyer request.  In that case, uploader department will recalculate  (an option given in MRP screen). User will select the line in MRP  containing requisite FG no., Buyer PO no. and recalculate.

This populates the relevant lines in MRP.


References which flows from various source documents till purchase order:

1. VDF: Table : Production forecast entry: Ref. Fields: Production forecast Name, Entry No.
2. Customer SO Buffer: Table: Customer SO Buffer, Ref. Fields: Upload set#, Line no.
3. Block Order: Table: Sales Line, Ref. Fields: Document no., Line no.
4. Sales Order: Table: Sales Line, Ref. Fields: Document no., Line no.

**Comment by prabhupdesh** [comment]
1. Once base documents (VDF, CSO Buffer, Block Order, Sales Order) is uploaded, then same document cannot be reuploaded.
2. In case, there is any change in base document, then a button called "recalculate" should be used which allows populating requisition lines again for same document no. reference

**Comment by prabhupdesh** [comment]
Deletion  related controls to be updated by saravanan. Developed by yashwanth.

**Comment by IT-Saravanan** [comment]
S.No	-MRP Scenario Tested Cases	     					                                       -Result	-Remarks

1	DEMANDED BY Flowing till Pur Order 		  				                                 -   Yes	-SO, CSO, VDF

2	Demanded Ref No Flowing Till Pur 						                                 -   Yes	-SO, CSO, VDF

3	Sales order Line No Flowing Till Pur Ord					                                 -   Yes	-SO,BO, CSO, VDF

4	Sales Order No  Flowing till Pur Ord						                                 -    Yes	-SO,BO, CSO, VDF

5	Indent Type  flowing till Pur Ord						                                        -     Yes	-SO,BO, CSO, VDF

6	Sub Indent Type  Flowing till Pur Ord						                                -      Yes	-SO, BO, CSO, VDF

7	Qty Base Value Match With Needs Form					                                   -    Yes	-QTY BASE (Pur UOM) 
-
8	Modification is allow in MRP	         					                                         -      Yes	
	
9	Deletion is Happen in MRP Page after Creating The Pur Ord	                                  -      No	

10	Deletion is allow after Confirm 						                                          -       No
	
11	once uploaded Same (SO,BO,CSO,VDF) System allow is generating lines Again 	           -      No	

12	System Recalculate and Generate items After Adding Items in Block Order                   -	Yes	

13	System Recalculate and Generate items After Adding Items in Sales Order                  -     Yes	

14	System Allow to Add items in Existing Pur Ord					                             -  Yes	-Only One Line Possible

15	System Allow to Edit Qty in Sales order and Block Order 			                      -          No	

16	System Allow To Insert Item in Sales Order and Block Order			                           -     Yes	

17	In Sales  Order With Diff FG Item System Allows to Generate MRP Lines		           -   Yes	
-
18	In Block Order With Diff FG Item System Allows to Generate MRP Lines		           -    Yes	

19	If Revised the BO Or SO Boolean Field Has Been Ticked 				                      -  Yes

**Comment by IT-Saravanan** [comment]
*Once uploaded Same (BO) System allowed and generating lines Again (Test Case: Block Order No:13108200001)
*Upload Set No B-28-140120, Sales order No: 41001200015, Line No 60000, Not Updating Demanded By, And Demand Ref No:
*In MRP For selecting block Order first time the revised boolean field has ticked

**Comment by prabhupdesh** [comment]
[MRP.docx](https://github.com/BPS-Industries/Navision/files/5010297/MRP.docx)

**Comment by prabhupdesh** [comment]
Need to add more functionalities as below:

1. While creating purchase order, system should check if any PO already present for same vendor and same expected receipt date. If present, item line should be added in the purchase order. Dampener period setup in item card should be used.

2. Need to explore dampener period,

**Comment by prabhupdesh** [comment]
Ananthi
1. Indent type = production for ananthi, sreejothi. Better check indent type for all relevant users
2. Option to select sample Order
3. Needs form link not working
4. Show material tracking report
5. Show indent sent date
6. In mail alert, show buyer PO no. also
7. Send alert to merchants, Akhtar sir, Ananthi,sreejothi, stores, purchases, ravindran
8. Requisition no. to be PO wise
9. Cancel button in MRP page
10.BOM,SO,Upload Set.No,VDF View in MRP Page

Ghouse
1.on top of the Material Tracking from requisition report Sales Header details also to be placed
2.Link should be Ananthi(Uploading Source Document) ->Kumar(Check Inventory)->Ghouse(Creating PO based on inventory availability confirmation by stores team

**Comment by IT-Saravanan** [comment]
Ananthi's Requirement 

1. Indent type = production for ananthi, sreejothi. Better check indent type for all relevant users
2. Option to select sample Order
3. Needs form link not working
4. Show material tracking report
5. Show indent sent date
6. In mail alert, show buyer PO no. also
7. Send alert to merchants, Akhtar sir, Ananthi,sreejothi, stores, purchases, ravindran
8. Requisition no. to be PO wise
9. Cancel button in MRP page
10.BOM,SO,Upload Set.No,VDF View in MRP Page

Ghouse Requirement,
1.on top of the Material Tracking from requisition report Sales Header details also to be placed
2.Link should be Ananthi(Uploading Source Document) ->Kumar(Check Inventory)->Ghouse(Creating PO based on inventory availability confirmation by stores team

**Comment by YashwanthGowdaJ** [comment]
For Type of indent = Merchant,PD and Management, while sending mail from indenter, Buyer PO No., Demanded by should be same as requisition No. and demanded ref. No should be 10000 by default as these fields will not contain any values for those cases.

**Comment by YashwanthGowdaJ** [comment]
Ananthi has faced below issues.
1. While changing item No., customer season, entity and location code is becoming blank
2. While changing Item No., quantity is changing for few items(its converting base UOM to Purch. UOM)

**Comment by YashwanthGowdaJ** [comment]
While Suganthi using block orders for creation of indent, quantity is zero in block order. Needs to take care of this scenario.

Block order No : 13109200006

**Comment by ramapandian14** [comment]
If Sales Order has been created against block Order.We can take Qty Booked field or Else we can instruct user to select Sales Order directly in MRP..

**Comment by YashwanthGowdaJ** [comment]
Included Sample order in the selection list to polulate indent. Currently this development lies in test server. Saravana, please test this and confirm moving to live

**Comment by prabhupdesh** [comment]
As discussed during meeting with merchants & mr. bawa on 26-09-20

1. PD Indent
2. Production Indent
3. **CL Indent**
> a. MOQ Indent
> b. At customer Risk
4. **Management Indent**
> a. Safety valve
> b. For customer
> c. VDF (raised by merchants & approved by management)
> d. Fat boy indent (raised by merchants & approved by management)
>>1. Will run on VDF,CSO,BO,SO as usual
>>2. Select only PU,LI,HW,PK-TI,PK-HE,PK-HA,PK-TY,PK-ID related materials
>>3. Send for approval to management
>>4. Management can approve or reject
>>5. If management approves, get confirmed and forwarded to sourcing with cc to merchants
>>6. If management rejects, comes back to merchants

**Comment by prabhupdesh** [comment]
Needs form from CSO buffer is required

**Comment by IT-Saravanan** [comment]
In MRP Screen Product Development (PD) Indent Ananthi & Vidhya  need option to select the FGD in item Card.

**Comment by IT-Saravanan** [comment]
As Discussed While Selecting Block Order System Need to  Assign Block order no for Buyer Po Number.

**Comment by IT-Saravanan** [comment]
[Uploading MRP Stores Document.docx…]()

**Comment by IT-Saravanan** [comment]
[MRP Stores Document.docx](https://github.com/BPS-Industries/Navision/files/5305125/MRP.Stores.Document.docx)

**Comment by IT-Saravanan** [comment]
[MRP Stores Document.docx](https://github.com/BPS-Industries/Navision/files/5305186/MRP.Stores.Document.docx)

**Comment by IT-Saravanan** [comment]
As discussed on 01/10/2020 
1.Style No& Name  Make Non-Editable
2. FG No - Make Non-Editable
3.Quantity UOM Purchase - Make Non Editable
4.Remove Confirm UnConfirm Button
5.Auto Confirm for Sending Send Approval Request
6.Auto Un confirm For Rejecting Approvals
7.Show Indent Type in approval Lists ( Fatboy, Safetyvalve,Customer risk & VDF

**Comment by IT-Saravanan** [comment]
Need To Hide Button Stores Employees
1.Purchase accept
2.Purchase Unaccept
3.Create Purchase Order
4.Show Purchase Order
5.Split Qty
6.Reservation Entries
7.Show Worksheet

**Comment by IT-Saravanan** [comment]
As Discussed on 05/10/2020
1.Hide confirm\ Unconfirmed Button
2.Hide Reject Button
3.Hide Reservation Entries
4 Hide item Tracking Lines
5.Need To Add One Field For bucket for Stores Purpose Based on customer, Delivery month & Year, Example (Party: Ecco Delivery Month is December Delivery Year is 2020. Bucket Will Create ECC1220)
7. If Multiple Delivery Dates is there in one Block Order we need take Which is the Earliest month delivery month lying in the lines 
8.Merchants Needs Mail Alert for Sending Approvals For Management Indent & after management Confirms  indent that time also they needs the intimation Mail.

**Comment by IT-Saravanan** [comment]
As Discussed with  Veera & Suganthi, Regarding Bucket No:
Bucket No is generated based on Customer Name And Customer Delivery Month and delivery Year
IF customer is ECCO Block Order Delivery Month is October Delivery Year Is 2020
We Are allocating ECC1020 as a bucket No. Ecc is a customer posting group, 10 Is Month and Year is 20.
If Same Customer given order same Delivery month and year we are allocate Bucket No. is Everything remain Same Additionally Added Alphabets Like (A,B,C,D)
They are using Previously this same method Manually.
Veera needs Sketch attachment for MRP Alert Mail

**Comment by IT-Saravanan** [comment]
As discussed on 08/10/2020, Regarding Approval for Management Fat boy indent
Approval not required for fat boy Indent,We will remove approval for fat boy materials

**Comment by ramapandian14** [comment]
Mail alert for concern merchant also included while Pre-Production confirm the indent to Store in MRP Page

**Comment by IT-Saravanan** [comment]
As discussed for purchase team needs Vendor Filter in the Indent N Sourcing Page

**Comment by YashwanthGowdaJ** [comment]
"Earliest Drop Dead Material In Date" added in a MRP IndentNSourcing page(as a variable), Needs form and Material Tracking reports. 

This field is fetching the data which is earliest among all the demanded lines(eg. In all the block order lines) from "DD Material In Date" field from "Cust. & vend. dates" table through demanded By and Demanded Ref. No.

**Comment by YashwanthGowdaJ** [comment]
Given a new functionality in IndentNSourcing page to create job work orders automatically.

Based on location, entity, customer season, due date job work order lines will get populated.

**Comment by IT-Saravanan** [comment]
As Discussed with Ghouse & Raja, His team Needs this Requirement in Indent N Sourcing Page
1.Item Filter 
2.Vendor Filter
3.Expand MRP Page Based on Item & Vendor

**Comment by IT-Saravanan** [comment]
As Discussed 
1.Place a Boolean field in purchase Header For Planned from MRP  
2.Mail Alert to Purchase team pending from their Side, (Stores Confirmed But purchase order not yet Created )

**Comment by IT-Saravanan** [comment]
As discussed Daily Mail alert for Stores & Sourcing
1. Need report For Stores Confirmed Sourcing not Accepted (Need to create Purchase order)
2. Need report For Production Team Confirmed Stores not confirmed (Stores Need to Update Stock and Confirm)
3. Item Filter & Vendor Filter Moved to live 
4. Buy to Stock & Customer Liability Page Created , (working on that).

**Comment by YashwanthGowdaJ** [comment]
1. Till now for fat boy indent, while purchase team accepting the order, at the same time, stores confirmation was also happening. As we need to send fat boy to the stores, we have removed this feature for fat boy and VDF.

2. If requisition line location is '15-18', then purchase order is automatically creating in '17' location. Moved this to live

**Comment by prabhupdesh** [comment]
Need to take care of below github id:
#92 
#93 
#94

**Comment by prabhupdesh** [comment]
#95

**Comment by prabhupdesh** [comment]
#96

**Comment by YashwanthGowdaJ** [comment]
![image](https://user-images.githubusercontent.com/61491976/98068811-25e13f80-1e83-11eb-87b8-da6520f400ac.png)

About multiple quantities fields and usage of those fields

**Comment by YashwanthGowdaJ** [comment]
#98

**Comment by YashwanthGowdaJ** [comment]
As like 44-Stock and 99-Stock, we have given Mepz stock for entering the stock.

If requisition lines contains both mepz and non mepz locations, then the stock confirmation is required from both the sides.

**Comment by IT-Saravanan** [comment]
#114

**Comment by IT-Saravanan** [comment]
IN MRP Buy to Stock indent & PD Indent, If it is Fixed asset dont allow quantity Greater than 1 or Less than 1
