### ISSUE TITLE
Vendor Advance - PO Link

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#65]
PO has been created and Click -> Mark Document Sent By Purchase Team.
Accounts will receive an alert for payment through mail.
Accounts will create a payment journal entry and link the Purchase order to relevant Payment Entry.
Click advance paid and mail alert will go to purchase team in Navision,

Development :-
1. Create a field called "Purchase Order No." in general journal lin and show in payment journal page
2. Lookup should show only those purchase orders for which "Document Sent"= TRUE and "Contract" = FALSE. Some additional filters can be placed on vendor no. Contract field is being used as "Advance paid" in purchase order
3. While sending for approval, system should check either "Applies-to Doc. No."  or "purchase order no." must be filled, only in those case where "Account type" = vendor and amount is positive.

**Comment by prabhupdesh** [comment]
Either applies to doc no. or purchase order no. must be filled in case account type = vendor and amount is positive.

Additionally, in purchase order no. you can place a filter to show only those purchase order which pertains to vendor selected in account no. field.
Also filter by entity &  Autopopulate location from purchase order.

**Comment by prabhupdesh** [comment]
More controls:

Amount in journal line cannot be greater then purchase order value
A button in purchase order page to show all advances paid against the purchase order

**Comment by IT-Saravanan** [comment]
**Added** 
*Purchase Order.No field in General Journal Line
*Purchase Order list will not show pertaining to vendor selected in account.no field
*System throw error if user haven't selected select ''Applies to doc.no" or "PO.No " if Account type =Vendor and amount is Positive

**Comment by YashwanthGowdaJ** [comment]
Additional filters in PJ while selecting Purchase order No.

1. Status must be released.
2. Document type is order
3. PO category is either order or contract.

If all these are working fine, then close the task.

**Comment by IT-Saravanan** [comment]
Vendor Advance payment functionality moved to live and working fine
