### ISSUE TITLE
Purchase order - Customer Seasons Mandatory

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#66]
Found certain ILE entries as per below, where although customer season has been entered in purchase order, it  has not flown to ILE at the time of GRN, possible reason being customer season got removed from purchase lines.

Yashwanth - can you place a control at the time of purchase order send approval and approving a purchase order that if customer season is not specified in purchase header and purchase line , it should not allow continuing.

10401190223
10402190127
10408190361
10401200150
10401200428
10401200429

**Comment by YashwanthGowdaJ** [comment]
Customer season is made mandatory while sending an approval, and also while approving. I have made changes in live server. Please test

**Comment by IT-Saravanan** [comment]
Customer Season Mandatory : That functionality moved to live and working fine,
In Purchase order while sending approval and also approving time if customer season is blank system showing error.
