### ISSUE TITLE
Breaking transactions by Division/Customer Season

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#7]
An automated batch job to break payments by division in GL Entries

**Comment by prabhupdesh** [comment]
1	Posting  a purchase invoice			
Inv no.	INV001			
Header	V1			
		Qty	Rate	
Lines	Belt	10	1	10
	Bag	20	2	40
	Wallet	30	3	90
	Wallet	40	4	160
				300
				
Dr	Cr			
Purchase	Vendor			
300	-300			
				
				
2	Making a payment through application			
				
Dr	Cr			
Vendor	Bank/Cash			
300	-300			
				
				
3	Allocation			
				
Dr	Cr			
Vendor..10				
vendor..40				
vendor..90				
vendor..160				
	Vendor..300

**Comment by IT-Saravanan** [comment]
**Breaking Payment transactions by Division Wise** 
Posting the Purchase invoice time here given one action button called *get ratio after click the button the purchase invoice automatically calculated the division wise ratio.
once the payment done against the purchase invoice, after going to Recurring General Journal here given Two action Button called get details & Allocation. In Recurring General Journal to type the payment document number and click the get details button it is automatically populate the payment details, after click the button Allocation it is automatically Allocate the payment division wise by ratio,
*Still Working on the post of the recurring General journal
