### ISSUE TITLE
Purchase invoice, GST Exempted = TRUE

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#70]
In purchase invoice, if "GST Exempt" is choosen as structure, then exempted should be TRUE in purchase lines

**Comment by IT-Saravanan** [comment]
In Purchase invoice if user select the GST structure GST EXEMPT in lines it is automatically updated in test server I have checked so yashwanth move this Functionality to live.

**Comment by YashwanthGowdaJ** [comment]
Moved this to live.

**Comment by IT-Saravanan** [comment]
1. In Purchase invoice if user select the Gst Structure GST EXEMPT in the purchase Header, there after Entering invoice details the lines Exempted Boolean Field is automatically Ticked.
2.In Purchase Invoice if user Select the GRN No in purchase header, lines automatically populated and with Exempted Field ticked 
3.In Purchase invoice user going to Functions select Get receipt lines  and select the GRN that time also Exempted Field is Ticked 
4. If the lines are present, then user tries to change the structure in header, then gst exempted field in lines will be ticked.
5.If the user selects structure other than GST exempt, then if lines were present with exempted as true, we need to untick exempted field

**Comment by IT-Saravanan** [comment]
Task Completed
