### ISSUE TITLE
Employee card - transport applicable

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#73]
![image](https://user-images.githubusercontent.com/61455315/89270118-841a3e80-d658-11ea-994b-b8d2057a89c8.png)

**Comment by prabhupdesh** [comment]
Transport applicable field in employee card should be non editable
Place a button called "Transport applicable" with confirmation message. Clicking on this button will set transport applicable field

**Comment by prabhupdesh** [comment]
Please update

**Comment by YashwanthGowdaJ** [comment]
As far as I remember, I have done this development in test server, but not moved to live. I will check the test servers and I will move to live

**Comment by IT-Saravanan** [comment]
transport applicable funtionality working fine for new employees, but need to check already the employee having transport applicable

**Comment by IT-Saravanan** [comment]
If already pay elements inserted and transport applicable is not ticked. transport applicable not becoming true.

**Comment by YashwanthGowdaJ** [comment]
@IT-Saravanan I have taken care of above mentioned point. Please check

**Comment by IT-Saravanan** [comment]
Task completed, functionality working fine. please close this task
