### ISSUE TITLE
Report Issue :- Cost sheet summarized vs Version cost summarized

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#77]
Cost sheet summarized vs Version cost summarized
------------------------------------------------------------

In cost Sheet Summarized Rate(USD) for Leather is showing Correct
But Version cost summarized Rate (USD) for Leather is showing Wrong

Calculation in cost sheet summarized
------------------------------------------
Ext(USD)/Total Cons. = 0.97/.035 =2.76

Calculation in Cost Sheet-FGD. No:- D-M-UCM-LE-20-16-1
---------------------------------------------------------------------
Total consumption (Including BO %) * Rate (USD) = 0.35 * 0.344 =0.1204 for Leather
Total consumption (Including BO %) * Rate (USD) = 0.37 * 2.301 =0.849   for Crust

Adding of LE +CR =0.1204 +0.8409 =0.97(Extension (USD)

**Comment by YashwanthGowdaJ** [comment]
Previously the code(based on above calculation) was found only in cost sheet summarized report. So it was showing proper values. Added the same code in version cost sheet summarized report too.

We are not doing any changes in cost sheet and version cost sheet reports.

[VCS summ 160920.txt](https://github.com/BPS-Industries/Navision/files/5230105/VCS.summ.160920.txt)
[CS summ.txt](https://github.com/BPS-Industries/Navision/files/5230106/CS.summ.txt)
