### ISSUE TITLE
Wallet BOM Project Study

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#79]
**FGP/FGD TYPE for Randa ->Belt**
-------------------------------------

1. Papa Card -> Colourwise
2. Child card ->Warehouse wise

**FGP/FGD TYPE for Non Randa ->belt**
--------------------------------------

1. Papa Card ->Colorless
2. Child card >Color wise

Belt Vs Wallet
--------------------------
Belt ->Belt size
Wallet ->Same Design(Sub Cat or Type while Create items for FGP) with Different Colors(black or Grey)

Wallet Papa -> Sub Cat or Type
Wallet Child  ->Colors with WH

**Comment by ramapandian14** [comment]
FGP/FGD TYPE for Randa ->Wallet
----------------------------------------
Papa Card -> Colourwise
Child card ->Warehouse wise

FGP/FGD TYPE for Non Randa ->Wallet
-------------------------------------------------
Papa Card ->Colorless
Child card >Color wise

BOM Structure
-----------------------
1.Main/Visible
2.Invisible
3.Consumable
4.BOM Specific
5.Whse Specific

Sales Order for Belt
------------------------
User will enter Belt sizes in Sales line(Belt size field -32/34/36/38/40)

Wallet
---------
User have created a warehouse (W1) in Block /Sales Order
Later Whse revised from W1 to W2
User Will enter Whse in Sales Line(WhseField -W2)

Based on actual warehouse user have created relevent whse BOM in Whse Master.
System will pick automatically from WHSE BOM.

**Comment by YashwanthGowdaJ** [comment]
While working on wallet BOM heirarchy, I arrived with few doubts,
1. If item cards were created without warehouse, then no need to include "WH specific PnP" division on production BOM's as the WH will be entered in sales orders, we were unable to know for which WH, BOM is created.

2. Based on the WH mentioned in sales orders, needs form will pick relevant WH items from WH master and will be shown.

WH- Warehouse

**Comment by YashwanthGowdaJ** [comment]
Ram/Saravana,

I have developed wallet BOM heirarchy in test server. Right now wallets will also work same as belts as per my development. Please test and let me know how far I have reached.

I have worked on creating new wallets BOM. When user tries to create new BOMs for belts, BOM heirarchy will be applicable. 

Need to work on existing BOMs
