### ISSUE TITLE
Warehouse entries for Job Work

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#8]
Job Work Order Process in Navision
1.Material will send from 44 to Jahan.
2.Material will consume Jahan.
3.Output of finished material in 44 Location.

**Comment by ramapandian14** [comment]
Job Work Order Issue
------------------------------
1.Material will send to Vendor Location 

Transferring the Material from 44 to Jahan 

 ILE                                   Warehouse Entries

44    =-100  (Transfer)             No Entry 
Jahan =+100

2.Material Consumed in Vendor Location

ILE                                                       Warehouse Entries

Jahan =-100(Consumption)                 No Entry (Negative Adjustment of -100 should create)

3.Receiving the Output Material from Vendor Location

ILE                                        Warehouse Entries

44 -+100(Output)                Positive Adjustment of +100

Issue
---------
System is not creating a warehouse entries against Consumption Entries in Navision.
ILE Net Qty -100
Warehouse  -200(Actual Should be 100)

**Comment by ramapandian14** [comment]
Please Check..

**Comment by ramapandian14** [comment]
Warehouse Entries are not created for job work

**Comment by YashwanthGowdaJ** [comment]
Ram,

I am creating warehouse entries for both positive adjustment & negative adjustment with the sending material. Kindly check...

**Comment by ramapandian14** [comment]
Completed and moved to Live..
