### ISSUE TITLE
GST Reconcilation 

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#80]
**Facing Issues in Reconcile Time**
scenario 1 - Document Date Mismatch
Scenario 2 - External Document Number Mismatch
Scenario 3 -Wrongly Updated of GST Values (Ex: Vendor Invoice contains IGST Wrongly Maked Entry in CGST & SGST)
Scenario 4 -Wrong GSTIN 
Scenario 5 -Taxable Value Mismatch

**How to Resolve** 
Scenario 2 - There is one option is there Go to Filter  (update invoice details ) there we Can Alter Vendor Invoice Details as per GSTR 2A,

**Comment by pranav7712** [comment]
Hi.. Is there any program or module developed for doing the reconciliation of GSTR2A with the purchase ledger?

**Comment by prabhupdesh** [comment]
A GST tool software being used by accounts for GST reconciliation
