### ISSUE TITLE
Tritan Invoice wrongly booked in Expenditure of BPS

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#82]
User have selected a fixed asset in purchase Invoice. 
User have selected a dimension as BPS while creating a fixed asset card in Navision.
Based on above information Entity is flowing in Purchase Invoice lines

**Comment by prabhupdesh** [comment]
Ram, please update , is this completed?

**Comment by ramapandian14** [comment]
Completed the Task
