### ISSUE TITLE
Close Customer Season for Closing Prices

### ISSUE THREAD

**Issue by ramapandian14** [BPS-Industries/Navision#85]
1.Create a Close Customer Season Button in Dimension Values.
2.**Status** should be **Released** as well as **Blocked -No** in **Dimension Values-Customer Season** .
3.User will open the Close Customer season Button it will Populate all the list of items with Inventory availability by same Customer Season wise as well as break by Entity/Location/Bin code wise.

**Note**:-
-------------
1.System should not allow me to populate the items  if **Status** should  not be **Released** as well as **Blocked -Yes** in **Dimension Values-Customer Season** .
2.If Stock is available in Same Customer season(20-TRT-ALL-ALL-AS but with different Location/Entity/Bin Code.
3.User need to update a new Customer Season as 20-TRT-ALL-MB-AS for all three lines in same items with different Location/Entity. 

Item.No | Location | Entity | Customer   Season | New Customer   Season | Bin Code
---------------------------------------------------------------------------------------------------
PK-DK-HE-19-95-1 | 44-MAIN | TRITAN | 20-TRT-ALL-ALL-AS | **20-TRT-ALL-MB-AS** | 44-UA
PK-DK-HE-19-95-2 | 99-MAIN | BPS | 20-RAND-ALL-All-AS    | **20-TRT-ALL-MB-AS** | 99-UA
PK-DK-HE-19-95-3 | 99-MAIN | TRITAN | 20-TRT-ALL-ALL-AS | **20-TRT-ALL-MB-AS** | 99-UA

**Comment by ramapandian14** [comment]
[CS Transfer.xlsx](https://github.com/BPS-Industries/Navision/files/5290265/CS.Transfer.xlsx)

**Comment by ramapandian14** [comment]
**Yashwanth**

1.Need to create a field named as **Unit cost Difference**.
2.If Unit Cost as 100 but user will enter unit cost (Revalued ) as 120  & Difference of 20 will populate in **Unit cost Difference**.
3.Based on Unit Cost Difference system will automatically post the revaluation journal for Item with new customer season in Navision.

**Comment by prabhupdesh** [comment]
No idea on this. Closing as of now
