### ISSUE TITLE
Changing location code in MRP

### ISSUE THREAD

**Issue by prabhupdesh** [BPS-Industries/Navision#92]
Requirement from gajendra:

We have created PO# 10310200233 for the REQ094 selected Location 99-Main. But we need to place order for 44-Main. Please give me an option to select Location code when creating Purchase Order.
for now i can change all the line to 44-Main. I am asking for future sir.

**Comment by prabhupdesh** [comment]
Status please??

**Comment by IT-Saravanan** [comment]
Sir
we have given functionality to purchase team to change the location before creating the purchase order.

**Comment by YashwanthGowdaJ** [comment]
Change location has already been given in MRP. Before creating the purchase order, if they want to change location, they can change and then the PO will be created under the changed location.

![image](https://user-images.githubusercontent.com/61491976/122347223-70718100-cf67-11eb-8d70-a68e9888e4ee.png)
