### ISSUE TITLE
Changes Done in warehouse receipts for MRP

### ISSUE THREAD

**Issue by YashwanthGowdaJ** [BPS-Industries/Navision#98]
As many lines were getting created in purchase orders for same item, users were facing difficulties while doing GRN.

Changes done in warehouse receipts.

We have given a summarized page of warehouse receipts line, which is a combination of all the receipts line based on Receipt No, item No and Source No with summation of quantity. When users tries to enter quantity to receive in summarized line, the Qty to receive field in receipts line will automatically splitted based on quantity.

Bin code and Date of manufacture will be entered in summarized line, and will be assigned same in receipt lines.

Created a new field in gate entry attachment table called as "Gate entry line No", to avoid primary key constraint while doing "Get gate entry lines".

Changes in CU 90(purch Post)
Previously, as gate entries were created based on warehouse receipt lines, for each line, different gate entries will be attached. But now same gate entry will be attached for all the receipt lines.

So, instead of closing  gate entry, record wise, we are closing it based on Receipt No.(For each receipt No. gate entry will be closed once)

**Comment by YashwanthGowdaJ** [comment]
Technically, we are running a query to populate warehouse receipt summary line

**Comment by prabhupdesh** [comment]
Changes done
