### ISSUE TITLE
Need Error Message in Incoming Document 

### ISSUE THREAD

**Issue by IT-Saravanan** [BPS-Industries/Navision#99]
Need Error Message in Incoming Document If Vendor Purchase Invoice is already Exist

**Comment by YashwanthGowdaJ** [comment]
![image](https://user-images.githubusercontent.com/61491976/98435751-91cddd00-20fb-11eb-8e20-7ef9ef287af4.png)

Requested by Nirmal and Sivakumar

**Comment by YashwanthGowdaJ** [comment]
While validating vendor number invoice, system will check whether the combination of entered invoice No and vendor No. purchase invoice is present or not. Checking with both purchase invoice and posted purchase invoices.

If purchase invoice is present with the entered combination, then system will throw an error.
